### ISSUE TITLE
Allow rendering of text to collages

### ISSUE THREAD

**Issue by jazmit** [elm-lang/core#118]
Could we have a function in the Collage or Text package that allows rendering of text to the 2D canvas?

eg: (if in the Collage library)
````elm
fromText : Text -> Shape
fromTextWithMaxWidth : Text -> Float -> Shape
````
I know it's possible to convert the text first to an Element, then to a Form, which overlays a span on the canvas. However this doesn't support text stroke styles, and scaling can be wonky.  I'd also like this so we can have text in WebGL (once we've added a function to elm-gl to convert a collage to a webgl texture).

Am happy to have a stab at doing a pull request for this if folks think it's a good idea?

**Comment by TheunisKotze** [comment]
Canvas text would be great..  There seems to be an issue when scaling toForm'ed text, the size of the resulting div is off, resulting in an incorrect final position.

Performance is also quite bad atm, I'm hoping this will help out with that too

**Comment by rehno-lindeque** [comment]
I chatted a bit to Evan about having pure canvas `Form` version of text - and it sounded like he was positive about it. This would also take a lot awkwardness out of use cases like this one: https://groups.google.com/d/topic/elm-discuss/rLwnzss-hBQ/discussion

**Comment by jazmit** [comment]
Opinion so far seems pretty positive, so I've made a start on this:
https://github.com/jazmit/core/commit/8a2c7f4cb21e99c609638d631d5a6aa6a74733e6
We can now render Text to canvas with outline, gradient, fill, etc, but text css properties (weight, font, etc) are currently ignored.  I'd love some feedback on the following before I finish it off and submit a PR:
- To implement this, I changed the Shape type alias to become its own ADT which could break some existing code if it constructed `Shape`s using the type alias directly rather than the polygon function (as it probably should do).  If we want to use the existing `filled` and `outlined` functions with text, text must share a type with `Shape`s, as Elm isn't polymorphic this way.  The other option would be to have special `filledText` and `outlinedText` functions.
- To implement the css attributes, it would be best if I refactored the native Text module.  It currently builds up styles as a CSS string, which means we'd have to parse CSS in the Collage module to use the values.  It would be possibly better to build up styles as a JS object, and only convert to CSS on rendering.  Does anyone see any objections to this?

**Comment by rehno-lindeque** [comment]
It took me a moment or two to grasp that this commit actually takes a styled `Text` type instead of a `String` type - this does seem very useful. I wonder if it's ok to merge this in as is, ignoring the styles applied to the `Text`. We'd love to use it asap! :)

I was going to say that I wonder if `Shape` constructors should be hidden from the export list for `Collage`. I suppose one reason for exporting them might be to allow users to pattern match on their shapes, but using them to construct shapes instead of `polygon` and `text` does seem dodgy.

**Comment by jazmit** [comment]
I agree vis. the constructors, but I see that jvoigtlaender is dealing with
the exports and want to keep this PR focused.

James Smith
james@schoolshape.com

**Comment by jvoigtlaender** [comment]
Whether or not to export the `Shape` constructors here is really Evan's call to make. In all the export-list PRs related to https://github.com/elm-lang/elm-lang.org/issues/173, I was mainly following what intentions were already expressed in the `elm-doc` style documentations.

**Comment by TheunisKotze** [comment]
Nice! Looks good to me.. from a quick look only obvious thing missing is text-alignment (non-issue for me personally)

**Comment by jazmit** [comment]
Yeah, I skipped text alignment for now, because the alignment functions in `Text` all return `Element` - incorporating could be controversial.  Any ideas?
