### ISSUE TITLE
Textured shapes performance issue

### ISSUE THREAD

**Issue by etaque** [elm-lang/core#119]
Hi,
Textured shapes consume way too much CPU, see this issue:
https://github.com/elm-lang/elm-lang.org/issues/186

(below my original comment)

Hitting this as well with Elm 0.14 on [Tacks](http://www.playtacks.com/). Here are Chrome CPU profiling screenshots:
 - with racing area as a filled rect:

![54a4979a120000300001ae3e 2015-01-18 18-58-56](https://cloud.githubusercontent.com/assets/40526/5793448/2a4f6778-9f44-11e4-858b-c70a09182a7f.png)

- with racing area as a textured rect (image being 200*200 jpeg file):

![54a4979a120000300001ae3e 2015-01-18 18-58-41](https://cloud.githubusercontent.com/assets/40526/5793449/2a524e3e-9f44-11e4-87c4-a1abf85b4078.png)

**Comment by jastice** [comment]
See also https://github.com/elm-lang/elm-compiler/issues/724

**Comment by dy-dx** [comment]
I am getting an infinite loop when rendering a textured shape, using this code:

https://gist.github.com/dy-dx/4213cab10354b1c9b060
http://share-elm.com/sprout/55089d4de4b0d720e25d6386

This function keeps calling itself til my browser crashes:
https://github.com/elm-lang/core/blob/master/src/Native/Graphics/Collage.js#L143

**Comment by dy-dx** [comment]
OK, I've got a fix for the issue: https://github.com/dy-dx/core/commit/b67635080b9316ecbb253acf952f309817ad3984

These changes work when I edit the compiled JS from elm-make, but unfortunately I have no idea how to build/test the entire project. Can someone help me out?

**Comment by evancz** [comment]
Sorry this did not get attention til now! The `Graphics.*` modules now live in `evancz/elm-graphics` so I am trying to get stuff migrated over there. I'm hoping this will make it easier to get help on stuff like this!
