### ISSUE TITLE
Initial value in a channel ignored in foldp

### ISSUE THREAD

**Issue by rehno-lindeque** [elm-lang/core#148]
The initial value in a `Channel` doesn't appear in a foldp over the channel converted to a Signal.

```elm
type Action = Init
            | ...

actions : Signal.Channel Action
actions = Signal.channel Init

update : Action -> Model -> Model
update action state =
  case Debug.log "action" <| action of      -- Debug.log never prints "action: Init"
    Init -> ...

model : Model -> Signal Action -> Signal Model
model initialState action =
  Signal.foldp update initialState action  -- Seems like the initialState here should be
                                           -- combined with the initial action, either
                                           -- to create the first value or to create the
                                           -- first two values in the signal

main = run emptyModel (Signal.subscribe actions)

```

Initializing a signal with a good `initialState` is not always easy because initialization may depend on a signal coming in from a port in which case you need to do something like this:

```elm
port userId : Signal Int

main = run emptyModel (Signal.zip (Signal.subscribe actions) userId)
```
...in this case creating an initial model based on the incoming `userId` seems near impossible unless some event can be triggered (perhaps by explicitly calling `send` on the `userId` port after the widget has been initialized in order to force an update).

This might assist with issues like this one as well: https://github.com/elm-lang/core/issues/91. I'm not taking the work on promises into account, I don't know if this may be handled already in the upcoming implementation.

**Comment by jvoigtlaender** [comment]
Maybe you want `foldp'` from http://package.elm-lang.org/packages/Apanatshka/elm-signal-extra/3.2.1/Signal-Extra?

**Comment by rehno-lindeque** [comment]
Oh thanks! That one totally slipped my mind, I gave it a try:

This did indeed do the trick...
```
Signal.foldp' update (flip update emptyModel) (Signal.zip action ownerId)
```

This still feels like some pretty strange behavior though? It completely blind-sided me that the first value in the signal was ignored by the fold.

**Comment by evancz** [comment]
The "initialization" phase is different from the "running" phase. Imagine writing this code `foldp (\_ c -> c + 1) 0 Mouse.clicks` and having the initial value be 1!

In the TodoMVC app, I [bring the initial value in as a value, not a signal](https://github.com/evancz/elm-todomvc/blob/master/Todo.elm#L307-L309), and that works great. Is that not plausible for your case?

**Comment by rehno-lindeque** [comment]
Unfortunately not really - we have a button that allows admins to act on behalf of another user or as a guest (so the active user is not fixed). To be honest, I could probably change the logic so that the owner id is assigned on save rather than initialized in the widget - this is probably a better behavior.

I see what you're saying with `foldp (\_ c -> c + 1) 0`, that does make sense. I was just a little surprised... 

I won't spend any time on this because I'm sure you've thought about this much more deeply than I could ever hope to, but it does almost seem to me like one should be able to have some kind of `Mouse.click : DelayedSignal ()` where `foldp (\_ c -> c + 1) 0 Mouse.click` really does start out as 0.

**Comment by jvoigtlaender** [comment]
Can this issue be closed?

**Comment by rehno-lindeque** [comment]
I'd say this is API design and probably doesn't belong here anyway. There's been a large number of proposals  for alternate API's related to this, perhaps there will be a top-level issue in [elm-plans](https://github.com/elm-lang/elm-plans) at some point.

**Comment by amitaibu** [comment]
For posterity, I was able to "solve" a similar case where I needed an initial value to be passed to the ports, by simply sending a default value immediately after starting Elm:

```js
var elmApp = Elm.fullscreen(Elm.Main, {somePort: null});

// Make sure that the ports are getting the inital values, as by design they are being fed only with 
// changed values.
elmApp.ports.somePort.send(null);
```

It's a little hackish, but still allows one to use the start-app module.

**Comment by joeandaverde** [comment]
@evancz Is this what you were referring to as far as bringing the value in instead of signal? 

https://github.com/evancz/elm-todomvc/blob/1be0712d3fa8bf786bde84d8db5f685e23413876/Todo.elm#L330

For future reference press "y" to toggle the url you copy to contain the git commit hash so links don't break.

**Comment by mietek** [comment]
Just ran into this issue as well. The improved documentation for `foldp` seems to have [disappeared](http://package.elm-lang.org/packages/elm-lang/core/3.0.0/Signal#foldp)...

**Comment by jvoigtlaender** [comment]
@mietek, doesn't using http://package.elm-lang.org/packages/Apanatshka/elm-signal-extra/latest/Signal-Extra#foldp%27 help?

**Comment by mietek** [comment]
I couldn’t figure out how to use `foldp’`.  Eventually, I settled on the following:

```elm
type alias Model = ...

defaultModel : Model
defaultModel = ...

type Action = Idle | ...

port getState : Maybe Model -- Restores state from loadStorage

init : (Model, Effects Action)
init =
    ( Maybe.withDefault defaultModel getState
    , Effects.task (Task.succeed Idle)
    )
```
