### ISSUE TITLE
Desired operations for Transform2D library

### ISSUE THREAD

**Issue by imeckler** [elm-lang/core#151]
I think that the `Transform2D` type is a bit too abstract. I'm currently trying to debug something involving them and it's impossible to actually inspect them. The module itself provides no way to define functions out of the type, and it seems the only place `Transform2D`s can be used is in `Graphics.Collage.groupTransform`. Such a library is of general use, i.e., not only with forms, and I think some version of the following functions would be quite reasonable to add:

```elm
apply : Transform2D -> (Float, Float) -> (Float, Float)

type alias TransformView =
  { matrix      : (Float, Float, Float, Float)
  , translation : (Float, Float)
  }
view : Transform2D -> TransformView
```
In fact these two functions are interderivable (up to floating point errors), so just one would be enough if you're all feeling spartan.

**Comment by identicalsnowflake** [comment]
I was hoping for something like this, too. I'm writing CSS bindings, and I'm trying to use Elm types as much as possible, and I wanted to accept the core type Transform2D for the CSS transform property, but I can't because there isn't any way to inspect the Transform2D object.

**Comment by evancz** [comment]
Sorry this did not get attention til now! The `Graphics.*` modules now live in `evancz/elm-graphics` so I am trying to get stuff migrated over there.

That said, I would like to keep that API stable for now. I expect to be focusing on `<canvas>` for professional users and "friendly graphics" for learning as separate use cases. Progress will be made when those start happening.
