### ISSUE TITLE
Array.repeat causes a runtime error

### ISSUE THREAD

**Issue by TheSeamau5** [elm-lang/core#175]
Calling `Array.repeat` with a negative size causes a runtime error.

```
Invalid array length

Open the developer console for more details.
```

This is the code that has caused this:

```
import Array 
import Text (asText)

main = 
  asText <|
    Array.repeat -5 4
```

This behavior is not the same as the behavior with lists as calling `List.repeat` with a negative size yields the empty list.

**Comment by mgold** [comment]
@TheSeamau5 I think you can close this now.

**Comment by sindikat** [comment]
This issue still exists in Elm 0.15.1, just paste this in http://elm-lang.org/try :

    import Array
    import Graphics.Element exposing (show)
    main = show <| Array.repeat (-5) 0

**Comment by mgold** [comment]
The patch was merged after the latest version of core was released. You'll have to wait for 0.16, sorry.
