### ISSUE TITLE
Weird runtime error with eq

### ISSUE THREAD

**Issue by TheSeamau5** [elm-lang/core#177]
So, I was testing the core String library with elm-check when suddenly I had a weird runtime error.

This is the code I was testing with:

```elm
module Test.String (tests) where

import String
import Char
import Check (..)
import Random (..)
import Random.Extra (..)
import Random.String (..)
import Random.Char (..)


consUnconsInverse : Char -> String -> Bool
consUnconsInverse char string =
  let nextString = String.cons char string
  in
    case String.uncons nextString of
      Nothing -> False
      Just (c, str) ->
        c == char && str == string

tests : List Property
tests =
  [ property2 "Consing and unconsing are inverse operations" consUnconsInverse unicode (rangeLengthWord 0 1000 unicode)
  ]
```

and when I try checking my test:

```elm
import Test.String as String
import Check (check)

import Text (plainText)

testResult =
  check String.tests

main =
  plainText testResult
```

I get a runtime error that seems to point to the `eq` function defined in Javascript

Chrome (latest) : 
```
Cannot use 'in' operator to search for '0' in 饑


Open the developer console for more details.
```

Firefox Developer Edition (latest):
```
invalid 'in' operand y


Open the developer console for more details.
```

When I open the developer console, I'm immediately pointed to the `eq` function.

![screen shot 2015-02-17 at 12 58 18 am](https://cloud.githubusercontent.com/assets/3227869/6221776/3629515e-b640-11e4-9e7e-53f817fbfabb.png)

This is the moment right before the type error:

![screen shot 2015-02-17 at 1 01 32 am](https://cloud.githubusercontent.com/assets/3227869/6221797/985ccbd0-b640-11e4-9fdb-52d614b6f02e.png)

The bug happens due to a next if statement. It asks, `if i in y` except that the `in` operator only works on objects and somehow an actual string, in this case : `饑`, has managed to sneak in as y. 

![screen shot 2015-02-17 at 1 08 11 am](https://cloud.githubusercontent.com/assets/3227869/6221854/838cb502-b641-11e4-87b3-fe0536611398.png)

I speculate that what is needed is a `typeof` check for `y` the same way that there is a `typeof` check for `x` cuz `typeof "饑" === "object"` yields `false`

**Comment by evancz** [comment]
Thank you for the comprehensive issue! Love issues like this :)

This should be fixed by 6f5fbb8bc1ba2ce0fd3a3acf41e347c447689022.
