### ISSUE TITLE
Error in how polygons are drawn

### ISSUE THREAD

**Issue by imeckler** [elm-lang/core#178]
There is an error in the way polygons are draw. In short, the path defining the polygon is somehow not really being closed, and so linejoins are not rendered correctly. Here's an example showing smooth line joins being rendered jaggedly.

http://share-elm.com/sprout/54e64591e4b09711f39c2b0d

**Comment by vilterp** [comment]
Fixed by using `cap <- Padded` in the above example

http://share-elm.com/sprout/54e90d3be4b09711f39c2c88

**Comment by imeckler** [comment]
I wouldn't call that "fixed", it's just a different thing since the corners are sharp rather than smooth.

**Comment by vilterp** [comment]
Fair. Seems like it isn't treating the lower right corner as a join, and is basically just drawing it as a path. Not quite sure where to fix this in Graphics.Collage.

**Comment by evancz** [comment]
Is the fix "you can't draw closed polygons with lines"?

Currently the internal representation of `Forms` does not have any special cases, but it'd be good to have for circles and rectangles probably. I'd like to do a big set of improvements like this that includes supporting arcs, bezier curves, etc. but I think it'll be a while until then unfortunately :/

**Comment by evancz** [comment]
Sorry this did not get attention til now! The `Graphics.*` modules now live in `evancz/elm-graphics` so I am trying to get stuff migrated over there.

I don't really know what action to take on this one though, so unless there is a proposed fix, I'm not sure how valuable it is to keep this open.
