### ISSUE TITLE
Add weight option to Text library

### ISSUE THREAD

**Issue by TheSeamau5** [elm-lang/core#184]
It would be nice to have the following function in the Text library:

```elm
weight : Int -> Text -> Text
```

to set the weight of the text. Currently, one can only make things bold. But font weights vary a lot and matter especially when you mix different fonts on a page. Plus, bold can then be redefined in terms of weight like so:

```elm
bold : Text -> Text
bold = weight 700
```

**Comment by evancz** [comment]
Sorry this did not get attention til now! The `Graphics.*` modules now live in `evancz/elm-graphics` so I am trying to get stuff migrated over there.

That said, I would like to keep that API stable for now. I expect to be focusing on `<canvas>` for professional users and "friendly graphics" for learning as separate use cases. Progress will be made when those start happening.
