### ISSUE TITLE
Make "list" from the Random library use loops

### ISSUE THREAD

**Issue by TheSeamau5** [elm-lang/core#185]
I opened an issue on elm-random-extra: https://github.com/TheSeamau5/elm-random-extra/issues/1

where I spotted that I'm unable to generate lists larger that 3999 elements long (at least on my computer: macbook pro from 2011). 

This is due to how `list` is implemented. It's a recursive definition. This issue goes towards the larger goal of solving tail recursion in Elm, but I wanted to point out this example as I have found it.

**Comment by jvoigtlaender** [comment]
In the current version of `core`, `Random.list` is implemented in tail recursive fashion. And the current compiler version optimizes tail recursion. So this should not be an issue anymore.
