### ISSUE TITLE
Change type of toFloat to number -> Float

### ISSUE THREAD

**Issue by rehno-lindeque** [elm-lang/core#190]
I'm wondering whether it might be useful to change the type of `toFloat` from
```elm
toFloat : Int -> Float
```
to 
```elm
toFloat : number -> Float
```
so that one could write functions like
```elm
module Number.Format where

prettyPrint : number -> String
prettyPrint n = 
  let print = {- ... -}
  in print (toFloat n)
```

This might also be a more generic proposal to discuss than issues like https://github.com/elm-lang/core/issues/4 which might be repeated for various functions.

**Comment by rehno-lindeque** [comment]
Having said that, it's not a big deal to just implement prettyPrint as

```elm
prettyPrint : Float -> String
```

for now...

**Comment by evancz** [comment]
Consolidated all the math related stuff into the #721 meta issue. Follow along there!
