### ISSUE TITLE
Consider using arc to draw circles

### ISSUE THREAD

**Issue by jwmerrill** [elm-lang/core#2]
https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D.arc

Currently, circles are rendered as a 50-gon, which is (just barely) perceptibly pointy.

**Comment by evancz** [comment]
Sorry this did not get attention til now! The `Graphics.*` modules now live in `evancz/elm-graphics` so I am trying to get stuff migrated over there.

I'd like to keep it relatively stable for now though. I expect to be focusing on `<canvas>` for professional users and "friendly graphics" for learning as separate use cases. Progress will be made when those start happening.
