### ISSUE TITLE
Graphics.Input crashes if Text is not imported

### ISSUE THREAD

**Issue by TheSeamau5** [elm-lang/core#203]
Buttons from Graphics.Input do not work.

The following code : 
```elm
import Graphics.Input (button)
import Signal (channel, send)

chan = channel ""

badButton =
  button (send chan "") "+"
```

causes the following error : 

```
Cannot read property 'make' of undefined

Open the developer console for more details.
```

Note: this problem also exists in the latest commits.

**Comment by TheSeamau5** [comment]
Note: I encountered this problem as I tried to answer this thread on the mailing list: https://groups.google.com/forum/#!topic/elm-discuss/7aG8wS2jnBI

Kinda weird to try to explain the relationship between buttons and signals when buttons don't work.

**Comment by TheSeamau5** [comment]
Actually, there's even a more minimal example of the bug:

```elm
import Graphics.Input (button)

badButton = button 
```

**Comment by TheSeamau5** [comment]
This seems to be true of all functions in the `Graphics.Input` package. 

```elm
import Graphics.Input 

badButton =  Graphics.Input.dropDown
```

yields the same error.

**Comment by evancz** [comment]
Thanks for the reports, if you want to take a swing at it that'd be great. I am relatively overloaded, so it is not feasible for me to address every issue that comes up immediately.

As an aside about mailing list / issue protocol, can you try to do more drafting and revising such that we don't get 3+ messages in a row that could have been one? Both here and on the mailing list it makes it much harder to follow the thread of conversation, you have to do a lot of summarizing in your mind that could have been done by the author. I hope this is not offensive to say, it's just that it makes things artificially difficult.

**Comment by TheSeamau5** [comment]
No offense taken. I'll try my best. Sometimes I write several messages in a row because I had several thoughts in a row spread across the day. 

In this case, I just reported the error and didn't think I could find anything but then found a few more things along the way. 

Now, that said, I found why this has happened:

The following code totally works.
```elm
import Text
import Graphics.Input (button)

okButton = button
```

This might be potentially an issue for elm-compiler. Basically, in the Native Javascript, `Graphics.Input` requires the use of `Text` but not in the Elm code. Well, there is an `import Native.Text` but I suspect it to be somewhat broken or something went wrong in the code generation.

If it is in fact the case that it's the compiler's fault, then this is beyond my expertise. Maybe I'll modify the import line to `import Text` instead of `import Native.Text` but that sounds like just patching one instance of a bug rather than solving a deeper problem.

**Comment by TheSeamau5** [comment]
It seems that in the end there's already such [an issue in elm-compiler](https://github.com/elm-lang/elm-compiler/issues/864). It seems to be a bug in elm-make. I'm thus closing the issue here and move the findings to elm-compiler.

**Comment by evancz** [comment]
I think @mgold fixed this bug in the latest version of core. Is there a closed issue about adding a Text import?

**Comment by TheSeamau5** [comment]
You mean this? https://github.com/elm-lang/core/pull/96

I tried using button with the newer code, which I'm assuming includes the pull request you're mentioning, and it persists there too. I think it's as you described it here: https://github.com/elm-lang/elm-compiler/issues/864

There's something wrong with `elm-make`.

**Comment by TheSeamau5** [comment]
Actually, I take that back, it's fixed. What I saw was a different bug o_0. 

If you're interested, it's caused by the following code:

```elm
import Graphics.Input exposing (button)
import Port exposing (Port, message)

port num : Port Int

b = button (message num.address 0) ""
```

which yields :

```
Cannot read property 'arity' of undefined


Open the developer console for more details.
```

**Comment by evancz** [comment]
Probably has to do with implementation changes happening in 0.15 so that looks like something we can find and fix.

**Comment by mgold** [comment]
Seems right to me -- the import Text has been fixed but this arity stuff is new.
