### ISSUE TITLE
Issue with Array.append

### ISSUE THREAD

**Issue by jheiling** [elm-lang/core#205]
There seems to be an issue with Array.append:

I have the following functions for creating a jagged array and turning it into a regular array:

    initialize : Int -> Int -> (Int -> Int -> a) -> Array(Array a)
    initialize l1 l2 f = Array.initialize l1 (\i1 -> Array.initialize l2 (f i1))
    
    toArray : Array(Array a) -> Array a
    toArray = Array.foldl (flip Array.append) Array.empty

If I just call

    xs = initialize 3 3 (,)

it works as expected and xs is

    Array.fromList [Array.fromList [(0,0),(0,1),(0,2)],Array.fromList [(1,0),(1,1),(1,2)],Array.fromList [(2,0),(2,1),(2,2)]]

But if I call

    xs' = toArray xs

later, xs will be

    Array.fromList [Array.fromList [(0,0),(0,1),(0,2),(1,0),(1,1),(1,2),(2,0),(2,1),(2,2)],Array.fromList [(1,0),(1,1),(1,2)],Array.fromList [(2,0),(2,1),(2,2)]]

afterwards.

Here's a full example showning the bug:

    import Array
    import Array (Array)
    import Graphics.Element (..)
    import Text (..)
    
    initialize : Int -> Int -> (Int -> Int -> a) -> Array(Array a)
    initialize l1 l2 f = Array.initialize l1 (\i1 -> Array.initialize l2 (f i1))

    toArray : Array(Array a) -> Array a
    toArray = Array.foldl (flip Array.append) Array.empty

    xs = initialize 3 3 (,)
    xs' = toArray xs

    main = 
      [ asText xs
      , asText xs' ]
      |> flow down

**Comment by sindikat** [comment]
I think I have the [same bug](https://github.com/circuithub/elm-array-extra/issues/3) with using [`Array.Extra.resizelRepeat`](https://github.com/circuithub/elm-array-extra/blob/1.0.2/src/Array/Extra.elm#L140), which uses `Array.append` and `Array.repeat`. There's something going on from [JavaScript side](https://github.com/elm-lang/core/blob/2.1.0/src/Native/Array.js#L516).

**Comment by evancz** [comment]
Closing in favor of #649 which will track all array issues and progress on a new implementation.

**Comment by JulianLeviston** [comment]
Any progress on the new implementation? #649 doesn't seem to include any updates as at now.

**Comment by Skinney** [comment]
The new implementation lives at https://github.com/Skinney/elm-array-exploration. It can be used in your code today.  All it really needs is a final look over before it's ready to be merged. Hopefully I'll find the time to do that soon.

**Comment by JulianLeviston** [comment]
@Skinney awesome. Thanks :)
