### ISSUE TITLE
Add flipped infix withDefault (?) operator from Maybe.Extra (aka the existential operator)

### ISSUE THREAD

**Issue by rehno-lindeque** [elm-lang/core#206]
Following @evancz's comments here https://github.com/circuithub/elm-array-extra/pull/1#issuecomment-88966985 I thought there should be an issue here for discussion.

The question that remains appears to be what precedence the `?` operator should have. Here's how it is defined in [Maybe.Extra](https://github.com/circuithub/elm-maybe-extra/blob/e0d4e4b9b66e7acea0df96122e843d377f90edfb/src/Maybe/Extra.elm#L9) at the moment:

```elm
{-| Flipped, infix version of `withDefault`.
    head [] ? 0 == 0
-}
(?) : Maybe a -> a -> a
mx ? x = withDefault x mx
```

Anecdotaly, the default operator precedence for new operators has worked pretty well for me so far if that's any help...

**Comment by evancz** [comment]
Let's move this to #216
