### ISSUE TITLE
"View Source" link on package.elm-lang.org should point to its .elm file

### ISSUE THREAD

**Issue by hoosierEE** [elm-lang/core#208]
Currently, the "View Source" links for each of the core libraries point to here:
> https://github.com/elm-lang/core 

It would be nicer if these links instead pointed to the Elm code for that library.  The worst offender is Graphics.Input.Field which is 5 links away from its link on package.elm-lang.org.

Instead of linking to elm-lang/core, it should go *directly* to its source code:
> https://github.com/elm-lang/core/blob/1.1.1/src/Graphics/Input/Field.elm

I think this change would improve the user experience for people using the package.elm-lang.org documentation.

**Comment by jvoigtlaender** [comment]
Im closing this issue here. The relevant place to track this request is here: https://github.com/elm-lang/package.elm-lang.org/issues/35.

**Comment by hoosierEE** [comment]
Woo, nice! :+1:
