### ISSUE TITLE
Add Maybe.unsafe?

### ISSUE THREAD

**Issue by evancz** [elm-lang/core#215]
With lots of core functions becoming total, it makes sense to consider having a central way to live dangerously.

```haskell
unsafe : Maybe a -> a

firstNumber =
    unsafe (head numberList)
```

The `unsafe` function extracts a value or crashes. But why introduce such a crazy thing?

There are a tiny set of cases where you *know* it is going to be fine and might want this. For example, imagine you have a `Dict` and the values are lists. You would never put an empty list in your dictionary, that would be silly, so you know you can always get elements of the list. I have seen this a few times programming in languages like Elm.

The nice part of `unsafe` is that it makes the risks extremely explicit. Rather than *ever* creating an unsafe function, you can always return a `Maybe` and extract it with `unsafe`. This way, you can search through code for any occurrences of `unsafe` and quickly identify any risks. It also is a good sign of &ldquo;maybe you should try to say the same thing a different way?&rdquo;

This feels similar in spirit to [`Debug.crash`][crash] which also makes risks very obvious.

[crash]: http://package.elm-lang.org/packages/elm-lang/core/latest/Debug#crash

Can you find uses of this in your code? Please share so we can evaluate if it is a good idea!

**Comment by haf** [comment]
Have you considered adding structural typing on top of lists, to avoid this use case? That way head could be defined totally on the type of non-empty lists.

**Comment by lfairy** [comment]
I'd suggest requiring a message as well, so that in the (hopefully rare) case that it fails, we'd get some context as to what happened.

**Comment by nixpulvis** [comment]
Taking a note from Rust, I've always liked the name `expect` for this. Unsafe feels weird to me.

**Comment by jvoigtlaender** [comment]
Maybe close this? Like https://github.com/elm-lang/core/issues/216, it doesn't seem to have gotten traction.

**Comment by evancz** [comment]
Yeah, I don't think it's necessary given that we made a lot more things return `Maybe` and it has been pretty fine.
