### ISSUE TITLE
Handle Errors in Repl

### ISSUE THREAD

**Issue by MarcoPolo** [elm-lang/core#219]
When an error is encountered it's persisted across the repl. i.e.:
```
> 'sad=panda

Error in repl-temp-000.elm:

Parse error at (line 2, column 3):
unexpected "a"
expecting at least one datatype or variable definition


> pwnd = True

Error in repl-temp-000.elm:

Parse error at (line 2, column 3):
unexpected "a"
expecting at least one datatype or variable definition
```

If you are playing around and you make a mistake you essentially have to retype and rebuild the environment.

**Comment by manleyjster** [comment]
+1. This is a minor (but consistent) irritation for me.

**Comment by jvoigtlaender** [comment]
Move this over to the https://github.com/elm-lang/elm-repl repository? (If it is still a problem with the current version with `elm-repl` at all.)

**Comment by evancz** [comment]
What @jvoigtlaender said. This should be on the `elm-repl` repo if the problem still exists!
