### ISSUE TITLE
Image src URLs with spaces in them don't work for fittedImage and croppedImage

### ISSUE THREAD

**Issue by srikumarks** [elm-lang/core#221]
In the Graphics.Element package, `fittedImage` and `croppedImage` don't work for all image URLs. 

For example, if an image URL is "somewhere/my cool photo.jpg", the image won't show up with `fittedImage` and `croppedImage`. It will, however, show up when you use "image" or "tiledImage", or if the image was named "somewhere/my-cool-photo.jpg" (without spaces).

**Comment by srikumarks** [comment]
Please ignore the first few commits, but the last two are perhaps worth considering. Here is what they solve -

When we provide a "src" string to tiledImage and fittedImage functions (in Graphics.Element), the functions assume that the string contains no parens (which are allowed in hrefs). For example, "helloworld).png") is a valid src value, but will break the url setting code in these two functions.

To make these correct, we need access to the encodeURI/decodeURI and encodeURIComponent/decodeURIComponent functions available as globals in Javascript. 2ad079b adds these to Basics and b8a94d0 adds double quotes around the "src" parameters in tiledImage and fittedImage functions.

This, I think, is a useful first step, but requires the developer to ensure correct string encodings. It will be good to have a type to track the encoding status of a string so that such errors are caught by the type system.

**Comment by jvoigtlaender** [comment]
Is this issue completely resolved by #222? Then it would make sense to close the issue itself.

**Comment by jvoigtlaender** [comment]
This issue would now belong over at https://github.com/evancz/elm-graphics.
