### ISSUE TITLE
Line height stuck at 18px

### ISSUE THREAD

**Issue by justinmanley** [elm-lang/core#226]
Sometimes, I'd like to show text in the browser that is smaller than 16pt.

In some cases, that's because I'd like it to take up less space than 16pt text. At the moment, that's not possible with the Graphics.Element module. Here's what happens when you try to use different font-sizes with Graphics.Element:

![elm-line-height](https://cloud.githubusercontent.com/assets/1668487/7324606/834f1920-ea7d-11e4-9d19-b75d48034e6d.png)

That is, setting the `height` of `Text` to a value <16 will change the font-size, but the text will still take up the same amount of space; setting the `height` to a value >16 will change both the font-size and the amount of space that the text uses.

Is this a bug? I asked about it on elm-discuss and never got an answer.

This behavior is caused by the way that `Text` is handled by Elm. All `Text` seems to be wrapped in a `<div>` which, among other things, has `height: 18px`. When `height` is called on a piece of `Text`, the HTML text is wrapped in a `<span>` with `font-size` set to the `height` before being placed inside this `<div>`. 

Why is the height of the enclosing `<div>` set to `18px`?

**Comment by evancz** [comment]
Sorry this did not get attention til now! The `Graphics.*` modules now live in `evancz/elm-graphics` so I am trying to get stuff migrated over there. I am hoping that'll make it easier to get help with issues like this!
