### ISSUE TITLE
Text fields placing cursor at end of line

### ISSUE THREAD

**Issue by Lambdanaut** [elm-lang/core#227]
Sometimes when the render function for a text field is called, it places the cursor at the end of the text. 

The bug can be replicated in http://elm-lang.org/edit/examples/Intermediate/Form.elm

If you type "foobar" into one of the fields, then re-position the cursor to the front of the text and hold down the "a" key, the cursor will randomly be placed at the end of the text field after a few frames.

You can also replicate the bug by mapping a `Time.fps 30` signal into a function that renders the text fields. The cursor will constantly be placed at the end of the highlighted field. 

I tested this in Google Chromium Version 39.0.2171.65 Ubuntu 14.10 (64-bit)

Strangely it won't replicate for me in my Windows 7 Google Chrome.

**Comment by evancz** [comment]
Sorry this did not get attention til now! The `Graphics.*` modules now live in `evancz/elm-graphics` so I am trying to get stuff migrated over there.

In this case though, the `Graphics.Input` libraries did not survive the transition, so this will be impossible to reproduce.

**Comment by Lambdanaut** [comment]
No prob. Glad to see elm changing! Love it :)
