### ISSUE TITLE
Textures example from Elm website doesn't work

### ISSUE THREAD

**Issue by leonardoborges** [elm-lang/core#230]
The example is as follows:

```elm
import Graphics.Collage exposing (..)
import Graphics.Element exposing (..)


main : Element
main =
  collage 300 300
    [ textured "/stripes.jpg" (ngon 5 75)
    ]
```

Nothing is rendered and the Javascript console reports the error:

`Uncaught ReferenceError: redo is not defined`

Offending snippet taken from `Collage.js`:

```javascript
	function setFillStyle(ctx, style)
	{
		var sty = style.ctor;
		ctx.fillStyle = sty === 'Solid'
			? Color.toCss(style._0)
			: sty === 'Texture'
				? texture(redo, ctx, style._0)
				: gradient(ctx, style._0);
	}
```

I'm using Elm 0.15.

**Comment by hblumberg** [comment]
Seems like this might be an issue again: http://elm-lang.org/examples/texture

**Comment by jvoigtlaender** [comment]
No, not an issue *again*, but an issue *still*, in the sense that it will only be fixed on the site http://elm-lang.org when the next version of https://github.com/elm-lang/core/ has been released and is used for compiling the website.

So the fix exists and has been merged, but does not yet take effect in the deployed website.

**Comment by hblumberg** [comment]
Oh, I'm sorry, I misunderstood! Thanks for your quick response.
