### ISSUE TITLE
Probably outdated documentation

### ISSUE THREAD

**Issue by hossameldeenfci** [elm-lang/core#231]
In (Graphics.Input & Graphics.Input.Field)'s documentation, there seems to be referring to Signal.Channel a lot, like in the first line here, and actually all over the examples:
http://package.elm-lang.org/packages/elm-lang/core/2.0.1/Graphics-Input

The API definition seems to be correct, though.

Graphics.Input.Field documentation page:
http://package.elm-lang.org/packages/elm-lang/core/2.0.1/Graphics-Input-Field

Unfortunately, I'm not comfortable enough yet with Signal.Message to fix it myself.

**Comment by jvoigtlaender** [comment]
The changes would be very mechanical:
* `Signal.Channel` becomes `Signal.Mailbox`
* `Signal.channel` becomes `Signal.mailbox`
* `Signal.subscribe x` becomes `x.signal`
* `Signal.send x` becomes `Signal.message x.address`

That should be it.

**Comment by hossameldeenfci** [comment]
Done with the mechanical steps. If anyone could review again before sending the PR, that'd be nice. Or should I send the PR directly since I've reviewed? (Excuse me, still learning the etiquette)

The new Graphics.Input.elm: https://github.com/hossameldeenfci/core/blob/patch-1/src/Graphics/Input.elm
The new Graphics.Input.Field.elm: https://github.com/hossameldeenfci/core/blob/patch-2/src/Graphics/Input/Field.elm

**Comment by jvoigtlaender** [comment]
Looks good, just one change missing, in [this line](https://github.com/hossameldeenfci/core/blob/patch-1/src/Graphics/Input.elm#L3): the Markdown link to `send` should now probably go to `message` as well.

I think it's okay to send the PR then.

**Comment by hossameldeenfci** [comment]
Edited. Sent the PR.
