### ISSUE TITLE
Separate Path and Shape types?

### ISSUE THREAD

**Issue by jvoigtlaender** [elm-lang/core#234]
The documentation gives the impression that

```elm
outlined : LineStyle -> Shape -> Form
```

and

```elm
traced : LineStyle -> Path -> Form
```

have different types. But they don't. Which can lead to "wrong applications", like for [this user](https://groups.google.com/d/msg/elm-discuss/Dk_pb0l_ns8/QnMAjNs5_Y4J).

**Comment by hoosierEE** [comment]
Yeah, I think you're right about this.  The compiler should complain if someone gives `traced` a `circle`, or `outlined` a `segment`.  I experienced this myself, twice.  Once because I made the mistake, and twice because I forgot about the first time!

**Comment by evancz** [comment]
I agree, I implemented this in a long long ago time when it wasn't clear whether type aliases would be distinct in some way. In any case, I think it makes sense to hide all the internal details by making both of them a `type`

**Comment by jvoigtlaender** [comment]
Cool, I'll send a PR.

**Comment by jvoigtlaender** [comment]
Closed via https://github.com/elm-lang/core/pull/235.

**Comment by hoosierEE** [comment]
Nice, thanks!
