### ISSUE TITLE
Add epsilon to Basics

### ISSUE THREAD

**Issue by TheSeamau5** [elm-lang/core#238]
Defining an epsilon value is pretty basic need when dealing with arithmetic, especially to define an approximately equal operation (due to floating point errors).

While this can perfectly live in a library, I think it's worth being in the core library in the Basics module.

In JS, `Number.EPSILON` is defined as 2.2204460492503130808472633361816E-16, or 2-52.
This is not well supported accross browsers, as such, it's worth defining it as a constant directly.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/EPSILON

**Comment by evancz** [comment]
Consolidated all the math related stuff into the #721 meta issue. Follow along there!
