### ISSUE TITLE
Make `Set a` and `Dict a ()` be different types?

### ISSUE THREAD

**Issue by jvoigtlaender** [elm-lang/core#260]
Currently they are not. Which means that expressions like `Dict.get 5 (Set.singleton 7)` etc. are type-correct, even though:
* they make no sense (the particular given one makes specifically little sense, since `Set` does not itself have a `get` function)
* the documented APIs suggest that these expressions should not be valid (types of `Dict.get` and `Set.singleton` are completely incompatible, as far as a reader of http://package.elm-lang.org/packages/elm-lang/core/latest/Dict and http://package.elm-lang.org/packages/elm-lang/core/latest/Set is concerned).

**Comment by jvoigtlaender** [comment]
BTW, I conjecture `Set a` and `Dict a ()` are currently only accidentally not distinguished, similarly as in #234, where Evan indicated that at same point in the past it wasn't clear whether type aliases (which are at play here) would behave like Haskell's `type` or like Haskell's `newtype`.

**Comment by jvoigtlaender** [comment]
Closed via https://github.com/elm-lang/core/pull/263.

**Comment by evancz** [comment]
Oh, also, this means that the `toString` function is messed up for now. We may want to give the internal constructor a weirder name when we fix that!

**Comment by jvoigtlaender** [comment]
So currently it will say something like `Set (Dict.fromList [(0,())])` instead of `Set.fromList [0]`? Well, probably better to fix that, yes. Though I must say looking at the implementation of `toString` in the native JS code right now, I'm a bit scared overall. I mean, it seems that if somebody decided to have a constructor named `RBNode` in their own union type, results could be quite catastrophic?

**Comment by jvoigtlaender** [comment]
Indeed, this leads to a runtime error:
```elm
import Graphics.Element

type V = RBNode

v = RBNode

main = Graphics.Element.show v
```
