### ISSUE TITLE
changelog.md quite off for 0.15

### ISSUE THREAD

**Issue by jvoigtlaender** [elm-lang/core#266]
If anybody is currently looking at the repo's [changelog.md](https://github.com/elm-lang/core/blob/2.0.1/changelog.md) to find out what happened in the 0.15 release, which seems a very reasonable thing to do, they will get some very wrong impressions. For example, the changelog claims that `Signal` was split into `Stream` and `Varying`. It also claims that `Channel`s are now called `Input`s.

Delete the file if it serves no purpose? Seems better than giving wrong information.

**Comment by jvoigtlaender** [comment]
https://github.com/elm-lang/core/pull/42 observes that the changelog is also not accurate concerning the 0.14 release.

**Comment by evancz** [comment]
Are the facts in there still off, or were they wrong at the time of release and subsequently fixed?

If they are still wrong, lets fix them. I'm not sure what we can do if the 2.0.1 tag is messed up. I guess we can move it around, but that does not seem ideal.

**Comment by jvoigtlaender** [comment]
The facts are still off, see [the current master version of the file](https://github.com/elm-lang/core/blob/master/changelog.md).

I wasn't sure whether there's even interest in fixing (rather than just deleting) it. Given that there have been no complaints about the wrong facts since the 0.15 release, it seems nobody is looking at that file (instead, at the blog posts).

But sure, let's fix the file in master. I wouldn't change the content in the earlier releases retrospectively.

**Comment by jvoigtlaender** [comment]
I made a pull request (#268) that I hope captures all corrections and additions.
