### ISSUE TITLE
Make Runtime.js pass a linter

### ISSUE THREAD

**Issue by rtfeldman** [elm-lang/core#285]
It seems like a good idea to have Runtime.js pass a JS linter. This would maximize its compatibility with older browsers and would have essentially no downside.

**Comment by Dandandan** [comment]
ESLint with configuration is added (and some progress has been made to fix all the issues).

**Comment by evancz** [comment]
Made some progress on this, but it's not an official part of the workflow. We can talk about it in real life if this seems crucially important. My feeling is that this code is not changing a ton, so I'm not sure how much benefit would come from this in terms of bugs avoided.
