### ISSUE TITLE
Adding a Shape makes a text unselectable

### ISSUE THREAD

**Issue by Yorkst** [elm-lang/core#292]
Migrated from https://github.com/elm-lang/elm-compiler/issues/970

When I remove square, it is possible to select "Abacaba" by mouse:
```
module Main where


import Graphics.Collage exposing (..)
import Graphics.Element exposing (..)
import Color exposing (..)

main = collage 600 200 [
    {--}
    "Abacaba"
        |>show
        |>toForm
    --}
    {--}
    ,square 50
        |> filled blue
        |>move (150, 0)
    --}
    ]
```

Tested in Chrome&Firefox

**Comment by evancz** [comment]
I think we need to add `pointer-events: none` to the canvas elements that are created by `Graphics.Collage` so that the pointer goes through to lower levels. Can someone take a look at this?

**Comment by evancz** [comment]
Sorry we did not get a solution to this. The `Graphics.*` modules now live in `evancz/elm-graphics` so I think it makes sense to migrate issues like this over there if they are still a problem.
