### ISSUE TITLE
Cannot find type `Set`

### ISSUE THREAD

**Issue by ericariello** [elm-lang/core#293]
------- message from online compiler
NAMING ERROR
Cannot find type `Set`

44| update : (Time.Time, Set KeyCode) -> Program -> Program
Maybe you want one of the following?

    Int
------- if I add "import Set"
NAMING ERROR
Cannot find type `Set`

45| update : (Time.Time, Set KeyCode) -> Program -> Program
Maybe you want one of the following?

    Int
    Set.Set
------ if I change to "import Set.Set
NAMING ERROR
Could not find a module named `Set.Set`

7| import Set.Set

**Comment by jvoigtlaender** [comment]
Either of these should work:
```elm
import Set

update : (Time.Time, Set.Set KeyCode) -> Program -> Program
```
or:
```elm
import Set exposing (Set)

update : (Time.Time, Set KeyCode) -> Program -> Program
```

**Comment by jvoigtlaender** [comment]
What I really meant to say is that both of my above versions should work.

**Comment by jvoigtlaender** [comment]
@ericariello, do my comments above address your concern? Can this issue be closed?

**Comment by jvoigtlaender** [comment]
I'm closing this, as the comments above should address the issue in terms of using the imports correctly. If the feedback from the compiler is the problem, opening an issue at https://github.com/elm-lang/error-message-catalog could prepare the ground for an improved error message.

**Comment by ericariello** [comment]
Sorry for answering this late @jvoigtlaender: 
Yes, your comment helped very much, thank you!
