### ISSUE TITLE
Time.delay (Native.Signal.delay) has no kids

### ISSUE THREAD

**Issue by wetmore** [elm-lang/core#295]
The delay function creates a node in the signal graph with no kids. This means any module using delay cannot be opened in the reactor debugger, because the following code in `debug.js` will throw an error:

```javascript
function addAllToDict(node)
	{
		nodesById[node.id] = node;
		node.kids.forEach(addAllToDict);
	}
	nodes.forEach(addAllToDict);
```

`node.kids` is undefined for an output-delay-output-n node (where n is the delay in millis).

I don't know much about the signal implementation so I don't know if the lack of kids is intentional, but if it is the debugger code should account for this. Otherwise it's impossible to use the debugger on code with `delay` which is a bummer.

**Comment by AlexNisnevich** [comment]
Oh interesting. I had been wondering why the debugger stopped working for https://github.com/AlexNisnevich/kalevala after I started using `delay`.

I second that the debugger should account for this somehow. Or at least it should be documented somewhere that using `delay` breaks the debugger.

**Comment by evancz** [comment]
Thanks for the report! I think it may make sense to move this to the elm-reactor repo. cc @vilterp to confirm or deny :)

**Comment by evancz** [comment]
I am trying to be more intense about closing issues. I think the resolution here is "move the issue to [this repo](https://github.com/elm-lang/elm-reactor/issues)" so I'm just gonna commit to it. Thanks again for reporting this!

**Comment by vilterp** [comment]
Signal.delay creates an input and an output; I think if the output gets registered as a kid of the given node the reactor will be fine. I'll submit a PR; it should be like a one line change.

**Comment by wetmore** [comment]
I didn't see your reply Pete and posted [this](https://github.com/elm-lang/elm-reactor/issues/136).

Feel free to close it if you'd like.

**Comment by vilterp** [comment]
Replied there, thanks!

**Comment by evancz** [comment]
Thanks for working through this together! :D
