### ISSUE TITLE
Documentation and Design: Transform2D

### ISSUE THREAD

**Issue by maxsnew** [elm-lang/core#296]
I think the `Transform2D` documentation is overly technical in that it emphasizes the underlying matrix representation too much. Here's a link for convenience http://package.elm-lang.org/packages/elm-lang/core/2.1.0/Transform2D.

 Even people familliar with some linear algebra might not be familiar with affine transformations and their representation as 3x3 matrices where the bottom row is (0 0 1).

Most of it is pretty straightforward and easily explained but the really bad one in my opinion is "Multiplication" which doesn't even mention that multiplication of these matrices really means composition of the transformations that they represent. I think this function should be renamed to `compose`.

Also can we have pictures in documentation? They might be helpful here but maybe that's just over-complicating things.

I'd be willing to work on this but I wanted to discuss it first esp. since it's a proposed API change.

**Comment by dnalot** [comment]
I have a similar concern in another package. Two considerations: 

0. Do their type signature match any more generic functions you could borrow (or apply back) inspiration from? 
0. Are you familiar with any library on another platform that has tried this?

**Comment by maxsnew** [comment]
@dnalot Could you clarify what you mean by 2?

**Comment by dnalot** [comment]
Basically just checking if [anyone outside Elm](https://en.wikipedia.org/wiki/List_of_numerical_libraries) has set precedent we could borrow for intuitively naming graphical operations.

**Comment by evancz** [comment]
This lives in `evancz/elm-graphics` now, but I also would prefer to keep the API like it is. I think you are correct that it could be easier, but I'd like to keep that API stable for now.
