### ISSUE TITLE
Re-rendering can cause an input field to lose focus.

### ISSUE THREAD

**Issue by jwmerrill** [elm-lang/core#3]
In [this example](http://share-elm.com/sprout/5462d666e4b00800031fe8d0), typing in the input field causes it to immediately lose focus.

The issue is apparently that whenever the number of elements in a flow changes, all the elements in the flow are re-rendered. Re-rendering an input causes it to lose focus.

Avoiding re-rendering input fields unnecessarily would mean this bug would manifest less often, but the robust solution is to make sure that re-rendering restores focus.

Some discussion and a work around for this particular case here:

https://groups.google.com/forum/#!topic/elm-discuss/RzGDnQKh5eg

**Comment by evancz** [comment]
Sorry this did not get attention til now! The `Graphics.*` modules now live in `evancz/elm-graphics` so I am trying to get stuff migrated over there. The input elements did not make the leap though, so the fix is to use HTML and SVG for this sort of stuff.
