### ISSUE TITLE
Maybe.andThen Documentation Is Not Valid

### ISSUE THREAD

**Issue by defndaines** [elm-lang/core#300]
The example code for `andThen` in the Maybe module is not valid. It assumes that `String.toInt` will return a `Maybe`, but it returns a `Result`.

Sorry, just learning, so I don't have a good working example to provide as a PR.

**Comment by jvoigtlaender** [comment]
Closing this, since there is now a PR which addresses this: https://github.com/elm-lang/core/pull/328.
