### ISSUE TITLE
Add Mouse.up & Mouse.down

### ISSUE THREAD

**Issue by jinjor** [elm-lang/core#308]
I am trying to render selection rectangle that starts by mousedown and ends by mouseup. The start position should be memorized when mouse state changes to `isDown == True`.

Currently we have to filter `Mouse.isDown`. I think better to provide two more functions below
```elm
Mouse.down : Signal ()
Mouse.up : Signal ()
```
and `Mouse.isDown` can be made by their combination.
```elm
isDown = merge (always True <~ down) (always False <~ up)
```
Does this implementation cause any trouble?

Thanks.

**Comment by evancz** [comment]
Seems plausible, adding to #322 for future consideration in a broader redesign of core.

**Comment by jinjor** [comment]
Thanks :)

**Comment by evancz** [comment]
No problem, thanks for raising the idea!
