### ISSUE TITLE
trimLeft and trimRight not defined in Internet Explorer

### ISSUE THREAD

**Issue by jvoigtlaender** [elm-lang/core#319]
It seems the latest IE (as well as earlier ones) does not support JavaScript's `trimLeft` and `trimRight` on strings (while it supports `trim`, at least the latest IE). As a consequence, Elm code using `String.trimLeft` and `String.trimRight` will fail on IE.

**Comment by jvoigtlaender** [comment]
Confirmed at [MSDN](https://msdn.microsoft.com/de-de/library/ecczf11c%28v=vs.94%29.aspx) that IE does not support `trimLeft` and `trimRight` on strings. Also found some other mentions online of these functions being "non-standard". So maybe avoid relying on them?

**Comment by TheSeamau5** [comment]
Yeah, Mozilla recommends against both `trimLeft` and `trimRight`.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/TrimLeft
