### ISSUE TITLE
Bool values cannot be the member of Set

### ISSUE THREAD

**Issue by jinjor** [elm-lang/core#329]
I'm facing a problem with making a Set that contains Bool values.
And also, lists or tuples that contains Bool cause the same trouble.

Here is the simple example and the error message.
```elm
set = Set.fromList [True]
```
```
The 1st argument to function `fromList` has an unexpected type.

4| set = Set.fromList [True]
Note: comparable types include Int, Float, Char, String, lists, and tuples.

As I infer the type of values flowing through your program, I see a conflict
between these two types:

    comparable

    Bool
```
I understand what the compiler is saying, but not sure why Set or Dict keys need to be `comparable`. Should they always be sorted?

I think the possible solutions are...
- Bool (or other union types) should be `comparable`
- there should be another type instead of `comparable`

Any ideas? Or is there any workaround?

Thanks.

**Comment by jvoigtlaender** [comment]
`Set` is implemented via `Dict`, and `Dict` is implemented via some sort of balanced trees, operations on which do in fact require a total order on entries/keys. So the implementation indeed requires `comparable` for types that should be put into a `Set` or used as key in a `Dict`.

So probably the right feature request here is that `Bool` should become `comparable`. Making all union types comparable would be more complicated, but special-casing for `Bool` could make sense.

**Comment by evancz** [comment]
Why do you want a set of booleans? Any case I can think of can also be handled just by booleans.

**Comment by jvoigtlaender** [comment]
Well, what about a set of tuples, some tuple component of which is a boolean? Certainly that's a valid use case that is not covered by just booleans alone?

**Comment by evancz** [comment]
Ah, I was just looking at the example given. Nested stuff makes sense. Let's hear @jinjor's specific case though.

**Comment by jinjor** [comment]
Yeah, exactly the case @jvoigtlaender said. (Sorry, the example above is not real one. )

Here is the specific case in my WebRTC app.
```elm
type alias Peer = Int
type alias MediaType = String
type alias Upstream = Bool
type alias Connection = (Peer, MediaType, Upstream)

type alias Model =
  {  connections : Set Connection
  ,  videoUrls : Dict Connection String

  ...

  }
```
Oh, now I found `MediaType` can also be written as an union type, like `type MediaType = Audio | Video`.

**Comment by evancz** [comment]
Okay, makes sense. I don't know what the short term solution is, but I made an aggregate issue at https://github.com/elm-lang/elm-compiler/issues/1008 so we can keep track of all the issues along these lines. Hopefully the different perspectives will help us come to a good answer.
