### ISSUE TITLE
Aggregating issues about Graphics.*

### ISSUE THREAD

**Issue by evancz** [elm-lang/core#332]
**Do not add issues or ideas as comments here. Open a separate issue for that.**

A bunch of issues and ideas have come in about `Graphics.*` over time and I'm trying to aggregate them all in one place.

**Issues:**

  * https://github.com/elm-lang/elm-compiler/issues/805 - bug with `email`
  * https://github.com/elm-lang/elm-compiler/issues/835, https://github.com/elm-lang/elm-compiler/issues/727 - events swallowed on `<input>` elements
  * https://github.com/elm-lang/elm-compiler/issues/800 - centering of `<input>` elements
  * https://github.com/elm-lang/elm-compiler/issues/867 - flow right inputs inside of flow down
  * https://github.com/elm-lang/elm-compiler/issues/890 - clicking `Html` in elements
  * https://github.com/elm-lang/elm-compiler/issues/775 - bug with `clickable`
  * https://github.com/elm-lang/elm-compiler/issues/773 - pixel mismatch
  * #334 - something weird with clicks

**API Ideas:**

  * https://github.com/elm-lang/elm-compiler/pull/601 - add `Graphics.Input.slider`
  * https://github.com/elm-lang/elm-compiler/issues/683 - quadratic curves in `collage`
  * https://github.com/elm-lang/elm-compiler/issues/680 - rounded corners somehow
  * https://github.com/elm-lang/elm-compiler/issues/533, https://github.com/elm-lang/core/pull/307 - get local mouse position
  * #419 - add `sprite` back

**Comment by mgold** [comment]
I'll add:
* New shapes in `Graphics.Collage`, most notably `arc`. Part of the problem is when an arc is `traced`, do you see just part of a circle, or does it go into the center like a slice of pie?

* Collision detection, either with [backbuffers](https://groups.google.com/d/msg/elm-discuss/Ee2_MfauicE/_635u_oJ4_UJ) or geometrically.
