### ISSUE TITLE
Proposal: Add Signal.foldp'

### ISSUE THREAD

**Issue by jvoigtlaender** [elm-lang/core#333]
The function which currently is in http://package.elm-lang.org/packages/Apanatshka/elm-signal-extra/5.3.0/Signal-Extra#foldp%27.

Discussions like [this](https://groups.google.com/forum/#!topic/elm-discuss/h-WAC3kgrOU) (and others) on the mailing list show that this would be worthwhile.

**Comment by evancz** [comment]
[The plan](https://github.com/elm-lang/core/blob/master/CONTRIBUTING.md#adding-new-functions) is to look through all the `*-extra` packages and incorporate things that have been useful in general.

I think an issue like this is going to get lost in the shuffle, and you and I will not forget it either way. So let's revisit it when we are going through `*-extra` packages.

**Comment by evancz** [comment]
For additional context, I am trying to close issues more aggressively. This means "it's a good idea but we need to come back to it later" means we close it for now. The clear resolution is "we will come back to it later". That's the theory at least! Otherwise it seems that issues will pile up forever.

**Comment by jvoigtlaender** [comment]
Sure, I just thought that with the new "meta-issue" https://github.com/elm-lang/core/issues/322 it might make sense to bring this up directly in the repo. But the other strategy is fine as well, of course. So maybe add to https://github.com/elm-lang/core/issues/322 that there is an understanding that `*-extra` packages are also implicitly included in those considerations?
