### ISSUE TITLE
String.toFloat "." yields Ok NaN

### ISSUE THREAD

**Issue by Pisys** [elm-lang/core#336]
The Result of String.toFloat "." yields Ok Nan instead of Err "..."
Probably a bug?

**Comment by evancz** [comment]
Yeah, that's pretty freaky!

If you are interested, seems like a nice bug to check out and turn into a PR!

**Comment by jvoigtlaender** [comment]
There are two pull requests addressing this issue: #342 and #343. I suggest to close the ticket here and select one of the two PRs (probably #342, which appears to be more encompassing).
