### ISSUE TITLE
Json.Decoder.int Bug / Ints in Elm

### ISSUE THREAD

**Issue by agrafix** [elm-lang/core#337]
The javascript spec allows numbers up to 2^53-1 (`9007199254740991`) and Elm generally is fine with these large integers, too. The json decoder fails for inputs larger than `2147483647`. 

I've found the error in the Native.Json part:
https://github.com/elm-lang/core/blob/2a8dcb522f71541c299a8a465bb39bc17bb9ec67/src/Native/Json.js#L53

It checks that `(value|0) === value`, but this check will fail for any input larger than `2147483647` because binary operators only work on 32bit ints.

I did not send a pull request (yet?) because I'm not sure what the correct step is. The Bitwise module allows parameters of type `Int`, and this will produce broken results iff the number is larger. Should elm distinguish between `Int` (32 Bit) and `LargeInt` (53 Bit)? Or should we just fix the json parser?

**Comment by evancz** [comment]
PR #153 was open with a potential fix, but we closed it so @ajhager or @krisajenkins could do a PR with the faster version of the fix.

**Comment by ajhager** [comment]
And the new PR is on its way. :)

**Comment by agrafix** [comment]
Very cool, looking forward to it! :-) @ajhager

**Comment by agrafix** [comment]
@evancz what do you think about the behavior of the bitwise module? maybe there should at lease be a warning that is only works for 32 Bits Ints?

**Comment by jvoigtlaender** [comment]
Is this completely addressed by #352 (which was merged)? If so, please close the issue. If not, please say what is not addressed.

**Comment by evancz** [comment]
Not sure what happened here, so I am going to close. Someone please reopen with fresh information if something else needs to happen.
