### ISSUE TITLE
Flipping arguments in foldl's step function

### ISSUE THREAD

**Issue by sindikat** [elm-lang/core#340]
Elm's [`foldr`](http://package.elm-lang.org/packages/elm-lang/core/2.1.0/List#foldr) has the same type as Haskell's [`foldr`](http://hackage.haskell.org/package/base-4.8.1.0/docs/Prelude.html#v:foldr):

    foldr : (a -> b -> b) -> b -> List a -> b -- Elm
    foldr :: (a -> b -> b) -> b -> t a -> b  -- Haskell

However Elm's [`foldl`](http://package.elm-lang.org/packages/elm-lang/core/2.1.0/List#foldl) has a different type, than Haskell's [`foldl`](http://hackage.haskell.org/package/base-4.8.1.0/docs/Prelude.html#v:foldl):

    foldl : (a -> b -> b) -> b -> List a -> b -- Elm
    foldl :: (b -> a -> b) -> b -> t a -> b  -- Haskell

Changing type of `foldl` in Elm is API-breaking, but it makes sense. When you fold a list from left, your step function looks like `(\acc e -> ...)` — the accumulator is to the left of the current element, because the accumulator is to the left of the list itself. This is a good visual intuition. Also there is no reason to arbitrarily deviate from Haskell, if it doesn't benefit Elm (or there are benefits that I don't know about?).

Can we consider that? If no, can we maybe add the note to documentation to avoid confusion?

**Comment by evancz** [comment]
The reasoning is [here](http://package.elm-lang.org/help/design-guidelines#the-data-structure-is-always-the-last-argument) and matches how things work [in Standard ML](http://sml-family.org/Basis/list.html) which I find the clearest and nicest of the ML family languages.

I get why Haskell did it that way, but in practice I find it super annoying. I also am not targeting Haskell programmers primarily. I trust that they'll be able to sort out any minor differences (like colon vs double colon) and I can do what's right for the broader Elm community which will primarily be made up of folks coming from JS and ruby and python and such.

There are probably discussions on elm-discuss going into more detail about why things are this way, so def check that out for more information!

**Comment by sindikat** [comment]
Thank you Evan for the response. This topic was discussed on mailing list:

- https://groups.google.com/d/topic/elm-discuss/ehsV6-YveFA/discussion
- https://groups.google.com/d/topic/elm-discuss/8LXnaqtbBL8/discussion
