### ISSUE TITLE
Uncaught ReferenceError: redo is not defined

### ISSUE THREAD

**Issue by pdamoc** [elm-lang/core#347]
The `textured` Form throws this error. 

This fails without producing an error in the visual output. 
For an example of this please access: 
http://elm-lang.org/examples/texture

**Comment by jvoigtlaender** [comment]
That's already been [reported](https://github.com/elm-lang/core/issues/230) and [fixed](https://github.com/elm-lang/core/pull/274).

The next release of `core` should have the fix.

**Comment by jvoigtlaender** [comment]
Close as a duplicate?

**Comment by pdamoc** [comment]
Thank you!
