### ISSUE TITLE
Initial value of Keyboard.presses is shown as <internal structure>

### ISSUE THREAD

**Issue by grzegorzbalcerek** [elm-lang/core#362]
Consider the following program:

    module KeyboardSignals2 where

    import Graphics.Element exposing (show)
    import Keyboard
    import Signal exposing ((<~))

    main = show <~ Keyboard.presses

It shows:

     <internal structure>

initially. Only after pressing a key, it shows its code. But, shouldn't a signal always have a value consistent with its data type?

**Comment by jvoigtlaender** [comment]
Fixed by https://github.com/elm-lang/core/pull/363.

But note that by using `Keyboard.presses` you are in for further trouble: https://github.com/elm-lang/core/issues/326
