### ISSUE TITLE
[Proposition] Array.get, Array.set support negative indices (element from end)

### ISSUE THREAD

**Issue by sindikat** [elm-lang/core#366]
In Python negative list index allows to get or set element from end of the list:

    >>> xs = range(0,5)
    >>> xs[-1]
    4
    >>> xs[-1] = 10
    >>> xs
    [0, 1, 2, 3, 10]

JavaScript, though, [doesn't support negative indexes](http://stackoverflow.com/q/13618571/596361) for its Arrays.

I think it makes sense to make Array support negative indexes, after all Array.slice supports them, and Arrays have different semantics from Lists (which are supposed to be traversed once from beginning to end, not sliced constantly). It makes even more sense in 2D games, where you have `Matrix a` as alias for `Array (Array a)`, so you constantly need to slice a rectangular piece from a huge Matrix and then transform it using your `view` function to present on screen.

**Comment by evancz** [comment]
Seems reasonable, adding to meta issue #322

If you want it in the meantime, do [this](https://github.com/elm-lang/core/blob/master/CONTRIBUTING.md#adding-new-functions).

**Comment by Mouvedia** [comment]
broken link: https://github.com/elm/core/blob/master/.github/CONTRIBUTING.md#adding-new-functions
