### ISSUE TITLE
Mapping over task sent out of port causes runtime error

### ISSUE THREAD

**Issue by mgold** [elm-lang/core#368]
This program
```elm
import Task exposing (Task)

port one : Task Int Int
port one = Task.succeed 3

port two : Task Int Int
port two = Task.map identity one
```
crashes with the message
```
Cannot read property 'tag' of undefined

Open the developer console for more details.
```
The problem appears if you (1) have a task sent out a port (2) which is mapped over by another task (3) which is itself sent out a port. If you remove the `port` keyword from _either_ definition (on both lines), the error disappears.

The workaround is to only send the final task out a port, and this makes a lot of sense. It would be fairly easy to put a better runtime error into place. However, it's not obvious how to catch this at compile time.

**Comment by theor** [comment]
same problem here - a nicer error message at runtime, or even better, at compilation time would be better.
