### ISSUE TITLE
Documentation for Graphics.Collage.move implies (y,x) rather than (x,y)

### ISSUE THREAD

**Issue by eeue56** [elm-lang/core#370]
From [here](https://github.com/elm-lang/core/blob/2.1.0/src/Graphics/Collage.elm#L220)

>`(move (10,10) form)` would move `form` ten pixels up and ten pixels to the
right.

when in actuality the code is right first, then up.

```
move : (Float,Float) -> Form -> Form
move (x,y) f =
  { f | x <- f.x + x, y <- f.y + y }
```

**Comment by evancz** [comment]
Good point, hadn't thought to be parallel with it. Can you do a PR swapping the order of up and right in the docs?

**Comment by eeue56** [comment]
Yup - just done in #371.
