### ISSUE TITLE
millisecond docs imply a "milliseconds" variable exists

### ISSUE THREAD

**Issue by eeue56** [elm-lang/core#373]
Had one of my students confused by this line

>Units of time, making it easier to specify things like a half-second (500 * milliseconds) without remembering Elm’s underlying units of time.

in the [docs for time](http://package.elm-lang.org/packages/elm-lang/core/2.1.0/Time#millisecond) due to the fact it says `500 * milliseconds` and not `500 *millisecond` or `500 milliseconds`.

I think something along the lines of

> Units of time, making it easier to specify a time without remembering Elm’s underlying implementation of time.
> `halfSecond = 500 * millisecond` would create a variable with the value of 500ms, or half a second.

Might make it a little more clear?

**Comment by jvoigtlaender** [comment]
Closed via https://github.com/elm-lang/core/pull/376.
