### ISSUE TITLE
Avoid "notify called synchronously" when port callbacks throw

### ISSUE THREAD

**Issue by rtfeldman** [elm-lang/core#374]
See https://github.com/evancz/error-message-catalog/issues/31 for original discussion.

This code is a workaround for end users until `core` has a fix:

```javascript
function safeSubscribe(ports, name, callback) {
    ports[name].subscribe(function(value) {
        try {
            callback(value);
        } catch(e) {
            setTimeout(function() {
                // rethrow things how you want, mention 'name' so you know who caused it
            }, 0);
        }
    });
}
```

Per @evancz, should be a tiny fix [here](https://github.com/elm-lang/core/blob/2df1163d35841459f51c4176d0ad5631901b2583/src/Native/Port.js#L91-L94).

**Comment by evancz** [comment]
`notify` does not exist anymore, so this cannot be a thing anymore. (I'm pretty sure!)
