### ISSUE TITLE
Regex, runtime error

### ISSUE THREAD

**Issue by gunpinyo** [elm-lang/core#378]
In core package, module Regex
```elm
regex : String -> Regex
```

This function can produce runtime error if string contain invalid pattern.

Here is an example form elm-repl
```
b = Regex.regex("[a-z")
SyntaxError: Invalid regular expression: /[a-z/: Unterminated character class
```

It would be better if we change regex to be
```elm
regex : String -> Maybe Regex
```
it will return `Nothing` if string contains invalid pattern.

**Comment by eeue56** [comment]
I think it makes sense for regex to be `regex : String -> Result Regex` here, so that the error message is captured. If it's okay, I'll make a pull request for this so that it can be merged if it's approved

**Comment by mgold** [comment]
Yeah, it's either that or keep the runtime error. Most regexes won't be generated dynamically (in signals or functions), so there's a case for keeping the runtime error since it will be easier to work with the absence of a Result or Maybe. (We seem to be getting useful error messages, so I support a Result in the API.)

**Comment by rtfeldman** [comment]
In the spirit of [these guidelines](https://github.com/elm-lang/elm-plans/blob/master/CONTRIBUTING.md) I've made [a gist](https://gist.github.com/rtfeldman/a3614e123381e7751b4c) for a potentially interesting solution to this. Any discussion of that idea is welcome over on the gist itself, but let's not derail this issue with that stuff. :smile:

**Comment by jvoigtlaender** [comment]
Is this "the same" as https://github.com/elm-lang/core/issues/157? Should we close that other issue, then?

**Comment by eeue56** [comment]
I've created #380  that will change `regex` to return a `Result` instead, but I think it needs further discussion before merging. Having to use `case..of` everywhere doesn't quite fit right. 

Perhaps leaving `regex` as it's own function and introducing `safeRegex : String -> Result String Regex` might be a better solution, with `regex` intended for static expressions and `safeRegex` for dynamic ones. 

This would remove the need to introduce a new syntax as per rtfeldman's gist, though leave a runtime error possible.

**Comment by drbo** [comment]
Regex literals might be a solution.  That way invalid regexps are a compile time error

**Comment by mgold** [comment]
That's been brought up before, and I agree would be a good solution. But it involves a compiler change.

**Comment by tmcw** [comment]
For my (admittedly rare) usecase, I'm creating regular expressions based on user input, in order to filter a list and extract results with matching groups - so unfortunately a literal syntax _only_ would make that usecase more difficult - right now I'm porting from a JavaScript version which uses `new RegExp(variable)` in order to create regular expressions on the fly.

Returning a `Maybe Regex` would fit my usage perfectly, though I understand if that's not the most common way people interact with regular expressions.

**Comment by seanhess** [comment]
We just ran in to this issue as well. Is anyone working on it?

**Comment by mgold** [comment]
I'm not aware of any recent activity. I stand by my Dec 19 comment.

**Comment by seanhess** [comment]
You're saying it's not possible to change the signature to Maybe Regex because we give the string straight to JavaScript? supporting a constructor which returns Maybe or Result would require jumping all the way to literals?

**Comment by seanhess** [comment]
By the way my use case doesn't involve literals at all: we want to allow the user to type Regex expressions into a search box. Currently this works, but if they begin typing "a[bc" the program crashes and filtering stops working (even after the user fixes the Regex)

**Comment by jvoigtlaender** [comment]
@seanhess, when asking "is anyone working on this", does #380 fit your bill?

**Comment by seanhess** [comment]
Yes 380 is exactly what I need!

**Comment by jvoigtlaender** [comment]
So the thing you want does not need work, it needs merging/release, over at #380.

**Comment by seanhess** [comment]
Yes exactly, just merging. Releasing #380 would completely resolve my
issue.

**Comment by evancz** [comment]
Consolidated regex stuff in #722. Follow along there!

**Comment by evancz** [comment]
The plan is to move regular expressions to `elm-lang/regexp` or something, and it will have something like this:

```elm
fromString : String -> Result String RegExp
```

As seen here: https://github.com/evancz/regexp/blob/master/src/RegExp.elm#L44
