### ISSUE TITLE
Suggestion: Change the type of (%) to number -> number -> number

### ISSUE THREAD

**Issue by imeckler** [elm-lang/core#4]
Is there a compelling reason for (%) to have the current restricted type `Int -> Int -> Int`? Javascript (%) works as expected for non-integers and I often actually need this operation.

**Comment by imeckler** [comment]
In response to evancz's [comment](https://github.com/elm-lang/package.elm-lang.org/issues/12#issuecomment-70642996), I don't know about Haskell or SML, but in OCaml the function I have in mind is called `mod_float`.

**Comment by imeckler** [comment]
If you need such a function, here's an elm implementation in the meantime.
```elm
modFloat : Float -> Float -> Float
modFloat x m = x - m * toFloat (floor (x/m))
```

**Comment by evancz** [comment]
I have reservations about using the `number` type too aggressively, so I'd currently be more comfortable with a separate function. I'm used to seeing it called `fmod` in [places like C++](http://www.cplusplus.com/reference/cmath/fmod/). How this is handled in Java and C# and F#?

**Comment by mus0u** [comment]
I would also love to see an fmod function added.

**Comment by alexiamcdonald** [comment]
I've made [a library for this one function](https://github.com/alexiamcdonald/elm-math-extra)! It uses the native `(%)` operator though, so it would have to have a module review. Do you think it is worth it for a one-function package, or can we get this in the standard library? 😛

**Comment by JoshuaOSHickman** [comment]
Found myself needing this function. Not hard to write, but I was mostly just surprised there wasn't something in Basic for it.

**Comment by evancz** [comment]
Consolidated all the math related stuff into the #721 meta issue. Follow along there!

**Comment by jvoigtlaender** [comment]
A version of this function is now in http://package.elm-lang.org/packages/elm-community/basics-extra/2.3.0/Basics-Extra#fmod (by request https://github.com/elm-community/basics-extra/issues/10).
