### ISSUE TITLE
Touchend not called when element re-renders during a click

### ISSUE THREAD

**Issue by eeue56** [elm-lang/core#401]
When touching an element that re-renders itself before you stop touching (i.e trigger touchend), then touchend is never called, meaning until you click again the signal will be stuck with the data from the click start.

To try this, load the [example project](https://github.com/endeavour/Elm-Touch-Bug-Repro) up in Chrome, open the dev tools and enable mobile view, with stimulated touch events, and click on the [] in the webpage.

**Comment by evancz** [comment]
Not sure if this makes sense in 0.17. No more Touch in core.
