### ISSUE TITLE
Proposal: add Dict.intersectBoth

### ISSUE THREAD

**Issue by mgold** [elm-lang/core#402]
I recently found myself writing this code:
```elm
let commonKeys = Dict.intersect dict1 dict2 |> Dict.keys
    unsafeGet k d = Dict.get k d |> (\(Just x) -> x)
in List.map (\k -> (unsafeGet k dict1, unsafeGet k dict2)) commonKeys
```
This requires the unsafe `(\(Just x) -> x)` operation, even though I *know* it's safe because I'm only looking at keys in the intersection. Although, I was using the union at first, and that blew up in a runtime error, so this is a real runtime error that we can avoid by offering this API in `Dict`:

```elm
intersectBoth : Dict comparable v -> Dict.comparable w -> Dict.comparable (v,w)
```
The current `intersect` function keeps only the values from the first dictionary, even though we know they're also in the second one (because it's the intersection). It's pretty useless in my case:
```elm
intersect : Dict comparable v -> Dict comparable v -> Dict comparable v
```
 A more extreme change would be to replace it with the function I've called `intersectBoth`, since you can get back the old behavior with `Dict.map (always fst)`. But if you don't want to do that, adding another function shouldn't be too bad. Because the representation of dictionaries is opaque, this can't be done in a third party library.

**Comment by evancz** [comment]
I am a fan. I'd want it to be something like this:

```elm
intersectWith : (a -> b -> c) -> Dict comparable a -> Dict comparable b -> Dict comparable c
```

So you could do `intersect = intersectWith always` and `intersectBoth = intersectWith (,)`. I'm not certain about switching the meaning of `intersect` but I'm doing some core stuff now, so I'll think about this more.

**Comment by mgold** [comment]
I can live with `intersectWith`. Thanks.

**Comment by mgold** [comment]
I don't think the commit referenced above was ever released, but it's covered by `Dict.merge` in 4.0.1.
