### ISSUE TITLE
Dreamwriter: Failed to execute 'requestFullScreen' on 'Element': API can only be initiated by a user gesture.

### ISSUE THREAD

**Issue by NigelThorne** [elm-lang/core#407]
"Failed to execute 'requestFullScreen' on 'Element': API can only be initiated by a user gesture." occures when you try to fullscreen the document. 

I'm using Chrome on Ubuntu.

**Comment by evancz** [comment]
When describing a potential bug, it is important to provide a minimal reproduction. In this case, are you reporting an issue with https://github.com/rtfeldman/dreamwriter ? Why not open the issue there? Is there an issue open about this already?
