### ISSUE TITLE
Keyboard.meta should be renamed to Keyboard.super

### ISSUE THREAD

**Issue by anicholson** [elm-lang/core#414]
The documentation for `Keyboard.meta` [states that][1]

```
{-| The meta key is the Windows key on Windows and the Command key on Mac.
-}
```

That doesn't match the usage I've seen. In my experience, Meta has referred to "Alt" on Windows/Linux and "Option" on Mac, whereas the "Windows"/"Command" key has always been referred to as "Super". 

[1]: https://github.com/elm-lang/core/blob/master/src/Keyboard.elm#L170

**Comment by anicholson** [comment]
See also: http://askubuntu.com/a/19565

**Comment by jvoigtlaender** [comment]
In contrast, see https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/metaKey. This is how it is in Browser/JavaScript land. Elm is not going to change that. So the behavior and documentation of `Keyboard.meta` is exactly as web devs will expect. `Keyboard.super` would be an alien concept to them.

**Comment by evancz** [comment]
@jvoigtlaender is exactly right about why it is named that way. I think it makes sense to stick with the browser versions of the terminology.

**Comment by anicholson** [comment]
0_o well there you go. TIL. Thanks for the explanation, @jvoigtlaender , and @evancz  for a cool language :)
