### ISSUE TITLE
Please add `apply` and `pure` to Json.Decode

### ISSUE THREAD

**Issue by jasonzoladz** [elm-lang/core#416]
It would be nice to have `pure` and `apply` defined in Json.Decode, as it seems way more natural than `object6`.  (And it saves the boilerplate of defining them every time.)

I assume (perhaps wrongly?) that they have not been included due to accessibility concerns.  (Obviously, you need not discuss Applicatives.)  Since the language supports partial application and ADTs, isn't the pedagogy simply:

"`pure` takes a function/value and puts it a box.  `apply` takes a function in a box, and a value in a box, and returns a value in a box."  What am I missing?

**Comment by evancz** [comment]
The equivalent of `pure` already exists and is called [`succeed`](http://package.elm-lang.org/packages/elm-lang/core/2.1.0/Json-Decode#succeed). I felt that the name `pure` actively misleads people about what is happening.

Adding the equivalent of `apply` is planned. In the meantime, [these are the guidelines](https://github.com/elm-lang/core/blob/master/CONTRIBUTING.md#adding-new-functions) for adding stuff like this and I suspect there's already a `*-extras` package out there that has it.

Furthermore, it should be pretty easy to define in terms of `andThen`.

```elm
andMap : Decoder (a -> b) -> Decoder a -> Decoder b
andMap decodeFunc decodeValue =
    decodeFunc `andThen` \func -> decodeVaue `andThen` \value -> succeed (func value)
```

**Comment by jasonzoladz** [comment]
I know that it's easily defined:
`apply =  object2 (<|)`

My point was that it's a foundational primitive that is trivial to add to the library.

**Comment by evancz** [comment]
> Adding the equivalent of `apply` is planned. In the meantime...

It is very hard to respond to the volume of API suggestions for core in a piecemeal way. This is planned. It wasn't in the first version, but many folks have wanted it since then. So it's in the plan to add it.

**Comment by jasonzoladz** [comment]
Thanks Evan.  I appreciate the reply.
