### ISSUE TITLE
Array.indexedMap stops at 1024

### ISSUE THREAD

**Issue by simonh1000** [elm-lang/core#426]
Try this in repl: 
`Array.indexedMap (\idx v -> idx) <| Array.fromList [0..1030]`

results in `... 1021,1022,1023,0,1,2,3,4,5,6]`

List.indexedMap seems to be OK

**Comment by jvoigtlaender** [comment]
Isn't that the same as https://github.com/elm-lang/elm-lang.org/issues/262 and https://github.com/elm-lang/core/issues/271, which was fixed in https://github.com/elm-lang/core/pull/391 (but hasn't yet been released as part of a new `core` version)?
