### ISSUE TITLE
How to teardown a module instantiated with `Elm.embed`

### ISSUE THREAD

**Issue by TehShrike** [elm-lang/core#432]
I couldn't find anything in the documentation or source code.

When I need to remove a component, how am I supposed to stop it?

I don't want to have to delete the element, just clear it.

Would deleting the element from the DOM even get the job done?  Would the garbage collector be able to clean up the Elm code?

**Comment by danneu** [comment]
Looks like `fullscreen` and `embed` return an object with three methods, one of them being `.dispose()`.

Source: [elm-core/Native/Runtime.js#L171-L175](https://github.com/elm-lang/core/blob/218bf6b28c9be53f7303a10a1580e25955d44978/src/Native/Runtime.js#L171-L175)

```
function dispose() {
  removeListeners(listeners);
  inputs = [];
}
```

**Comment by TehShrike** [comment]
This looks like what I was hoping for!  I'll leave this open in case some other contributor wants to confirm, but I'll give `dispose` a try.
