### ISSUE TITLE
Why not allow calling `embed` with non-DIV elements?

### ISSUE THREAD

**Issue by TehShrike** [elm-lang/core#433]
I would like to embed a module on a non-div element.

Right now, that throws an error: https://github.com/elm-lang/core/blob/master/src/Native/Runtime.js?ts=3#L23

What are the reasons for this?  I'm guessing that Elm expects the element to have `display: block` - if so, why not just require that, or even add that style manually?

**Comment by ethagnawl** [comment]
I'd like to +1 @TehShrike's comment. The `div` requirement _seems_ rather arbitrary.

In my use-case, I'm mounting an Elm app into an existing page which is broken up into `section`s and would like to mount my app directly into its designated `section`, without having to insert a nested placeholder `div`.

**Comment by evancz** [comment]
I don't think it's true anymore. Not sure. Reopen with a SSCCE for 0.17 if it is. Also some motivation for why you want to make a change.
