### ISSUE TITLE
Linear gradient: Incorrect values give javascript runtime error.

### ISSUE THREAD

**Issue by ggVGc** [elm-lang/core#434]
If calling `linear` as such `linear (a,b) (c,d) [(0,white), (2, black)]`, which is obviously incorrect, it results in a runtime error in the javascript output, and nothing being shown or printed on screen. I suggest a crash instead with an indication that the values need to be in the interval [0,1], or some way of preventing a runtime error here, although that seems a bit difficult.

**Comment by evancz** [comment]
Sorry for such a slow response, been very focused on Elm 0.17 stuff. The `Graphics.*` modules have moved to `evancz/elm-graphics` so it makes sense to move this over there. I think this will also make it less likely that issues get lost in the shuffle.

**Comment by jvoigtlaender** [comment]
For anyone encountering this: This now lives as a newly opened issue at https://github.com/evancz/elm-graphics/issues/14, with an SSCCE.
