### ISSUE TITLE
Bug gives error "newProps is not defined"

### ISSUE THREAD

**Issue by sanichi** [elm-lang/core#437]
I think the variable names `props` and `newProps` should be the same in lines 456 and 460 of the function `clickable` in `core/src/Native/Graphics/Input.js`:

```
		var element = wrappedElement._0;
		var props = Utils.update(element.props, { click: onClick });
		return {
			ctor: wrappedElement.ctor,
			_0: {
				props: newProps,
				element: element.element
			}
		};
```

Comparing with the function before that one (`hoverable`) it looks like there's a typo on line 456, and it possibly was meant to be:

```
var newProps = Utils.update(element.props, { click: onClick });
```

**Comment by jvoigtlaender** [comment]
@evancz, is this another case of `props` changes needed, like in the last minute changes earlier today?

**Comment by evancz** [comment]
Should be fixed now. Clear out `elm-stuff/` and try again.

**Comment by sanichi** [comment]
Thanks a million!
