### ISSUE TITLE
"up.props not defined" error in elm reactor 0.16

### ISSUE THREAD

**Issue by fredcy** [elm-lang/core#438]
The customButton native code tries to access `up.props.width` but `up.props` is not defined. Looks like an intermediate `_0` object was introduced between `up` and the `props` property.

**Comment by fredcy** [comment]
@evancz This problem manifests when running elm reactor in 0.16 but looks to me to be a significant problem in core/src/Native/Graphics. Some recent change added a wrapper layer in Element named `_0` but there is still code around expecting to access properties like `props` directly from the element. Case in point is the `customButton` function mentioned above.

**Comment by jvoigtlaender** [comment]
Is this still relevant or was it fixed by https://github.com/elm-lang/core/commit/09f3dd2b11f34987bf6b32201fd1899baff5d646?

**Comment by fredcy** [comment]
It was fixed by the latter. I'm closing this now.
