### ISSUE TITLE
Http.send behavior

### ISSUE THREAD

**Issue by smiley325** [elm-lang/core#44]
From the mailing list:

Right now, the way Http.send works, the Waiting state only occurs for the first request. If the URL changes thereafter, it will maintain the previous Response until the new response comes in. I can see why that would be a useful behavior to have, especially if you hook up your output/views directly to the response signal.

In more stateful applications however, it would be useful to have a different Http.send (not sure what I would name it) which, when the URL changes, will revert to the Waiting state while waiting for the new response to come in. This would allow someone to have a loading animation be displayed whenever requests to the server are happening, so the user is aware that something is being waited on. In this style, if the programmer wants to display the old results while the new results are fetching, he can do that by storing results in his/her application state.

Jeff Smits added that under this new behavior, "you can do a dropIf ((==) Waiting) Waiting to get the old heaviour back." Whereas you cannot derive this new behavior from the old behavior.

Just wanted to put this suggestion out there for the next revision of Http. The change itself is just a single line swap in Native/Http.js

**Comment by evancz** [comment]
This stuff lives in `evancz/elm-http` now.
