### ISSUE TITLE
Date.fromTime 1422777600000 returns {} in elm-repl

### ISSUE THREAD

**Issue by berndca** [elm-lang/core#441]
I expected 

  Date.fromTime 1422777600000 

to return 

  // new Date(1422777600000.0)
  Sun Feb 01 2015 00:00:00 GMT-0800 (PST)

However I got {} : Date.Date

I'm  using elm-repl 0.16. Am I missing something?
Thanks, Bernd

**Comment by rgrempel** [comment]
I think the issue you are seeing is that `toString` doesn't produce what you might expect from a `Date`.

For instance, here's an elm-repl session:

```elm
> import Date
> date = Date.fromTime 1422777600000
{} : Date.Date
> toString date
"{}" : String
> Date.year date
2015 : Int
> Date.month date
Feb : Date.Month
> Date.day date
1 : Int
```

So, you can see that elm-repl really has created a date, and you really can use it in functions. However, `toString` just doesn't produce what you might expect.

**Comment by berndca** [comment]
Thanks for the clarification! I guess the toString issue might be related to the fact that a native function call is used. Are there any plans to adjust the output of toString or perhaps to at least output a message indicating the limitation?

Thanks, Bernd

**Comment by rgrempel** [comment]
I've submitted a PR -- see #442

**Comment by jvoigtlaender** [comment]
Since there is a pull request addressing this issue, I am closing the issue itself.
