### ISSUE TITLE
Feature request: Graphics.Collage.RotateTo

### ISSUE THREAD

**Issue by MaciekChudek** [elm-lang/core#443]
Currently rotate takes an offset. But often you know what absolute direction you want something pointing now and don't care about the direction it was pointing before, let alone the angular difference between them. Consequently, something like this would be useful:

rotateTo : Float -> Form -> Form
rotateTo t (Form_elm_builtin f) =
  Form_elm_builtin { f | theta = t }

**Comment by evancz** [comment]
Sorry for a very slow response! All the `Graphics.*` modules now live in `evancz/elm-graphics` so this kind of stuff should be moved there.

Nonetheless, I don't think it's likely this would be added.
