### ISSUE TITLE
Array.append causes runtime error on largish arrays

### ISSUE THREAD

**Issue by klaftertief** [elm-lang/core#444]
I know there are already some similar Array issues, but I hope to offer a better test case for this specific issue. This is extracted from issues working on a polyline simplification library, for this issue mainly https://github.com/klaftertief/elm-simplify/blob/tail-recursive-array/src/Simplify/RadialDistance.elm.

I applied the open pull requests #396 and #399, but they didn't help.

This test cases crashes in [`subLengths += a.table[i].table.length`](https://github.com/elm-lang/core/blob/820e9e9aae29381b635cdc2b45d2b11b284c93b4/src/Native/Array.js#L661) (`table` is undefined) starting at a length of `32^2 - 1*32 + 1`.

```
import Array exposing (append, initialize)
import Graphics.Element exposing (show)

main =
  show <|
    append
      (initialize 1 (always 1))
      (initialize (32^2 - 1*32 + 1) (\i -> i))
```

It's extracted from this recursive function (which is similar to the one in the linked repo). An interesting thing is that this starts crashing at a length of `32^2 - 2*32 + 1`.

```
import Array exposing (append, empty, get, initialize, length, slice)
import Graphics.Element exposing (show)

run accum array =
  let
    head = get 0 array
    tail = slice 1 (length array) array
  in
    case head of
      Nothing -> accum
      Just x ->
        run
          (append (initialize 1 (always x)) accum)
          tail

main =
  show <|
    run
      empty
      (initialize (32^2 - 2*32 + 1) (\i -> i))
```

**Comment by eeue56** [comment]
I spent a while looking at this problem with @klaftertief and sadly was unable to figure out a solid solution.  I'm glad you made it an issue! When I get some time I'll look more into this.

**Comment by klaftertief** [comment]
Thanks @eeue56 for your efforts.

[This commit](https://github.com/klaftertief/core/commit/724ce5c7458befa7e2cbbcb8df40aff2eef93db2) fixes the symptoms of this specific issue, see [this test](https://github.com/klaftertief/core/commit/ccbf20c3bb49e98f0decd9e6be9260fbcd49aa86).

There are more Array related bugs/crashes popping up in other test cases, but it's hard to find minimal test cases to have a solid foundation to fix those. I hope I'll find some time to add more minimal failing tests and maybe get a better understanding of the native implementation.

**Comment by dan-tull** [comment]
I hit this issue today, though for me the Array.append call that is failing is for arrays of length 963 + 1 and 960 + 2 (a slightly lower bound than the 993 in the example above).

If it would be useful, I could extract minimal test case for the bug in my scenario.

**Comment by eeue56** [comment]
We're working on it

**Comment by evancz** [comment]
Closing in favor of #649 which will track all array issues and progress on a new implementation.
