### ISSUE TITLE
error with Elm 0.16

### ISSUE THREAD

**Issue by igregson** [elm-lang/core#449]
After upgrading to Elm 0.16, I get the following error when running `elm-package bump`: 

```
Error: failure when running: elm-make --yes --docs=elm-stuff/documentation.json
Problem in dependency elm-lang/core 2.1.0

The elm-package.json constraints of 'elm-lang/core' are probably
letting too much stuff through. Definitely open an issue on the relevant github
repo to get this fixed and save other people from this pain.

In the meantime, take a look through the direct dependencies of the broken
package and see if any of them have had releases recently. If you find the new
thing that is causing problems, you can artificially constrain things by adding
some extra constraints to your elm-package.json as a stopgap measure.


Detected errors in 1 module.
```

When trying to update a package manually, such as by running `elm-package update evancz/elm-html`, I get this: 

```
Error: Unable to find a set of packages that will work with your constraints.
```

The problem seems to be related to Elm Core, which is why I'm reporting it here (as instructed in the fabulous error message). However, I'm new to elm so could be missing something completely obvious. 

Grateful for any suggestions.

**Comment by jvoigtlaender** [comment]
My suggestions would be:

First, remove the complete `elm-stuff` subdirectory.

Then, do either of the following two:
* Remove the `elm-package.json` file and do fresh `elm-package install` calls for all the packages you depend on.
* Go through the `elm-package.json` file and update bounds so that they match these:
```json
{
    "dependencies": {
        "elm-lang/core": "3.0.0 <= v < 4.0.0",
        "evancz/elm-effects": "2.0.1 <= v < 3.0.0",
        "evancz/elm-html": "4.0.2 <= v < 5.0.0",
        "evancz/elm-http": "3.0.0 <= v < 4.0.0",
        "evancz/elm-markdown": "2.0.0 <= v < 3.0.0",
        "evancz/elm-svg": "2.0.1 <= v < 3.0.0",
        "evancz/start-app": "2.0.2 <= v < 3.0.0"
    },
}
```

**Comment by igregson** [comment]
Thanks @jvoigtlaender, did the trick :)
