### ISSUE TITLE
Time.every should behave appropriately when the computer goes to sleep

### ISSUE THREAD

**Issue by avh4** [elm-lang/core#452]
I have a dashboard where some data is updated every hour with `Time.every Time.hour`.  If the computer goes to sleep shortly after the signal fires, and then is woken more than an hour later, I would expect the signal to fire immediately upon the page being woken, but in this case, the signal will not fire for almost another hour.

**Comment by evancz** [comment]
Hmm, I guess this is till true. Is there a way to solve this in JS?

**Comment by avh4** [comment]
`setTimeout` and `setInterval` both should fire after the computer wakes if the firing is overdue.  Not sure what is going on here, but will debug it more the next time I run into it.
