### ISSUE TITLE
typeerror (undefined) in touch 'end' function

### ISSUE THREAD

**Issue by bburdette** [elm-lang/core#461]
I've got a project where I have a bunch of SVG controls, which respond to either touch or mouse input.  If I use the touch signal (passing it in to the startapp 'inputs') then I get an error after randomly clicking around among the controls.  This is using the mouse on my laptop, which isn't a touch device.  

The error occurs in the 'end()' function, which is inside Elm.Native.Touch.make.  Specifically the var 't' is undefined.  The error occurs in the 'if' comparison, "if (localRuntime.timer.now() - t.t < tapTime)".
    
```
  function end(e) {
    var t = dict.remove(e.identifier);
    if (localRuntime.timer.now() - t.t < tapTime)
    {
      hasTap = true;
      tap = {
        x: t.x,
        y: t.y
      };
    }
  }
```

There is a pull request from this issue https://github.com/elm-lang/core/issues/390 which purports to solve the problem (or a similar problem), but for me the type error still occurs.  Pull request: https://github.com/elm-lang/core/pull/400

I gave that a try by manually applying the patch to an html page built with elm-make.  

Its not exactly a minimal example. but you can reproduce this error by checking out my project '[oscpad](https://github.com/bburdette/oscpad)' and running /elm/RunMe.elm with elm-reactor.  I may try to find a workaround so for future reference the bug occurred in commit  bcef5c3d27066f15642ba56f21a1040fa832256c.

**Comment by bburdette** [comment]
Tested with Chromium Version 45.0.2454.101 (64-bit) and with firefox nightly 42.0.

**Comment by bburdette** [comment]
For me I fixed it by removing the code that appears to emulate mousemove.  Maybe the way to go would be to put this emulation code somewhere else?  Or allow deactivating it.  https://github.com/bburdette/core/commit/fc240a3faa2ad887f942b2a304b0800c575682e5

**Comment by evancz** [comment]
Touch is not handled by core anymore. There is support for http://elm-lang.org/examples/drag stuff at the moment, but it's not super easy for touch yet.
