### ISSUE TITLE
Keyboard.presses not working in Firefox v 42.0

### ISSUE THREAD

**Issue by danchoi** [elm-lang/core#462]
This code works in Chrome and Safari for OS X, but not for Firefox v 42:

```elm
module KeyboardSignals where

import Keyboard
import Signal exposing (map)
import Graphics.Element exposing (show)

main = show `map` Keyboard.presses
```

In Safari and Chrome, pressing keys makes the number at the top update with the KeyCode. In Firefox v 42, the number remains "0" no matter what.

**Comment by jvoigtlaender** [comment]
I'm closing this, since it is covered by https://github.com/elm-lang/core/issues/326, https://github.com/elm-lang/core/pull/463 etc.
