### ISSUE TITLE
Touch:  touch events generated inadvertently

### ISSUE THREAD

**Issue by bburdette** [elm-lang/core#464]
I've made some svg controls that work with the touch library.  They work pretty well in on a touch device, but on my laptop its possible to put the touch controls into a mode where they receive touch events while the mouse cursor moves, even though the mouse button is not pressed.  With the right combination of clicks you can reverse it so they don't receive the mousemove touch events anymore.  

To reproduce the problem, check out my [oscpad](https://github.com/bburdette/oscpad) project and run elm-reactor.  Then go into elm-reactor and select RunMe.elm.  Hopefully the result looks something like this:

![screenshot](https://raw.githubusercontent.com/wiki/bburdette/oscpad/images/mousedown_problem.png)

So what you do is click on a part of the SVG that doesn't have a button or slider, then with the mouse button down move from there onto a button or slider area and release.  After that you'll get touches wherever you move the cursor, even though the mouse button is not down.  How it works is that when you click on the empty area, the Touch library does a "node.addEventListener('mousemove', move);".  If you move onto a button area and release, the 'move' remains in effect even though the mouse button is still up.  

To reverse the effect, click on an empty area again and release the mouse without moving.  This will cause "node.removeEventListener('mousemove', move);" to be called, which cancels the stream of touch messages.  

I've made a sort-of fix which is in this commit in my fork of core:  

https://github.com/bburdette/core/commit/f61a550e665d2fc3be2533481680ea10d883f52d

I put an undefined check into the end() function, since I thought that might have been causing a problem.  That didn't fix the issue, but what does fix it is getting rid of the 'localRuntime.addListener' calls for mousedown, mouseup, and blur.  That lets my code work as intended in either mouse or touch mode.  Removing these addListener calls probably breaks something horribly in someone else's code someplace, so I'm not proposing this as a fix necessarily.  I guess this stuff is for simulating touch events when you don't have a touch device?  For me I handle the mouse events separately so I don't want my mouse events in the form of touches.  Maybe this intention is to not have mouse events if you are using the touch library, just allow the touch library to take those over?

**Comment by bburdette** [comment]
In oscpad I made a hacky fix by just adding a copy of Touch.elm ("SvgTouch.elm") in my project, and making my changes to that.  So oscpad doesn't exhibit the problem anymore, but it should still manifest at commit a7de3341b2a00c482a05aa8b8e74485ae8158de4.

**Comment by evancz** [comment]
Touch stuff isn't handled in this package anymore.
