### ISSUE TITLE
Improve the Date API

### ISSUE THREAD

**Issue by imeckler** [elm-lang/core#467]
I think the `Date` API would really benefit from a function
```elm
ofYearMonthAndDay : { year : Int, month : Month, day : Int } -> Result String Date
```
since now the only ways of creating a date are from a string or a `Time`.
I'm not the best at naming things, so other name suggestions for this function would be much appreciated. 

It's a bit (though not entirely) of a separate issue, but it seems a `Date` is actually a calendar date equipped with a time of day. Thus the above function should in an ideal world be 
```elm
ofCalendarDateAndTime : { calendarDate : CalendarDate, time : TimeOfDay } -> Date
```
where `CalendarDate` is implemented by `{ year : Int, month : Month, day : Int}` and `TimeOfDay` is implemented by `Time`.

**Comment by lukewestby** [comment]
@imeckler These would be well suited for inclusion [here](https://github.com/lukewestby/elm-date-extra) until such a time that they might be included in core :smiley:

**Comment by jvoigtlaender** [comment]
@lukewestby, the link you give (https://github.com/lukewestby/elm-date-extra) leads into nothingness. But I agree that given [this policy](https://github.com/elm-lang/core/blob/master/CONTRIBUTING.md#adding-new-functions) it probably makes more sense to target another package with this feature request than `core`. Maybe https://github.com/rluiten/elm-date-extra?

**Comment by jvoigtlaender** [comment]
Or maybe https://github.com/rluiten/elm-date-extra does already provide the sought functionality?

**Comment by lukewestby** [comment]
Ah, sorry! I completely forgot to update this issue. Yes! Robin took over the effort on elm-date-extra, that is the "official" unofficial date extensions package. It does not currently provide the suggested functionality.

**Comment by jvoigtlaender** [comment]
@imeckler, can this be closed here? Take it up in https://github.com/rluiten/elm-date-extra?

**Comment by imeckler** [comment]
@jvoigtlaender Sounds good
