### ISSUE TITLE
Value comparison does not work for Date.Date

### ISSUE THREAD

**Issue by lukewestby** [elm-lang/core#468]
Simplest reproducible example, doable in the REPL:

```elm
import Date
(Date.fromTime 1) == (Date.fromTime 2) -- => True
```

This is happening because instances of JS `Date` are "exotic" objects and not primitives. They have no own properties and end up falling through both the strict equality and object cases for `Utils.eq()`. They're a rather strange edge case as far as JS object comparison goes, as they need to be coerced to their `Number` representation first with `+` or `valueOf()` first.

The workaround for now that I've been using is to do the same sort of coercion, just in Elm:

```elm
import Date
date1 = Date.fromTime 1
date2 = Date.fromTime 2
(Date.toTime date1) == (Date.toTime date2) -- => False
```

But IMVHO it seems like if `Date` is going to be a built-in data type for the language, it should be possible to compare instances reliably without transformation.

The way I would plan to handle this is by adding a top-level case to `eq` to check `x instanceof Date && y instanceof Date` and then compare `x.valueOf() === y.valueOf()`. If that plan makes sense to you I can submit a PR :smile:

Thanks!

**Comment by jvoigtlaender** [comment]
Mentioning @evancz, since I guess that is who @lukewestby means by "you" in the comment above, and since Evan might not otherwise even see the comment above anytime soon (not having notifications enabled for this repository).

**Comment by athanclark** [comment]
I'm not sure if this is related, but I've needed to compare `Date`s and have been disappointed that they're not natively `comparable`. I had to build this verbose utility function for comparing months, may you scrape it for success!

```elm
compareMonth : Month -> Month -> Order
compareMonth m1 m2 =
  case (m1, m2) of
    (Jan, Jan) -> EQ
    (Jan, _)   -> LT
    (Feb, Jan) -> GT
    (Feb, Feb) -> EQ
    (Feb, _)   -> LT
    (Mar, Jan) -> GT
    (Mar, Feb) -> GT
    (Mar, Mar) -> EQ
    (Mar, _)   -> LT
    (Apr, Jan) -> GT
    (Apr, Feb) -> GT
    (Apr, Mar) -> GT
    (Apr, Apr) -> EQ
    (Apr, _)   -> LT
    (May, Jan) -> GT
    (May, Feb) -> GT
    (May, Mar) -> GT
    (May, Apr) -> GT
    (May, May) -> EQ
    (May, _)   -> LT
    (Jun, Jan) -> GT
    (Jun, Feb) -> GT
    (Jun, Mar) -> GT
    (Jun, Apr) -> GT
    (Jun, May) -> GT
    (Jun, Jun) -> EQ
    (Jun, _)   -> EQ
    (Jul, Dec) -> LT
    (Jul, Nov) -> LT
    (Jul, Oct) -> LT
    (Jul, Sep) -> LT
    (Jul, Aug) -> LT
    (Jul, Jul) -> EQ
    (Jul, _)   -> GT
    (Aug, Dec) -> LT
    (Aug, Nov) -> LT
    (Aug, Oct) -> LT
    (Aug, Sep) -> LT
    (Aug, Aug) -> EQ
    (Aug, _)   -> GT
    (Sep, Dec) -> LT
    (Sep, Nov) -> LT
    (Sep, Oct) -> LT
    (Sep, Sep) -> EQ
    (Sep, _)   -> GT
    (Oct, Dec) -> LT
    (Oct, Nov) -> LT
    (Oct, Oct) -> EQ
    (Oct, _)   -> GT
    (Nov, Dec) -> LT
    (Nov, Nov) -> EQ
    (Nov, _)   -> GT
    (Dec, Dec) -> EQ
    (Dec, _)   -> GT
```
