### ISSUE TITLE
Runtime error with arrays

### ISSUE THREAD

**Issue by ckoster22** [elm-lang/core#474]
Copy/paste into http://elm-lang.org/try

```
import Array exposing (Array)

type alias Box =
  { value : String }

convertTo2D : Array Box -> Int -> Array (Array Box)
convertTo2D boxArray numRows =
  let
    nextRow = Array.slice 0 numRows boxArray
  in
    if Array.length nextRow > 0
    then Array.push nextRow (convertTo2D (Array.slice numRows (Array.length boxArray) boxArray) numRows)
    else Array.empty

oneDimArray = Array.initialize 100 (\index -> { value = toString index })

temp = convertTo2D oneDimArray 10
```

This is boiled down from a larger application. The relevant error is:
"Uncaught TypeError: Cannot read property 'height' of undefined  everything.js:831"

**Comment by jvoigtlaender** [comment]
Did you check it's not one of these [existing issues about arrays](https://github.com/elm-lang/core/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+arrays)?

**Comment by ckoster22** [comment]
I checked. It could possibly be this issue (https://github.com/elm-lang/core/issues/349) but it's unclear whether it's the same. None of them mention the same runtime error.

**Comment by jvoigtlaender** [comment]
Thanks!

**Comment by jvoigtlaender** [comment]
I've played a bit with your example. By unrolling the recursion a bit (repeatedly inlining `convert2D`) and trying with reduced overall size, I reduced it to this:
```elm
import Array

temp = 
  let
    n = 10
  in 
    Array.initialize (4*n) identity
    |> Array.slice n (4*n)
    |> Array.slice n (3*n)
    |> Array.slice n (2*n)
    |> Array.slice n n
```
This shows the same error.

And interestingly, changing `n = 10` to `n = 8` lets the error go away (while it remains for `n = 9`). Noticing that for `n = 8` we have `4*n = 32`, the "magic number" from #349, it might have something to do with that issue after all, or maybe share a common root problem with that one...

**Comment by evancz** [comment]
Closing in favor of #649 which will track all array issues and progress on a new implementation.

**Comment by wishfoundry** [comment]
I suspect this line is the culprit:
```javascript
var slot = new createNode(a.height - 1, 0);
```
in:
https://github.com/elm-lang/core/blob/master/src/Native/Array.js#L730

createNode() generates an new node, it should not be new'ed up itself
