### ISSUE TITLE
Request: allow undefined through ports, treat it like null

### ISSUE THREAD

**Issue by mietek** [elm-lang/core#476]
As mentioned on [elm-discuss](https://groups.google.com/forum/#!topic/elm-discuss/72pVKC2OlgQ) — can we have both `null` and `undefined` correspond to `Nothing`?

**Comment by kspeakman** [comment]
The maybe decoder converts undefined to Nothing, but ports do not.

This issue was referenced from another elm-discuss thread [here](https://groups.google.com/forum/#!topic/elm-discuss/vu2A3vHWUxM).

**Comment by evancz** [comment]
Tracking in https://github.com/elm-lang/elm-compiler/issues/1687 to see if any broader patterns emerge in things people are looking for. I am wary of making things super flexible because it can start to become confusing, but I'm not 100% convinced either way.
