### ISSUE TITLE
App randomly crashing in Dict: Cannot read property 'ctor' of undefined

### ISSUE THREAD

**Issue by seanhess** [elm-lang/core#478]
My app has historically worked without issues. I'm having some strange issues where it doesn't work as expected when I deliver it to my client. Right now, it crashes with the following message:

    Uncaught TypeError: Cannot read property 'ctor' of undefined

On this part of the generated .js

     var get = F2(function (targetKey,dict) {
        get: while (true) {
           var _p4 = dict;
           if (_p4.ctor === "RBEmpty_elm_builtin") {
                 return $Maybe.Nothing;
              } else {

The strange thing is every 5 or so hard reloads it works. Like it's a race condition or something? All of this code works perfectly locally, so it's frustrating to debug.

**Comment by seanhess** [comment]
I found the offending code. It was executed rarely because of a network race condition. 

      let res = case model.form of
                  Nothing -> res
                  Just form -> Session.applyDefaults form model.session.userInfo responses

res is defined recursively, which is an accident. I meant for it to be this:

                  Nothing -> model.responses

Should the compiler have caught this for me? Is there some flag I can enable to catch these? Or is it a bug, and if so where should I log it?

Thanks!

**Comment by jvoigtlaender** [comment]
See https://github.com/elm-lang/elm-compiler/issues/873 and a subset of the ton of related issues linked to from there.

**Comment by seanhess** [comment]
Thank you!
