### ISSUE TITLE
Regex.split modifies the state of the regex

### ISSUE THREAD

**Issue by rgrempel** [elm-lang/core#482]
`Regex.split` modifies the state of the `regex` parameter, because it does not reset the `lastIndex` property.

This is essentially the same problem that `Regex.find` had, before the following commit:

https://github.com/jonathanhefner/elm-core/commit/3fcf5831d3ef5c8f6c324c092ea937e5fc3c156b

So, `Regex.split` essentially needs a similar sort of fix.

**Comment by jvoigtlaender** [comment]
Can you give an example of an Elm program that is affected by this issue? (Same question for https://github.com/elm-lang/core/issues/483 as well.)

**Comment by rgrempel** [comment]
Well, it turns out that I can't -- so I'll close this issue!

**Comment by rgrempel** [comment]
Ah, actually I can illustrate the issue, using http://elm-lang.org/try. Here's the problematic example:

```elm
import Regex exposing (..)
import Graphics.Element exposing (..)

findComma = regex(",")

main = show
  [ split (AtMost 1) findComma "a,b,c,d,e"
  , split (AtMost 1) findComma "a,b,c,d,e"
  ] 
```

It produces:

```elm
[["a","b,c,d,e"],["b","c,d,e"]]
```

... where one would expect the same result both times.

**Comment by evancz** [comment]
Consolidated regex stuff in #722. Follow along there!

Seems like this could be a PR though.
