### ISSUE TITLE
Add Json.Encode.dict

### ISSUE THREAD

**Issue by avh4** [elm-lang/core#484]
There is a JSON decoder for Dict, but currently there is no corresponding encoder.

```elm
module Json.Encode where

dict : (v -> Value) -> Dict String v -> Value
-- or
dict : Dict String Value -> Value
```

**Comment by narkisr** [comment]
+1

**Comment by cullophid** [comment]
+1 
How do you get around this atm?
Do you have to convert all ducts to lists?

**Comment by narkisr** [comment]
https://github.com/celestial-ops/elm-ui/blob/master/src/Types/Persistency.elm#L41

**Comment by cullophid** [comment]
Thank you:)

**Comment by vilinski** [comment]
+1

**Comment by jvoigtlaender** [comment]
Add it to https://github.com/elm-community/json-extra?

Or even just open this feature request as an issue there (in line with https://github.com/elm-lang/core/blob/master/CONTRIBUTING.md#adding-new-functions)?

That package has a maintainer (https://github.com/elm-community/Manifesto/blob/master/maintainers.md).

**Comment by jvoigtlaender** [comment]
Also, there's http://package.elm-lang.org/packages/bartavelle/json-helpers/1.1.1/Json-Helpers#jsonEncDict, which may or may not be what you all want.

**Comment by lukewestby** [comment]
@vilinski i'd like to add a `Json.Encode.Extra` to `elm-community/json-extra`, and `dict` is a great fit for such a module. feel free to submit a PR!

**Comment by evancz** [comment]
With feature suggestions like this, I think the best route is to (1) tell folks about `*-extra` packages and (2) close the issue and add it to something like #322. That's what makes sense in this case at least.
