### ISSUE TITLE
Keyboard should have a signal of keypresses as well as than isDown states

### ISSUE THREAD

**Issue by jameshfisher** [elm-lang/core#49]
The `Mouse` module has `isDown` and `clicks`. The `Keyboard` module only has `isDown`. I would like a function `keypresses : KeyCode -> Signal ()`, analogous to `Mouse.clicks`.

I've implemented it like this, but there's probably a better way, and it would be nice if this functionality were in core:

```
keypresses : KeyCode -> Signal ()
keypresses c = isDown c |> keepIf identity False |> map (always ())
```

**Comment by evancz** [comment]
I believe this is resolved with `elm-lang/keyboard`
