### ISSUE TITLE
Json.Decode.float chokes on Infinity

### ISSUE THREAD

**Issue by philderbeast** [elm-lang/core#496]
```
> import Json.Decode exposing (..)
> decodeString float "1.0"
Ok 1 : Result.Result String Float
> decodeString float "Infinity"
Err ("Unexpected token I") : Result.Result String Float
```

There's a long discussion of whether JSON does/should support infinity here ...

http://stackoverflow.com/questions/1423081/json-left-out-infinity-and-nan-json-status-in-ecmascript

Elm does have the isInfinite function. I'm using FsPickler and it converts F# infinity to "Infinity" when encoding to JSON so that's one JSON encoder that includes infinity.

**Comment by jvoigtlaender** [comment]
Related: https://github.com/elm-lang/core/pull/342.

Also, what about NaN?

**Comment by lukewestby** [comment]
A quick note about `JSON.parse` given that JS is Elm's only backend right now:

The algorithm used in `JSON.parse` [expects that incoming text conform](http://www.ecma-international.org/ecma-262/6.0/#sec-json-object) to the definition of JSON in [ECMA-404](http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-404.pdf) which explicitly disallows non-digit number values, including `Infinity` and `NaN`.

One option to get around this using a `Json.Decode.Decoder` would be to write a `customDecoder` which attempts to parse a field as a number, and then falls back to trying to find `"Infinity"` as a String and returning `1/0` as the decoder result.

**Comment by evancz** [comment]
I like @lukewestby's way of handling this.

Fundamentally, using `JSON.parse` will trigger the error before any decoders have a chance to run, so I'm not sure what can actually be fixed though.

Makes sense to have in `json-extra` for now though!
