### ISSUE TITLE
Graphics.Element.layers fails with an empty list

### ISSUE THREAD

**Issue by rehno-lindeque** [elm-lang/core#5]
The program
```
main = layers []
```
...produces an exception...
```
Function 'foldl1' expects a non-empty list!
```
...due to the two calls to `List.maximum` over here: https://github.com/elm-lang/core/blob/53aef4887e668a5732ffff1ad0560bab779e8674/src/Graphics/Element.elm#L330

**Comment by jvoigtlaender** [comment]
This got fixed at some point. The two calls of `List.maximum` now return `Maybe`s and are wrapped in `withDefault`s.
