### ISSUE TITLE
Task.map2 example is not working

### ISSUE THREAD

**Issue by paparga** [elm-lang/core#501]
Hi!

I tried Task.map2 example 
`succeed 5 == map2 (+) (succeed 2) (succeed 3)`
and it returns `False`

Is this ok?

Pablo

**Comment by jvoigtlaender** [comment]
See [this comment](https://github.com/elm-lang/core/issues/403#issuecomment-152402738) of @evancz. Equality on `Task`s is in the same league as the others mentioned there. So: `Task.map2` *is* working, `==` on tasks *isn't*, and shouldn't be expected to.

**Comment by jvoigtlaender** [comment]
Closing this issue, opened another one pointing out the real problem more explicitly: https://github.com/elm-lang/core/issues/502.
