### ISSUE TITLE
Documentation suggests that `==` works on tasks, but it doesn't

### ISSUE THREAD

**Issue by jvoigtlaender** [elm-lang/core#502]
For example, the documentation of `Task.map2` (http://package.elm-lang.org/packages/elm-lang/core/3.0.0/Task#map2) contains this line:
```elm
map2 (+) (succeed 9) (succeed 3) == succeed 12
```
However, issuing that exact line in a program will actually evaluate to `False`. Very confusing, for example to @paparga [here](https://github.com/elm-lang/core/issues/501).

Maybe the documentation shouldn't be using `==` on tasks, and indeed maybe it should explicitly mention that `==` is wonky on tasks, as the documentation already says elsewhere about `Dict` etc.

(Note: For `Dict` etc., equality could potentially be made unwonky, but for tasks not.)

**Comment by halfzebra** [comment]
Here's my take on fixing those confusing in docs #557

**Comment by jvoigtlaender** [comment]
Thanks, I like your changes there!

I'll copy my original comment from above to the opening comment over there, so that Evan sees it all in one place when reviewing the PR.
