### ISSUE TITLE
Weird order for Maybe.andThen

### ISSUE THREAD

**Issue by calebmer** [elm-lang/core#505]
Why is `Maybe.andThen` defined like:

```elm
andThen : Maybe a -> (a -> Maybe b) -> Maybe b
```

Instead of:

```elm
andThen : (a -> Maybe b) -> Maybe a -> Maybe b
```

Because it is defined the other way around it is much more difficult to compose.

**Comment by jvoigtlaender** [comment]
This is a question for the mailing list: https://groups.google.com/forum/#!forum/elm-discuss

**Comment by calebmer** [comment]
Due to my circumstances I can't participate in the mailing list.

**Comment by jvoigtlaender** [comment]
Hmm, weird.

**Comment by jvoigtlaender** [comment]
Closing this, since obviously no discussion is going to happen here.
