### ISSUE TITLE
Performance problem: Window module causing unnecessary layout reflow 

### ISSUE THREAD

**Issue by w0rm** [elm-lang/core#510]
In the Runtime code there is a `draw` function that checks for Window module and calls `resizeIfNeeded` if it exists. 

```
function draw()
{
    update(elm.node.firstChild, savedScene, scheduledScene);
    if (elm.Native.Window)
    {
        elm.Native.Window.values.resizeIfNeeded();
    }
    savedScene = scheduledScene;
}
```

`resizeIfNeeded` calls  `node.clientWidth` and `node.clientHeight` that [trigger layout reflow](https://gist.github.com/paulirish/5d52fb081b3570c81e3a).

Because `draw` function happens very often, this affects the performance and makes it impossible to use Window module to calculate dimensions in HTML5 games that render on every `requestAnimationFrame`.

**Comment by w0rm** [comment]
Seems that this is in the project from old times, tracked the `resizeIfNeeded` call down up until this commit https://github.com/elm-lang/core/commit/1af7914fe8c57d241cdd237c03d9c4c316b1f80a

**Comment by w0rm** [comment]
Below are two timelines of my game, one before, and another one after I deleted `resizeIfNeeded` call from the `draw` function.

![screen shot 2016-02-27 at 19 27 05](https://cloud.githubusercontent.com/assets/43472/13374568/cab68ace-dd88-11e5-92ed-d719b8439b8e.png)

You can see that the second one is mostly green with the frames painted in less than 20ms.

![screen shot 2016-02-27 at 19 30 08](https://cloud.githubusercontent.com/assets/43472/13374567/cab616d4-dd88-11e5-90ee-d1fc19509685.png)

The question is, why is it there in the first place, and can it be removed?

**Comment by evancz** [comment]
I guess it can be removed. I do not think `elm-lang/window` will have this issue.
