### ISSUE TITLE
Graphics.Collage doesn't allow to offset the texture

### ISSUE THREAD

**Issue by w0rm** [elm-lang/core#511]
I found out that the DOM is a wrong engine to render my HTML5 game due to performance, and wanted to use the canvas, however I discovered that `Collage.textured` [doesn't allow to offset the texture](http://package.elm-lang.org/packages/elm-lang/core/3.0.0/Graphics-Collage#textured), that I need to render animation strips. 

Also, waiting for `img.onload` and redrawing the whole canvas is bad, because its uncontrolled. A [task to load an image](https://github.com/zalando/elm-street-404/tree/master/vendor/elm-image-load) would be a much better approach. [elm-webgl](http://package.elm-lang.org/packages/elm-community/elm-webgl/1.0.0/WebGL#loading-textures) uses the same approach to load textures.

**Comment by evancz** [comment]
Sorry for the slow reply, it has been a busy time! All the `Graphics.*` modules live in `evancz/elm-graphics` now, so it makes sense to move issues like this there.
