### ISSUE TITLE
Keyboard should provide an equivalent to the wasd function for non-english layout

### ISSUE THREAD

**Issue by kototama** [elm-lang/core#512]
The keyboard module should provide a function to build the equivalent of the `wasd` function, or at least expose `dropmax` and `toXY`, to allow the clients to have the function for non-english layout.

**Comment by jvoigtlaender** [comment]
Please consider everything that was writzen here: https://github.com/elm-lang/core/pull/492

**Comment by jvoigtlaender** [comment]
@kototama, any further thoughts after reading what I pointed you to?

**Comment by kototama** [comment]
[That's](https://github.com/elm-lang/core/pull/492#issuecomment-174530430) basically what I did before opening this PR. It's not as convenient as it seems.

I can understand the wish to not put too much into core but on the other hand, for this case, core is assuming that most users will have a US layout. The need of users having others layouts is more complicate to implement because not all functions are exposed. It's not very fair.

A library can be close to modification, but it should be open for extension. It would be nicer to have a higher level function that build the equivalent of `wasd` given different keys mapping / layouts.

**Comment by jvoigtlaender** [comment]
Fair points. I am not making decisions about what goes into `core`. So you'll have to wait until the person who does gets around to considering your issue.

But as pointed out by me in the other thread, a more targetted request (more targetted than "provide an equivalent to the `wasd` function for non-english layout") may make more sense. Propose specifically to resurrect the `directions` function from `core` version `1.0.0`? Or just to expose the `toXY` function? (Exposing `dropMap` makes no sense from an API perspective.)

**Comment by kototama** [comment]
I'll have a second look when I have more time. Thank you.

**Comment by jvoigtlaender** [comment]
This issue would now belong over at https://github.com/elm-lang/keyboard.
