### ISSUE TITLE
Json.Decoder for objects with more than 8 arguments

### ISSUE THREAD

**Issue by tiziano88** [elm-lang/core#514]
I am working on a plugin to generate protobuf bindings for Elm (https://github.com/tiziano88/elm-protobuf); it uses the `Json.Decode` package to deserialize JSON into Elm objects, but it is hitting the limitations of the `objectN` combinators in that package; it is not unusual for protobuf objects to have dozens of fields, but the `Json.Decode` package only offers up to [`object8`](http://package.elm-lang.org/packages/elm-lang/core/3.0.0/Json-Decode#object8) as a convienence to build objects from other combinators.

I believe if Elm had a way of expressing Applicative Functors, this pattern would fall into that scope (e.g. `obj <$> dec1 <*> dec2 <*> dec3 ...`), and there would be no need for all the overloaded versions of this combinator, but currently, it seems inevitable.

So my question is: should I rely on some more custom way of deserializing JSON for large objects, or should we increase the number of overloaded `objectN`, or something else entirely?

Please let me know if you have any suggestions at all, I am happy to discuss alternatives.

See [here](
https://github.com/tiziano88/elm-protobuf/blob/8fe398beaf60b0dc0294fc2c5613c5410372a7ef/protoc-gen-elm/test/1/expected_output/Test.elm#L137) for an example code generated by the protobuf plugin that uses `object7`.

**Comment by jvoigtlaender** [comment]
You may want to use the `(|:)` operator: [http://package.elm-lang.org/packages/circuithub/elm-json-extra/latest/Json-Decode-Extra#|:](http://package.elm-lang.org/packages/circuithub/elm-json-extra/latest/Json-Decode-Extra#|:).

Generally, for such discussion, please use the [mailing list](https://groups.google.com/forum/#!forum/elm-discuss). This issue tracker here serves a different purpose.

**Comment by tiziano88** [comment]
Thanks @jvoigtlaender, that makes perfect sense, I didn't realise Json.Decode already has an `andThen` operator, which makes it a Monad and hence also an Applicative Functor already. I have [modified](https://github.com/tiziano88/elm-protobuf/commit/1651e82d11c4a8773e628af6aa6737ff63d7a1b3) my plugin already, emulating an Applicative-style syntax, although it is only bound to the `Json.Decode` instance (I really wish Elm had HKTs so that this pattern could be generalised).

Apologies for not posting to the appropriate medium, I shall take more care going forward.
