### ISSUE TITLE
Date.fromTime is returning {}

### ISSUE THREAD

**Issue by akovari** [elm-lang/core#516]
In repl, but this doesn't work in neither Chrome nor in Firefox:

```
> import Date
> Date.fromTime 1461967200000
{} : Date.Date
```

This is calling Native.Date.fromDate which does just this:
`new Date(1461967200000);`

Not quite sure why but this doesn't seem to be working.

**Comment by jvoigtlaender** [comment]
Duplicate of https://github.com/elm-lang/core/pull/442.
