### ISSUE TITLE
Result.sequence

### ISSUE THREAD

**Issue by berdario** [elm-lang/core#519]
I couldn't find this when I needed, and I implemented it myself

```
resultSequence : List (Result x a) -> Result x (List a)
resultSequence xs = case xs of
    [] -> Ok []
    result :: rest -> Result.map2 (::) result (resultSequence rest)
```

I would expect this to be available, by simmetry with [Task](http://package.elm-lang.org/packages/elm-lang/core/3.0.0/Task#sequence).

I haven't found anyone asking for this earlier in this bug tracker, but maybe it might still be of interest?

PS:

I just realized that there's a [elm-result-extra](https://github.com/circuithub/elm-result-extra)... due to the policy of keeping elm-core lean, maybe this should be proposed to be included there, at first?

**Comment by jvoigtlaender** [comment]
Regarding the PS: Yes, indeed, see https://github.com/elm-lang/core/blob/master/CONTRIBUTING.md#adding-new-functions.

And indeed, the function seems to already exist there, http://package.elm-lang.org/packages/circuithub/elm-result-extra/1.4.0/Result-Extra#combine.
