### ISSUE TITLE
Using two Keyboard signals, the second did not work

### ISSUE THREAD

**Issue by jessitron** [elm-lang/core#520]
Using both Keyboard.keysDown and Keyboard.ctrl, mapping then merging them to get my input signal: the second one (Keyboard.ctrl) did not fire. Replacing Keyboard.keysDown with a constant signal caused Keyboard.ctrl to work. 

Is this expected? Can only one of the signals that internally feeds off keysDown be used?
If so, documentation would be nice,

I'm in Safari on a Mac.

**Comment by jvoigtlaender** [comment]
Isn't the last sentence of the documentation of http://package.elm-lang.org/packages/elm-lang/core/3.0.0/Signal#merge clear enough on this?

**Comment by jvoigtlaender** [comment]
You may want to use http://package.elm-lang.org/packages/Apanatshka/elm-signal-extra/5.7.0/Signal-Extra#fairMerge.

**Comment by jessitron** [comment]
Thanks for the references.

It is not clear that keysDown and ctrl are the same signal underneath. (I can see it in the source, but not the docs)

**Comment by jvoigtlaender** [comment]
Yes, it's nowhere specified in the docs which signals come from the same origin.

Do you have a proposal for how to do this? For the `Keyboard` module or in general?

**Comment by jvoigtlaender** [comment]
No reply from @jessitron. Am closing this.

**Comment by jessitron** [comment]
Sorry I missed this notification.
It's OK to close it, it isn't specifically a bug, but it would be nice if
there was a comment at the top of the Keyboard file indicating which
signals are mutually exclusive.

On Sun, Mar 20, 2016 at 6:43 PM, Janis Voigtländer <notifications@github.com

**Comment by jvoigtlaender** [comment]
@jessitron, I try to address this in https://github.com/elm-lang/core/pull/532 now.

**Comment by jessitron** [comment]
\o/
