### ISSUE TITLE
Exponentiation (^) can break Int/Float type safety

### ISSUE THREAD

**Issue by mgold** [elm-lang/core#529]
Currently, exponentiation `(^) : number -> number -> number`. A negative integer power will yield a float, producing a float value typed as an Int.

```elm
base : Int
base = 10

power : Int
power = -3

bad : Int
bad = base ^ power
```

`toFloat bad == 0.001` which can cause all kinds of havoc.

Perhaps the return value should be changed from `number` to `Float`.

**Comment by jvoigtlaender** [comment]
Closing as a duplicate.

**Comment by mgold** [comment]
I looked for if this had already been reported... where's the original?

**Comment by jvoigtlaender** [comment]
#194, #526

**Comment by mgold** [comment]
Ok thanks.
