### ISSUE TITLE
Parse error in Graphics.Element (elm-lang/core 3.0.0)

### ISSUE THREAD

**Issue by daveyarwood** [elm-lang/core#531]
When trying to run elm-test in a project using elm-lang/core 3.0.0, I got this parse error:

```
Error in package elm-lang/core 3.0.0 in module Graphics.Element:

Parse error at (line 143, column 43):
unexpected ","
expecting field access (e.g. List.map), whitespace, a newline, "-", basic term (4, x, 'c', etc.), infix operator or closing bracket '}'


This error is probably due to bad version bounds. You should definitely
inform the maintainer of elm-lang/core to get this fixed.
```

The problematic line appears to be [on this line in Graphics.Element](https://github.com/elm-lang/core/blob/3.0.0/src/Graphics/Element.elm#L143), the comma right after `newWidth`.

I'm new to Elm -- what's the issue with that comma?

**Comment by jvoigtlaender** [comment]
Which version of Elm are you using? I suspect, something too old.

**Comment by daveyarwood** [comment]
```$ elm
Elm Platform 0.16.0 - a way to run all Elm tools
...
```

**Comment by jvoigtlaender** [comment]
But your call of elm-test, which Elm version is *that* calling?

**Comment by daveyarwood** [comment]
A-ha! I think it was calling an older version of Elm that I installed a long time ago via cabal -- `~/.cabal/bin` is ahead of `/usr/local/bin` in my `$PATH` so it must have been using the older version. I just ran `rm ~/.cabal/bin/elm*` and re-ran `elm-test` and now it's working :+1: 

Thanks!
