### ISSUE TITLE
Duplicate field definition

### ISSUE THREAD

**Issue by ordavidil** [elm-lang/core#533]
Hey,

So I just started with Elm and it feels great for now, thanks.

It seems that the compiler allow me to define the same field twice, even with a __different type__, it just takes the latest definition but I would've expect it will raise an error.

Example:
```elm
type alias Model =
  { id: Int
  , a: Int
  , a: String
  }
```

**Comment by jvoigtlaender** [comment]
Please report this at https://github.com/elm-lang/elm-compiler instead of here (`core` is the standard library, not the compiler).

**Comment by ordavidil** [comment]
Thanks, sorry about that.
