### ISSUE TITLE
LineStyle.dashOffset doesn't have any effect (is ignored in implementation)

### ISSUE THREAD

**Issue by hoelzro** [elm-lang/core#534]
I was playing with some code to try to create the "marching ants" effect with a line, but changing `dashOffset` on my line style doesn't appear to affect the way the line is drawn.  Here's a minimal example that produces the issue:

```elm
import Color exposing (black)
import Graphics.Collage exposing (collage, dashed, segment, traced)
import Graphics.Element exposing (Element)

main : Element
main =
  let styleSansOffset = dashed black
      styleWithOffset = { styleSansOffset | dashOffset = 8 }

      lineSansOffset = traced styleSansOffset <| segment (0, 0) (100, 100)
      lineWithOffset = traced styleWithOffset <| segment (0, 10) (100, 110)

  in collage 300 300 [ lineSansOffset, lineWithOffset ]
```

and its output:

![2016-03-23-114348_274x206_scrot](https://cloud.githubusercontent.com/assets/107804/13993033/87b2d0b2-f0ec-11e5-953f-e8ba0ef4ce3a.png)

**Comment by jvoigtlaender** [comment]
Indeed, `dashOffset` is completely ignored in `Native/Graphics/Collage.js`. In fact, the `dashOffset` field is never accessed in the whole `core` code base. It might as well not exist.

Clearly an unsupported feature at the moment. Might make sense to remove it from the `LineStyle` type.

**Comment by jvoigtlaender** [comment]
Made a pull request for removing that feature: https://github.com/elm-lang/core/pull/535.
