### ISSUE TITLE
toString() for native objects

### ISSUE THREAD

**Issue by esad** [elm-lang/core#539]
I'm working on an Elm wrapper for PouchDB. In the app that uses the wrapper, the model has the reference to the PouchDB object. Trying to  `Debug.log` the model record then results in 

`RangeError: Maximum call stack size exceeded.`

I guess the db object has a cyclic reference somewhere.

To help with this case, and be able to control string representation of a native (wrapped) objects in general, I propose a convention of having a custom (e.g. `elm_toString`) function. The `Native.Utils.toString` implementation could then check if `elm_toString` is defined on an object and instead of iterating through properties, call this function to get the intended string representation.

**Comment by evancz** [comment]
Follow along in the #723 meta issue.
