### ISSUE TITLE
Exception in JS port handler causes Signal to stop updating

### ISSUE THREAD

**Issue by robertjlooby** [elm-lang/core#541]
If a `Signal` is sent out a `port`, and the handler errors on the JS side, then the value of the `Signal` stops updating on the Elm side after the first update.

There is a small example of it [here](https://github.com/robertjlooby/elm-port-error). The displayed time _should_ update once a second to the current time. You'll see it update the display once (which throws the first error) and after that it just errors with the "notify message has been called synchronously" message and the `Signal` stops updating on the Elm side. There is a related issue [here](https://github.com/elm-lang/core/issues/374) but it seems mostly concerned with providing a more accurate error message.

As a more practical example, the [todomvc app](http://evancz.github.io/elm-todomvc/) will not work on Safari in a private window because any access to localstorage throws an error.

----------------------------------

<img width="529" alt="screen shot 2016-03-29 at 10 30 50 pm" src="https://cloud.githubusercontent.com/assets/2107646/14131142/14cfafa4-f5fe-11e5-8fde-51cef113b10e.png">

**Comment by evancz** [comment]
Not sure if this is still true, but there at least are not signals anymore. It may persist in 0.17, but I think that'd need a different SSCCE.

**Comment by evancz** [comment]
Also sorry for the slow response on this stuff! I have been really focused on 0.17 so certain things were getting less attention. Port issues are pretty serious though!
