### ISSUE TITLE
Can't directly access nested records from another module 

### ISSUE THREAD

**Issue by Ryan1729** [elm-lang/core#543]
Given the following files:

Main.elm
```
module Main (..) where

import Graphics.Element exposing (..)
import A


main : Element
main =
  show A.b.c
```

A.elm

```
module A (..) where


b =
  { c = "123" }
```

I get the following error
```

Detected errors in 1 module.
-- NAMING ERROR ------------------------------------------------------- Main.elm

Cannot find variable `A.b.c`.

9│   show A.b.c
            ^^^
The qualifier `A.b` is not in scope. Maybe you want one of the following?

    A.c

```
Changing it to `A.b` shows the whole record `{ c = "123" }` as expected.
If I give `A.b` another name, say `d = A.b` then `d.b` gives the expected output, so I can use that as a workaround but not being able to access the record's value was unexpected.  

Running 0.16.0 through elm reactor.

**Comment by jvoigtlaender** [comment]
Thanks for the report. It's not a `core` issue, but an `elm-compiler` issue. And it's already tracked there: https://github.com/elm-lang/elm-compiler/issues/520

So I'm closing this issue here.
