### ISSUE TITLE
Array.length producing this error: TypeError: Cannot read property 'height' of undefined

### ISSUE THREAD

**Issue by rebelwarrior** [elm-lang/core#549]
Hi, I got an unusual error after compilation:
```{bash}
Successfully compiled SublistTests.elm
Running tests...
Cannot read property 'height' of undefined
[stdin]:415
				throw error;
				^

TypeError: Cannot read property 'height' of undefined
    at length ([stdin]:7895:12)
    at sliceRight ([stdin]:7499:14)
    at sliceRight ([stdin]:7514:16)
    at Function.slice [as func] ([stdin]:7494:26)
    at A3 ([stdin]:867:10)
    at Function.func ([stdin]:9114:27)
    at A3 ([stdin]:867:10)
    at Function.func ([stdin]:9132:39)
    at A3 ([stdin]:867:10)
    at Function.func ([stdin]:9140:14)
```

This is the offending code: 
```{elm}
ifArrayFits : Array.Array a -> Array.Array a -> Int -> Bool
ifArrayFits array1 array2 indexOf2 =
  let
    indexEnd = (Array.length array1) + indexOf2
  in
    (array1 == (Array.slice indexOf2 indexEnd array2))
```

This is from exercism.io here is the link:
[exercism.io/rebelwarrior/elm/sublist](http://exercism.io/submissions/2cb2057ab25c4a33a6b5e01b66012cbc)
Version 0.16 of Elm. 
It could be related to the way it is tested. I tried all the commands in this function in the repl and all worked fine. However, if I simply returned `True` or `False` from the function and commented out the code the error disappeared.

**Comment by jvoigtlaender** [comment]
Probably the same as https://github.com/elm-lang/core/issues/349 and/or https://github.com/elm-lang/core/issues/474?

**Comment by rebelwarrior** [comment]
Definitely not #349. 
If I hard code indexEnd to 32 33 or even 133 I get no error. 
It's not the slice alone it's the array + length that's producing the error.

**Comment by jvoigtlaender** [comment]
> If I hard code indexEnd to 32 33 or even 133 I get no error. 

Doesn't mean https://github.com/elm-lang/core/pull/399 won't fix this.

**Comment by rebelwarrior** [comment]
Here is another weird thing I tried it on try elm and reproduced the error with this code, but once it failed once I reduced one number by one and the returned it to the original value and NO Error. So it seems to be an intermittent issue with very large Arrays.
```{elm}
module Sublist (..) where

import Set
import Array
import Maybe
import Graphics.Element exposing (..)
import Debug exposing (..)

sublist : List comparable -> List comparable -> String
sublist list1 list2 =
  let
    size1 = List.length list1
    size2 = List.length list2
  in
    if list1 == list2 then
      "Equal"
    else if List.isEmpty list1 && not (List.isEmpty list2) then
      "Sublist"
    else if List.isEmpty list2 && not (List.isEmpty list1) then
      "Superlist"
    else if size1 <= size2 && isSublistOf list1 list2 then
      "Sublist"
    else if size2 <= size1 && isSublistOf list2 list1 then
      "Superlist"
    else
      "Unequal"

isSublistOf list1 list2 =
  let
    array1 = Array.fromList list1
    array2 = Array.fromList list2
  in
    -- check recursively if array2 indexes match first element of array1
    -- if so check if it fits
    checkArrayEl_r array1 array2 0

checkArrayEl_r : Array.Array a -> Array.Array a -> Int -> Bool
checkArrayEl_r array1 array2 indexOf2 =
  case (Array.get indexOf2 array2) of
    Nothing -> False
    Just el2 ->
      case (Array.get 0 array1) of
        Nothing -> False
        Just el1 ->
          if el1 /= el2 then
            checkArrayEl_r array1 array2 (indexOf2 + 1)
          else
            ifArrayFits array1 array2 indexOf2

ifArrayFits : Array.Array a -> Array.Array a -> Int -> Bool
ifArrayFits array1 array2 indexOf2 =
  -- Code below is producing an error and it should not...
  -- TypeError: Cannot read property 'height' of undefined
  let
    indexEnd = (Array.length array1)
    x = log ((toString indexOf2) ++ "---------**------")
    -- indexEnd = 133
  in
    (array1 == (Array.slice indexOf2 (indexEnd + indexOf2) array2))

main : Element
main =
  show (sublist [10..1000001] [1..100000])
```

**Comment by rebelwarrior** [comment]
That's true @jvoigtlaender it maybe the solution to one may fix the other. Slice is definitely funky for Arrays.

**Comment by rebelwarrior** [comment]
Now this is interesting I refactored the code to use Lists instead of Arrays and we get this very odd compile error that says array1 is not an Array but it passes a definition of `Array.Array Int` (but not by the way one with `Array.Array a`).
There is no slice in this code but now I'm wondering if it's the `Array.fromList` that's causing the problem.
Here is the link to the code:
[exercisim.io](http://exercism.io/submissions/15f1da1aaf6148008e4b7b3630dad6b0)

**Comment by evancz** [comment]
Closing in favor of #649 which will track all array issues and progress on a new implementation.
