### ISSUE TITLE
Feature request: continuous keydown events

### ISSUE THREAD

**Issue by jinjor** [elm-lang/core#551]
Currently `Keyboard` module does not have API for continuous keydown events. `Keyboard.isDown` is fired only when value is changed, but I sometimes need many events when I keep keys pressing.

For example, I am implementing Undo/Redo triggered by `ctrl+Z`/`ctrl+Y`. I usually undo 100+ steps by keep `ctrl+Z` pressing, but this feature cannot be implemented using current API.

**Comment by halfzebra** [comment]
You can achieve that by doing something like this:

`
import Keyboard
import Signal
import Time
import Debug
import Graphics.Element exposing (show)


main =
  Keyboard.keysDown
  |> Signal.sampleOn (Time.fps 30)
  |> Signal.map show
`

**Comment by jinjor** [comment]
Thanks, but I need different behavior. When some key is keeping pressed, The first event is fired immediately and the rest are fired after some interval. Like this:

a.......aaaaaaaaaaaaaaa

Also, I read the source and found the `down` state is made by filtering original events. I think it's more natural to use the original events than to reproduce new events.

**Comment by Warry** [comment]
Repeating keys can be retrieved with `keyup`, but the core only supports `keydown`. I agree with @jinjor that it should be the developer's choice and should be available there.

Maybe we should expose `document`'s events withOptions, just like for `Html`, where we can listen to an event by giving a string and a decoder.

**Comment by evancz** [comment]
A think this is solved in `elm-lang/keyboard`
