### ISSUE TITLE
Table rowspan and colspan issue in Internet Explorer and Edge

### ISSUE THREAD

**Issue by majorimi** [elm-lang/core#552]
Here is a sample app which demonstrates the issue with virtual DOM rendering in IE and Edge. We have a similar app (almost in production so we need a quick fix please) but in IE we have problem with table colspan and rowspan attributes. In the test app you can click 2 buttons (click them more then once) and you can see the problem. The same code works fine in Firefox and Chrome.
https://github.com/majorimi/ElmTableBug

**Comment by evancz** [comment]
Thanks! Fixes should be out in the next week or two.
