### ISSUE TITLE
1 `rem` 0 is NaN

### ISSUE THREAD

**Issue by miikka** [elm-lang/core#563]
Just noticed this (with elm repl 0.16.0 - not sure if that's the relevant version information):

```
> 1 `rem` 0
NaN : Int
```

Issue elm-lang/elm-compiler#262 seems to say that `NaN` shouldn't be an `Int`, so I assume this is a bug. [Relevant source](https://github.com/elm-lang/core/blob/3.0.0/src/Native/Basics.js#L18).

(I originally opened this issue as elm-lang/elm-compiler#1338 but moved it here as per @mgold's suggestion.)

**Comment by jvoigtlaender** [comment]
Fixing this in https://github.com/elm-lang/core/pull/564.

**Comment by jvoigtlaender** [comment]
I've replaced #576 by the more comprehensive #590.

I'm closing this here, since I think any discussion of this should take the larger picture of other division operators in Elm into account, see #590.
