### ISSUE TITLE
Json.Decode should expose "key" as a non-infix name for (:=)

### ISSUE THREAD

**Issue by ThomasWeiser** [elm-lang/core#567]
[NoRedInk/elm-decode-pipeline](http://package.elm-lang.org/packages/NoRedInk/elm-decode-pipeline/latest) postulates the abstention of infix operators, IMHO for good reasons, at least in library APIs.

`Json.Decode` exports the infix operator `:=` without a non-infix name. I propose to give it also a reasonable non-infix name. Can't make up for a good one at the moment, but think about something like ~~`at1`~~ `key`.

Example, using the infix operator:
```elm
import Json.Decode as JD exposing ((:=))

decodeName : JD.Decoder String
decodeName = "name" := JD.string
```
Evading infix operators currently forces to use `at` with a one-member list:
```elm
import Json.Decode as JD

decodeName = JD.at ["name"] JD.string
```
Proposal (edited):
```elm
decodeName = JD.key "name" JD.string
```

**Comment by jvoigtlaender** [comment]
How about
```elm
decodeName = JD.child "name" JD.string
```
or something like that? Also possible: `field`.

**Comment by ThomasWeiser** [comment]
Musing about the name: Official JSON docs speak of _name/value pairs_, but _name_ is not a nice name :) Actually, the most used term (beside _name_) in JSON land seems to be _key_. This is also the idiom used in Elm's `Dict` and it already appears as ```Json.Decode.keyValuePairs```.

So I propose: **```Json.Decode.key```** as in:

```elm
import Json.Decode as JD

decodeName : JD.Decoder String
decodeName = JD.key "name" JD.string
```

**Comment by evancz** [comment]
I agree that the API should be changed to be more in line with more recent libraries informed by usage, but I do not want to track API suggestions here.
