### ISSUE TITLE
Nested comparisons happen in unexpected order

### ISSUE THREAD

**Issue by jvoigtlaender** [elm-lang/core#568]
In comparing, say, tuples `(a,b,c)` vs. `(d,e,f)`, the natural expectation is that first `a` and `d` are compared and only if these are equal, `b` and `e` are compared, etc.

But that's not what is currently happening. That it's happening in reverse at the moment can be seen from the facts that `( True , identity ) == ( False , \x -> x )` does trigger a runtime error but `( identity , True ) == ( \x -> x , False )` doesn't.

In more realistic code it will more likely not be about runtime errors but about efficiency. But still, the natural expectation would be that `(a,b) == (c,d)` is equivalent to `a==c && b==d`, not to `b==d && a==c`.

**Comment by evancz** [comment]
This should be "fixed" by 6f5fbb8bc1ba2ce0fd3a3acf41e347c447689022.
