### ISSUE TITLE
Json decoding crashes the browser in 0.17

### ISSUE THREAD

**Issue by ccapndave** [elm-lang/core#571]
I have found a case of Json decoding which causes the browser to crash (in fact it gets stuck in an infinite loop, the fan spins up and then you have to force quit it).  This is the smallest test case I could come up with to reproduce it:

```elm
import Html exposing (text)
import Json.Decode as JD exposing (Decoder, (:=))
import Array exposing (Array)

json : String
json =
  """
  {
    "questions": [] 
  }
  """

main =
  let
    decoder : Decoder (Array String)
    decoder =
      ("questions" := JD.array JD.string)
    
    result : Result String (Array String)
    result =
      JD.decodeString decoder json
  in
  text <| toString result
```

I did some debugging, and it looks like the cause is in `https://github.com/elm-lang/core/blob/dev/src/Native/Json.js#L239` - in this case it seems that `problem.tag` is `undefined`, and so the browser gets stuck in this while loop forever.

**Comment by jvoigtlaender** [comment]
Fixing this in #573.

@evancz, relevant for 0.17 release.

**Comment by evancz** [comment]
Thanks for the report @ccapndave
