### ISSUE TITLE
Support for list multiplication like in Python

### ISSUE THREAD

**Issue by ebekebe** [elm-lang/core#580]
In Python you can write 

`2 * ['a', 'b']`

which will result in `['a', 'b', 'a', 'b']`. This is a useful operation for initializing large lists. For example, `100 * [0]` will give me a zero vector with 100 dimensions. I used this method on a regular basis in Python and would love to see it included in Elm's basics.

I propose the following implementation draft

```
(**) : Int -> List a -> List a
(**) count list =
    if count < 2
    then list
    else case list of
        []     -> []
        [a]    -> a :: ( (**) (count-1) list )
        h::t   -> append list ( (**) (count-1) list )
```

This enables a similar syntax as in python and is fit for "piping":

```
2 **  ['a', 'b']
[ 'a', 'b'] |> (**) 2
```

What do you think? Would you like to see this in Elm, too?

**Comment by jvoigtlaender** [comment]
Please read https://github.com/elm-lang/core/blob/master/CONTRIBUTING.md#adding-new-functions and follow what is said there. That is, bring this up as an issue or pull request in https://github.com/elm-community/elm-list-extra first instead.
