### ISSUE TITLE
Port Subscription Not working on initial load on 0.17

### ISSUE THREAD

**Issue by knowthen** [elm-lang/core#582]
**Background**: I was trying to pull in a JWT from localstorage using ports and I'm unable to do it on initial page load.

**Summary**: Elm Msg via port subscription, not generated on initial load, however it does work when triggered via button press

To provide a simplified example, I took the source from the [interop section](https://evancz.gitbooks.io/an-introduction-to-elm/content/interop/javascript.html) of the gitbook and slightly modified it as follows:

```elm
init : (Model, Cmd Msg)
init =
  -- (Model "" [], Cmd.none)
  (Model "" [], check "" )
```
I put a console.log into the javascript side and I can see that the handler on the js side is getting called
```javascript
app.ports.check.subscribe(function(word) {
      console.log('js subscribe fired..');
      // put some dummy data in
      // var suggestions = spellCheck(word);
      var suggestions = ["Junk", "Jump"];
      app.ports.suggestions.send(suggestions);
    });
```
however the response `app.ports.suggestions.send(suggestions);` doesn't seem to create message on the elm side.

Oddly if I click the "check" button, a message (from the subscription) is created.

Here's a repo with the code demonstrating the apparent bug: https://github.com/knowthen/portbug

![Visual Demo](https://media.giphy.com/media/l4HnMlNknycQBe7za/giphy.gif "Visual Demo")

**Comment by schnittchen** [comment]
I have the same problem here, and it sometimes works and sometimes doesn't.

I debugged around a bit and found this: Stepping into the port `send` has `subs` an empty (Elm) list here https://github.com/elm-lang/core/blob/master/src/Native/Platform.js#L547

Maybe @knowthen can confirm this observation.

**Comment by CumpsD** [comment]
Same here, `subs` is empty, working around it with `setTimeout(function(){ app.ports.jsMsgs.send(1); }, 0)` for now, then they aren't empty

**Comment by PhilippMeissner** [comment]
For the moment you might be happy using `programWithFlags` like the TodoMVC did. That's what I did as a momentarily workaround.
Here's the documentation: http://package.elm-lang.org/packages/elm-lang/html/1.0.0/Html-App#programWithFlags

Here's it in action :
https://github.com/evancz/elm-todomvc/blob/master/Todo.elm#L86
https://github.com/evancz/elm-todomvc/blob/master/index.html#L17

Hope that helps you out for the moment. Obviously this issue still needs to be looked into.

**Comment by evancz** [comment]
Going with #595 as a simpler example.
