### ISSUE TITLE
does flow support elm-html widgets?

### ISSUE THREAD

**Issue by neocris** [elm-lang/core#584]
look at this code:

```
import Html exposing (..)
import Graphics.Element exposing (..)

main =
  flow down
    [flow right
      [toElement
        0 0 (div
              []
              [ text "left" ]),
       toElement
         0 0 (div
              []
              [ text "right" ])],
     flow left
       [toElement
         0 0 (div
              []
              [ text "footer" ])]]
```
this should give a upper row with two divs followed by a another div below, but it doesn't. if we try the same structure but with, say, 'show "text"' instead of divs it works as expected. is it a bug or by design? i don't see anything on flow docs that imply it shouldn't work in both cases

**Comment by evancz** [comment]
Sorry for the slow reply. It has been busy times. All the `Graphics.*` modules have moved to `evancz/elm-graphics` so it makes sense to retarget stuff like this. In the new world, there is no way to embed HTML in Elements anymore.
