### ISSUE TITLE
Json.Decode.decodeString never succeeds when input is empty string

### ISSUE THREAD

**Issue by jinjor** [elm-lang/core#585]
For SSCCE:

```elm
import Html exposing (Html, text)
import Json.Decode as Json exposing (Decoder)

main : Html
main = text <| toString <| Json.decodeString decoder ""

decoder : Decoder String
decoder =
  Json.succeed "Succeed!"
```

This shows:
```
Err ("Unexpected end of input")
```

I ran into this problem when I used Http.post and tried to decode response (which is empty string). This issue may be related to [this issue](https://github.com/evancz/elm-http/issues/5).

**Comment by jvoigtlaender** [comment]
It was [noted on the mailing list](https://groups.google.com/d/msg/elm-discuss/P7oTdRrsDiI/YWpk1_YqAQAJ) that this is not a bug, but instead the expected behavior, since the emtpy string is not valid JSON.

**Comment by jinjor** [comment]
Ah, now I understand. Thank you.
The real problem here was "I assumed `Json.Decode.succeed` always succeeds even if given JSON is invalid", but it was wrong.

**Comment by jvoigtlaender** [comment]
I think the documentation could be more helpful, to prevent such misunderstandings. I opened https://github.com/elm-lang/core/issues/613.

**Comment by jinjor** [comment]
Seems good :)
