### ISSUE TITLE
Graphics.Element middle position can be off by one pixel due to rounding

### ISSUE THREAD

**Issue by parkermalenke** [elm-lang/core#59]
Hello,

Just started playing around with Elm and am finding it very impressive! Keep up the great work.

I noticed that in certain cases attempting to position an element in the middle of another element results in a layout that is off by a single pixel. I believe this is because [line 241](https://github.com/elm-lang/core/blob/master/src/Native/Graphics/Element.js#L241) and 236 in the source javascript are using the `bitwise or` to round towards a single pixel instead of something like `Math.round()`.

For a reproduction see this example which should draw a red rectangle with a single pixel border all the way around, but instead draws it with a 2px border at the top and left only.

```elm
import Graphics.Element (..)
import Color (red, blue)

main = spacer 99 19
  |> color red
  |> container 101 21 middle
  |> color blue
```

![screen shot 2014-12-18 at 9 00 33 pm](https://cloud.githubusercontent.com/assets/2721850/5500031/f0f4a94c-86f8-11e4-80a7-65041dabe90a.png)

On an unrelated note, I noticed P, Z, and N seem to refer to different methods of setting an axis origin for positioning. This terminology is unfamiliar to me and I would be interested to know what it refers to.

**Comment by evancz** [comment]
Sorry this did not get attention til now! The `Graphics.*` modules now live in `evancz/elm-graphics` so I am trying to get stuff migrated over there. I'm hoping this will make it easier to get help on stuff like this!
