### ISSUE TITLE
Cannot use the unit type in ports

### ISSUE THREAD

**Issue by toburger** [elm-lang/core#594]
I'm trying to migrate the code from this blog post into elm 0.17: http://tech.noredink.com/post/126978281075/walkthrough-introducing-elm-to-a-js-web-app
I've got it to work here: https://github.com/toburger/elm-todomvc/tree/feature/elm17

However it is not possible to create a port using a unit type.

When trying to compile this code:
`port dispatchDestroyCompleted : (() -> msg) -> Sub msg`
I get a runtime error saying: *_Tuple0 is not defined*

somehow unit gets transpiled into a tuple value.

When I change it to:
`port dispatchDestroyCompleted : (List Int -> msg) -> Sub msg`
everything works, but it doesn't resemble the intention of the port as clear as before.

**Comment by jvoigtlaender** [comment]
Known issue with known fix. https://github.com/elm-lang/elm-compiler/issues/1367, https://github.com/elm-lang/elm-compiler/pull/1361
