### ISSUE TITLE
Ports do not register immediate `send`

### ISSUE THREAD

**Issue by knewter** [elm-lang/core#595]
I've produced an example here: https://github.com/knewter/counter

It's actually published here: http://knewter.github.io/counter/Counter.html

If you load the page, the counter will have value 0.  The `Counter.html` file has the following code:

```javascript
var app = Elm.Main.fullscreen();
app.ports.jsMsgs.send(1);
window.app = app;
```

I mention the last bit because you can open up the browser's console, issue `app.ports.jsMsgs.send(1)`, and the counter will update.  So the inbound port works, but it doesn't work immediately.

**Comment by knowthen** [comment]
I think this is the same bug as this one: https://github.com/elm-lang/core/issues/582

**Comment by knewter** [comment]
it would appear to be the same bug.  This is a simpler case that produces the error though.  I didn't realize they were the same error before.

**Comment by roine** [comment]
As a work around I'm using something like:

    setTimeout(function(){ app.ports.jsMsgs.send(1); }, 0)

That's not pretty but it does the job.

**Comment by artisonian** [comment]
Why not use [programWithFlags](http://package.elm-lang.org/packages/elm-lang/html/1.0.0/Html-App#programWithFlags)?

**Comment by knewter** [comment]
The point is that it is a bug.  The simplified use case is here to expose it. In most cases it is entirely reasonable to use `programWithFlags` for the same solution, but that doesn't change the fact that the bug shouldn't exist!  In my use case, it's problematic to explain how ports work to people if I have to work around a bug when introducing their simplest use case (this qualifies I think)

**Comment by yoni-tock** [comment]
Yep, just hit this in our production app :(. Thanks to @lukewestby for pointing us at this bug!

**Comment by vjousse** [comment]
Same here, pretty annoying when discovering elm.
You often start by integrating it to your existing JS code with ports and you can encounter this bug pretty early in your development process.

**Comment by lukewestby** [comment]
@yoni-tock and I are going to pair on fixing this when he has some time in a couple weeks if no one can get to it earlier

**Comment by kittykatattack** [comment]
Just letting you all know I've experienced this bug too:

https://www.reddit.com/r/elm/comments/4u3icn/incoming_port_not_working/

**Comment by artisonian** [comment]
I've been looking into the issue. So far, I can tell that the app gets initialized using the scheduler (which doesn't do any work until the next turn of the event loop). I imagine three possible fixes:

- Add a way to schedule work immediately (to ensure the app is initialized in the same turn as `fullscreen`/`embed`/`worker`)
- Rearrange the work queue on the on the so that the scheduler runs initialization first
- Make initialization synchronous (which may mean bypassing the scheduler altogether, but that may cause other things to break)

**Comment by lukewestby** [comment]
What if the initialization functions accepted a callback instead of returning the application object synchronously?

```javascript
Elm.Main.fullscreen(flags, function (app) {
  app.ports.whatever.send('a string')
})
```

**Comment by evancz** [comment]
@lukewestby, I don't think we should make the API more complex. It's just a bug. It's totally possible to queue messages while things are initializing. In fact, the way I implemented the scheduler, that is exactly what I expect to be happening already. I looked into this quite some time ago and could not figure it out.

If folks want to continue discussion on this thread, please focus on exploring and sharing technical details. Obviously more people will run into this as more time passes. We do not need to record that every time it happens.

**Comment by artisonian** [comment]
@evancz @lukewestby The initial messages are being queued. I see this sequence:

- `setupOutgoingPort` and `setupIncomingPort` both execute
- `makeEmbedHelp` executes (but in the process, [enqueues the initialization code][init])
- any `send`s on that same turn of the event loop are enqueued, but `onEffects` for those ports haven't run yet, thus `subList` is empty (effectively dropping the messages)

I'll jump on `elm-dev` with questions about the scheduler, but just wanted to leave more details here.

[init]: https://github.com/elm-lang/core/blob/77bc734c0d3a939e7ea901fea0e0ec5ace58ddc3/src/Native/Platform.js#L164-L172

**Comment by yoni-tock** [comment]
@artisonian, let @lukewestby and I know what we can do to help. We were planning to dive into this next week

**Comment by wjdhamilton** [comment]
I just came across this issue whilst trying to explore ports in elm. The toy app I built to do so and is very simple so I created a repository for anyone who needs a simple example to work with: https://github.com/wjdhamilton/elm-ports-example
Note that I have not been able to make the inbound port work by calling it in the console either. This may reflect something else, but I really don't know; I'm new to Elm.

**Comment by yoni-tock** [comment]
@lukewestby and I just set up a SSCCE [here](https://github.com/lukewestby/elm-port-bootup-sscce/blob/master/README.md)

Candidate fix PR to core coming soon

**Comment by artisonian** [comment]
Cool. How did you tackle it?

BTW, I'm thinking about writing a blog post or something that walks through the internals of the scheduler. Think it's worth it?

**Comment by lukewestby** [comment]
@artisonian this is what we did: https://github.com/elm-lang/core/pull/685

YES! Definitely write that blog post!

**Comment by lukewestby** [comment]
Closing this as elm-lang/core 4.0.5 was published yesterday containing the fix

**Comment by amitu** [comment]
I am using elm-lang/core 4.0.5 and it is not fully fixed.

In `init` I return a port Cmd, and the port is this:

```javascript
app.ports.is_key_set.subscribe(function(key){
    app.ports.keyData.send([key, localStorage.getItem(key) == "true"])
})
```

If I do a `Debug.log` on `subscriptions`, it says subscribed on `keyData` before `is_key_set` is called in javascript side, yet `update` function is not called.

If I change it to:

```javascript
app.ports.is_key_set.subscribe(function(key){
    setTimeout(function(){
        app.ports.keyData.send([key, localStorage.getItem(key) == "true"])
    }, 0)
})
```

update is called.

**Comment by lukewestby** [comment]
@amitu please open a new issue and provide enough code to constitute an [SSCCE](http://sscce.org/) of the problem you're experiencing
