### ISSUE TITLE
First try at running elm make fails.

### ISSUE THREAD

**Issue by yb66** [elm-lang/core#599]
Hi,

I installed Elm on OSX 10.9.5 Mavericks yesterday using Elm Platform package installer 0.17. I thought I'd try out the [Buttons tutorial](http://guide.elm-lang.org/architecture/user_input/buttons.html) on my machine, but I got an error message:

```
$ elm make button.elm
Some new packages are needed. Here is the upgrade plan.

  Install:
    elm-lang/core 4.0.0

Do you approve of this plan? (y/n) y
Downloading elm-lang/core
Packages configured successfully!
I cannot find module 'Html'.

Module 'Main' is trying to import it.

Potential problems could be:
  * Misspelled the module name
  * Need to add a source directory or new dependency to elm-package.json
```
I found this StackOverflow answer that suggests running `elm package install evancz/elm-html`. That leads to:

`Error: Unable to find a set of packages that will work with your constraints`

The elm-package.json that was generated looks like this:

```
{
    "version": "1.0.0",
    "summary": "helpful summary of your project, less than 80 characters",
    "repository": "https://github.com/user/project.git",
    "license": "BSD3",
    "source-directories": [
        "."
    ],
    "exposed-modules": [],
    "dependencies": {
        "elm-lang/core": "4.0.0 <= v < 5.0.0",
        "evancz/elm-html": "4.0.2 <= v < 5.0.0"
    },
    "elm-version": "0.17.0 <= v < 0.18.0"
}
```

Any help, much appreciated. If this isn't the right place to open this issue please point me in the right direction.

Regards,
iain

**Comment by jvoigtlaender** [comment]
As of Elm 0.17, you need `elm package install elm-lang/html` instead of `elm package install evancz/elm-html`.

**Comment by yb66** [comment]
Thanks, but I still get an error:

```
$ elm package install elm-lang/html
To install elm-lang/html I would like to add the following
dependency to elm-package.json:

    "elm-lang/html": "1.0.0 <= v < 2.0.0"

May I add that to elm-package.json for you? (y/n) y


Error: Unable to find a set of packages that will work with your constraints.
```
Is there something else I need to do?

**Comment by jvoigtlaender** [comment]
Well, you should delete the now obsolete `evancz/elm-html` line from your `elm-package.json`, of course.
