### ISSUE TITLE
Feature request: mask with shape

### ISSUE THREAD

**Issue by thSoft** [elm-lang/core#6]
It would be great if forms could be masked with shapes, as discussed here: https://groups.google.com/d/topic/elm-discuss/WAd_Qy5xE94/discussion
Use cases include e.g. Google+-style icons, or together with transitions, even various wipes (e.g. cartoon-style circular).

**Comment by evancz** [comment]
Sorry this did not get attention til now! The `Graphics.*` modules now live in `evancz/elm-graphics` so I am trying to get stuff migrated over there.

I do not want to mess with that API too much at this point though. I expect to be focusing on `<canvas>` for professional users and "friendly graphics" for learning as separate use cases. Progress will be made when those start happening.
