### ISSUE TITLE
Elaborating the arguments to Http.request for CORS support

### ISSUE THREAD

**Issue by rehno-lindeque** [elm-lang/core#61]
With the ongoing work on `Http`, I'd like to bravely throw in a feature request for CORS support :)

The protocol for CORS is actually somewhat [involved](http://www.html5rocks.com/en/tutorials/cors/), particularly since it involves a preflight `OPTIONS` request which I believe needs to be resent after a timeout period. I think this is usually invisible to the user of most API's, it seems as though things can get tricky.

Using AngularJS's [$httpProvider](https://docs.angularjs.org/api/ng/provider/$httpProvider) and [Restangular](https://github.com/mgonto/restangular), this looks like the following:
```coffeescript
  $httpProvider.defaults.useXDomain = true
  Restangular.setDefaultHttpFields {withCredentials: true}
  Restangular.setDefaultHeaders {"Content-Type": "application/json"} # X-Requested-With header can't be used with CORS
```
While non-CORS restangular requests simply look like
```coffeescript
  Restangular.setDefaultHeaders 
  { "Content-Type": "application/json",
  , "X-Requested-With": "XMLHttpRequest"
  }
```

---

I think swapping the argument to request in the new API might also be handy.
```elm
request : String -> String -> String -> List (String, String) -> Request String
```
Since request is an elaborated version of `get`/`put`/`post`/`delete` it seems as though the primary use case is going to be adjusting the headers...
For example, for a regular ajax request, `get` might look like
```elm
get = Http.request
    [ "Content-Type": "application/json",
    , "X-Requested-With": "XMLHttpRequest"
    ]
    "GET"
```
while a CORS ajax request looks somewhat different
```elm
corsGet = Http.request
    [ "Content-Type": "application/json",
    , -- ... ?
    ]
    "GET" -- "OPTIONS" ?
```

**Comment by roobie** [comment]
Has there been no update on this issue? I am asking because I am facing similar challenges. Maybe I'm just missing something, and if so, please tell.

**Comment by jvoigtlaender** [comment]
Does http://package.elm-lang.org/packages/lukewestby/elm-http-extra/latest/ address your issues?

**Comment by evancz** [comment]
Not sure if `evancz/elm-http` or others solve this, but it's no longer a core thing.
