### ISSUE TITLE
Outgoing ports do not convert field names containing prime (single quote) properly

### ISSUE THREAD

**Issue by psfblair** [elm-lang/core#616]
I have a type alias that for various reasons that may not have been too good looked like this:

    type alias EventForServer = 
      { application'Common'Events'EventForServer: Bool
      , seqNum: Int
      , data: Json.Encode.Value 
      }

When I run tests I get 

    build/test.js:7364
    		return {application'Common'Events'EventForServer: v.application'Common'Events'EventForServer, seqNum: v.seqNum, data: v.data};
    		             ^^^^^^^^^^^^^
    
    SyntaxError: Unexpected string

The test.js code looks like this:

    var _user$project$Web_Messaging$eventsForServer = _elm_lang$core$Native_Platform.outgoingPort(
    	'eventsForServer',
    	function (v) {
    		return {application'Common'Events'EventForServer: v.application'Common'Events'EventForServer, seqNum: v.seqNum, data: v.data};
	});

It looks to me like some escaping is missing here.

**Comment by princejwesley** [comment]
Reported [here](https://github.com/elm-lang/elm-compiler/issues/1414)

**Comment by evancz** [comment]
Closing in favor of the one on the compiler repo
