### ISSUE TITLE
Json.Decode:  Uncaught TypeError: Cannot read property 'tag' of undefined

### ISSUE THREAD

**Issue by ivanceras** [elm-lang/core#618]
This will occur when decoding json with recursive data structure type.
 
```
Uncaught TypeError: Cannot read property 'tag' of undefined
```
pointing to this line of code

```js
function runHelp(decoder, value)
{
	switch (decoder.tag)
```

Here is a short [gist](https://gist.github.com/ivanceras/84e3f71f1f8f57b54e0a9c013904723b) for this issue

**Comment by jvoigtlaender** [comment]
This is a known issue, with known current workarounds. Check issue 873 at the elm-compiler repo.

**Comment by maca** [comment]
I cannot find a workaround while trying to receive some string using a port, in the most trivial example:

JS:
```  elmApp.ports.incomming.send("hello")```

Elm:
```
