### ISSUE TITLE
json parse integer 64bit timestamp

### ISSUE THREAD

**Issue by jschoch** [elm-lang/core#622]
"Expecting an Int at _.sender_map.updated but instead got: 1463343028211056000"

is there a Number type or something I can use for my decoder?

**Comment by jvoigtlaender** [comment]
Are you sure you are using version `4.0.1` of the `core` package? It contains this recent fix: https://github.com/elm-lang/core/pull/586.

**Comment by jschoch** [comment]
updated the package got

Uncaught TypeError: _NoRedInk$elm_decode_pipeline$Json_Decode_Pipeline$decode is not a function

**Comment by jvoigtlaender** [comment]
You will have to show complete example code to allow diagnosing this further. Ideally, an http://sscce.org/.

**Comment by jschoch** [comment]
i had to wipe out elm-stuff, it is working now, thanks!
