### ISSUE TITLE
String.reverse doesn't handle unicode characters properly

### ISSUE THREAD

**Issue by eoftedal** [elm-lang/core#625]
Examples from repl:

With combining unicode character (U+0300), the combining character becomes attached to the wrong character:
```
> String.reverse "màn"
"ǹam" : String 
```
With astral symbols (four byte UTF-8 character: U+1D306) it seems the surrogate pair is reversed:
```
> String.reverse "𝌆"
"��" : String
```

**Comment by eoftedal** [comment]
```
> String.length "𝌆"
2 : Int
```

**Comment by eoftedal** [comment]
Some inspiration: https://mathiasbynens.be/notes/javascript-unicode

**Comment by eoftedal** [comment]
Pull request for reversing: https://github.com/elm-lang/core/pull/627

**Comment by evancz** [comment]
Tracking in #735

**Comment by eoftedal** [comment]
@evancz In #725 you should also include the count issue from my second comment in this thread
