### ISSUE TITLE
Better error when div for embedding is undefined

### ISSUE THREAD

**Issue by hamiltop** [elm-lang/core#634]
Right now it complains that it can't call `appendChild` on `undefined`. Which makes sense, but if the intent is to treat Elm as a black box in production, then perhaps a check on the element existing and giving a clearer error would be helpful.

**Comment by noahzgordon** [comment]
This seems like a no-brainer so I went ahead and made a PR.

**Comment by evancz** [comment]
No longer lives in core. It's in virtual-dom. Not sure if it's still an issue. If so, issue on the correct repo with SSCCE is good, PR is not useful.
