### ISSUE TITLE
Json.Decode.customDecoder swallows Err strings

### ISSUE THREAD

**Issue by noahzgordon** [elm-lang/core#637]
The function `Json.Decode.customDecoder` has the following type:

`Decoder a -> (a -> Result String b) -> Decoder b`

My expectation as a user is that the decoder produced by `customDecoder` decodes an initial payload using the first argument, then maps the result into the second argument. However, when the second argument is applied and its result resolves to an `Err string`, the `string` is discarded. No matter what, when a custom decoder fails, the string value of Err is "Expecting something custom but instead got: <data>".

You can reproduce this by entering the following into elm repl:
```
import Json.Decode exposing (customDecoder, decodeString, string, (:=))

jsonString = """{ "foo": "bar" }"""

myDecoder = customDecoder ("foo" := string) (\_ -> Err "I want to see this message!")

decodeString myDecoder jsonString
-- Err "Expecting something custom but instead got: {\"foo\":\"bar\"}"
```

**Comment by evancz** [comment]
Should be fixed by  in 7f6e518378ec354681ef6337d5dfa8182b2e8fca
