### ISSUE TITLE
Is infix priority of (!) correct?

### ISSUE THREAD

**Issue by jinjor** [elm-lang/core#638]
I tired to expand the counter example to use `program` instead of `beginnerProgram`. I added empty command in `update` function, and got this error message. Is this a correct behavior?

```
-- TYPE MISMATCH ---------------------------------------------------------------

The right argument of (+) is causing a type mismatch.

25|       model + 1 ! []
                  ^^^^^^
(+) is expecting the right argument to be a:

    number

But the right argument is:

    ( number, Cmd a )

Hint: I always figure out the type of the left argument first and if it is
acceptable on its own, I assume it is "correct" in subsequent checks. So the
problem may actually be in how the left and right arguments interact.
```

I assumed `model + 1` should be evaluated first.

But it's trivial anyway. Adding a pair of parens fixes it.

**Comment by cobalamin** [comment]
Judging from http://faq.elm-community.org/operators.html, I'd say it should have a declaration of:

`infixl 1 !`

to work with everything up to and including `||`, but still be lower precedence than `|>`/`<|`.

You can declare this in your own code somewhere, which seems a bit off to me, but it works. That declaration would break as soon as (!) gets its own associativity/precedence declaration in core, though.

**Comment by evancz** [comment]
The current plan is to drop `(!)` but I agree that if it ends up in 0.19 it should have a very low precedence, possibly such that it'll work with `(|>)` chains.

**Comment by MartinKavik** [comment]
*Just note:*
Some ideas for infix operator precedence (including `!`) - https://discourse.elm-lang.org/t/infix-operators-lower-precedence-than-and/1235
