### ISSUE TITLE
`(==)` does not work correctly on records with field named `ctor`

### ISSUE THREAD

**Issue by jvoigtlaender** [elm-lang/core#652]
The current version of `core` (the current `master` branch) evaluates `{ctor = [0]} == {ctor = [0]}` to `False`.

@evancz, probably caused by the recent refactoring in https://github.com/elm-lang/core/commit/6f5fbb8bc1ba2ce0fd3a3acf41e347c447689022?

**Comment by jvoigtlaender** [comment]
Update: This now also happens with the released version `4.0.2` of `core`.

That is, the following program wrongly outputs `False`:
```elm
import Html

main = Html.text (toString ({ctor = [0]} == {ctor = [0]}))
```
while the following program continues to correctly output `True`:
```elm
import Html

main = Html.text (toString ({field = [0]} == {field = [0]}))
```

@evancz, just to let you know that the bug-fix release of `core` also introduced a bug. This one, which wasn't present in version `4.0.1`.

**Comment by evancz** [comment]
The real fix will be to reintroduce the `_` field to Elm records. This will serve as a runtime tag of whether something is an Elm record a union type *or* a JS value.

I feel like you found this by reading the new code, not by having a field with that name, so I'm not certain how urgent this is. That said, I suspect there is a stopgap fix that does not slow things down too much. Perhaps even just doing the non-pseudo-code of `ctor === ctor || eqHelp(ctor, ctor)`

**Comment by jvoigtlaender** [comment]
No, I didn't find this by reading the code. I found it by trying to run the test suite. Note that it contains this (at https://github.com/elm-lang/core/blob/master/tests/Test/Equality.elm#L22):
```elm
        , test "ctor same" <| assert ({ctor = Just 3} == {ctor = Just 3})
```
From there, I was trying whether it has something to do especially with `Just` of `Maybe`, which was not the case...

Only after that, I checked the source code to see what other special handling goes on with the `ctor` field name, and encountered this other failure, with `toString`: https://github.com/elm-lang/core/issues/654.

As an aside, it's a pity that the test suite is currently failing on GitHub.

**Comment by evancz** [comment]
I'm working on the tests. You can try sleuthing too if you'd like.

**Comment by jvoigtlaender** [comment]
I see you got the test suite passing already. A nice green batch on the repo page. Cool!

Maybe it's worth merging https://github.com/elm-lang/core/pull/655. It should pass now, given your earlier stopgap fix. And it might serve as a prophylaxis against any special casing surrounding `ctor` and equality testing creeping back in as an error at some point in the future.

Or if you think that's unlikely to become a problem again, that pull request could be simply closed.

**Comment by evancz** [comment]
Given that people in JS world get pretty intense about what color that badge is, I don't think it makes sense to check in broken tests unfortunately. I'd expect a relatively long turn-around on the `_` stopgap because it needs the compiler to change, so I would not want things to be "red" for that amount of time.

**Comment by jvoigtlaender** [comment]
If I understand correctly what you did two hours ago, the tests from https://github.com/elm-lang/core/pull/655 will not prevent the badge from being green. They were broken tests, but no longer.

**Comment by evancz** [comment]
Ah, gotcha. I thought you meant about `ctor` problems with `toString`. I started the tests again. Will merge if green. Thanks!
