### ISSUE TITLE
Json.Decode.decodeString throws runtime for types with cyclic dependencies

### ISSUE THREAD

**Issue by tiziano88** [elm-lang/core#653]
System details:

Elm Platform 0.17.0
Chrome Version 51.0.2704.103 (64-bit)
Ubuntu Linux 14.04 LTS

Error:

```
Uncaught TypeError: Cannot read property 'tag' of undefined
runHelp @ test.elm:5165
runHelp @ test.elm:5286
run @ test.elm:5157
runOnString @ test.elm:5152
A2 @ test.elm:92
(anonymous function) @ test.elm:7185
(anonymous function) @ test.elm:7220
```

Reproducible with the following example (even pasting it in http://elm-lang.org/try):

https://gist.github.com/tiziano88/7beb26152275326eb77bf9f754f14d9d

(I cut it down considerably from the original project, now it seems to be the minimal configuration that reliably causes the error)

I suspect the issue is due to the circular type dependencies, even though only two of the type involved are aliases, and the other two are actual types.

**Comment by tiziano88** [comment]
Actually, I managed to simplify the example even more; now it only contains three actual types, with a cyclic dependency between them. I am actually not sure what the expected outcome should be in this case, but definitely not a runtime error.

**Comment by tiziano88** [comment]
Turns out, even a single recursive type and associated decoder is enough (see updated Gist).

**Comment by jvoigtlaender** [comment]
See issue 873 in the elm-compiler repo, in particular also all the discussion there and in its linked references about the Json decoding special case.

**Comment by jvoigtlaender** [comment]
That is, https://github.com/elm-lang/elm-compiler/issues/873#issuecomment-220797386 (indicating how to work around this for Json decoders specially).
