### ISSUE TITLE
Undefined errors in 4.0.2

### ISSUE THREAD

**Issue by kevinbgreene** [elm-lang/core#660]
After installing 4.0.2 over 4.0.1 I started getting a series of undefined errors in the compiled JavaScript.

The first error was:

    app.js:4421 Uncaught ReferenceError: _elm_lang$core$Task$succeed is not defined

This is a just started app. It's only one file and a few lines of code. I am not using Task. However, if I import Task this error goes away and I get another:

    app.js:4552 Uncaught ReferenceError: _elm_lang$core$Process$spawn is not defined

Pinning to 4.0.1 solves my issues.

**Comment by evancz** [comment]
Can you share an http://sscce.org/ and information about your setup?

These problems seem bad, but I can't solve them with the current info. Please open a new issue with that information!

**Comment by kevinbgreene** [comment]
I was setting up a minimum project to share and show the issue and couldn't reproduce. Found deleting elm-stuff and doing a clean elm package install fixed the issue.

**Comment by evancz** [comment]
Ah, interesting. That may be some sort of caching bug with `elm-make` that happens in particular upgrade scenarios. There are some known issues on `elm-make` about mistakenly trusting the cache, so I'd expect a comprehensive fix there to cover this.

Anyway, thanks for the follow up!
