### ISSUE TITLE
Json.Decode dislikes recursion

### ISSUE THREAD

**Issue by surprisetalk** [elm-lang/core#664]
It seems that Json.Decode can't be used recursively.

Consider the following example: 
```json
[
  { "whatever": 1
  , "something": 2
  , "things": 
    [  { "whatever": 3
       , "something": 4
       , "things": []
       }
    ,  { "whatever": 5
       , "something": 6
       , "things": []
       }
    ] 
  }
]
```
```elm
decodeThings : Json.Decoder (List Thing)
decodeThings =
  Json.list decodeThing

decodeThing : Json.Decoder Thing
decodeThing =
  Json.object3 Thing
    ("whatever" := Json.int)
    ("something" := Json.int)
    ("things" := decodeThings)
```

The web console has the following complaint: `TypeError: undefined is not an object (evaluating 'decoder.tag')`.

The error seems to be occurring in `runHelp` in `https://github.com/elm-lang/core/blob/master/src/Native/Json.js`.
If you place a `console.log( decoder, value )` before `switch( decoder.tag )` in a compiled file, you'll see that the parent function doesn't pass a decoder object to the recursed child.

My current workaround (😅) is something like:
```elm
decodeThings1 : Json.Decoder (List Thing)
decodeThings1 =
  Json.list decodeThing1

decodeThing1 : Json.Decoder Thing
decodeThing1 =
  Json.object3 Thing
    ("whatever" := Json.int)
    ("something" := Json.int)
    ("things" := decodeThings2)

decodeThings2 : Json.Decoder (List Thing)
decodeThings2 =
  Json.list decodeThing2

decodeThing2 : Json.Decoder Thing
decodeThing2 =
  Json.object2 Thing
    ("whatever" := Json.int)
    ("something" := Json.int)
```

I'm willing fix this issue, but I would love some guidance on where to look!

Thank you friends.

ts

**Comment by jvoigtlaender** [comment]
This is a known compiler issue. See https://github.com/elm-lang/elm-compiler/issues/873 and the discussion there (explicitly considering JSON decoding in the comments). The current workaround is to make use of `lazy` from http://package.elm-lang.org/packages/elm-community/json-extra/1.0.0/Json-Decode-Extra#lazy.
