### ISSUE TITLE
Weird behaviour for testing equality on Dict

### ISSUE THREAD

**Issue by bzf** [elm-lang/core#669]
There seems to be something weird when testing equality on the `Dict` type.
Depending on how you construct the `Dict`, the result might vary.

Consider these values:
```elm
> foo = Dict.fromList [(1,1), (2,2)]
Dict.fromList [(1,1),(2,2)] : Dict.Dict number number'
> bar = Dict.fromList [(2,2), (1,1)]
Dict.fromList [(1,1),(2,2)] : Dict.Dict number number'
```

Since we're comparing the `Dict` I would expect that these to `Dict`s are
equal. However when trying this in the `elm-repl` that does not seem to be the
case.
```elm
> foo == bar
False : Bool
```

If we create another value `baz`, built the same way as `foo`, they will be
considered equal.
```elm
> baz = Dict.fromList [(1,1), (2,2)]
Dict.fromList [(1,1),(2,2)] : Dict.Dict number number'
> foo == baz
True : Bool
```

If I look at the documentation for [`Dict` on `core/3.0.0`](http://package.elm-lang.org/packages/elm-lang/core/3.0.0/Dict)
there is a warning that says
> Dictionary equality with (==) is unreliable and should not be used.

When reading the docs for [`Dict` on `core/4.0.3`](http://package.elm-lang.org/packages/elm-lang/core/4.0.3/Dict) it
seems to be missing. Maybe this is by mistake?

I'm running version `0.17.0` (got it by running `elm-repl --version`).

### Full session:
```sh
 λ elm-repl
---- elm repl 0.17.0 -----------------------------------------------------------
 :help for help, :exit to exit, more at <https://github.com/elm-lang/elm-repl>
--------------------------------------------------------------------------------
> import Dict
> foo = Dict.fromList [(1,1), (2,2)]
Dict.fromList [(1,1),(2,2)] : Dict.Dict number number'
> bar = Dict.fromList [(2,2), (1,1)]
Dict.fromList [(1,1),(2,2)] : Dict.Dict number number'
> foo == bar
False : Bool
> baz = Dict.fromList [(1,1), (2,2)]
Dict.fromList [(1,1),(2,2)] : Dict.Dict number number'
> foo == baz
True : Bool
```

**Comment by evancz** [comment]
What version of `core` are you using? It was fixed in 4.0.3, but is still weird before that.

**Comment by bzf** [comment]
@evancz Checking my `exact-dependencies.json` it seems to be `"elm-lang/core": "4.0.1"`. After upgrading to `4.0.3` it seems to work as expected, thanks!

**Comment by evancz** [comment]
Great, glad it's working!

**Comment by jvoigtlaender** [comment]
To be on the safe side regarding the future, I've proposed addition of the above case to the test suite: https://github.com/elm-lang/core/pull/670. There wasn't such a test yet.
