### ISSUE TITLE
Separate scale into scaleX and scaleY, and related issues

### ISSUE THREAD

**Issue by imeckler** [elm-lang/core#67]
It seems a bit arbitrary that `Form`s have separate fields for `theta`, `x`, `y`, and `scale` given that they could be wrapped in a group with an appropriate `Transform2D` (I assume this is an optimization to avoid additional levels of indirection).  Canvas supports scaling different amounts in the X and Y directions. Should forms have separate `scaleX` and `scaleY` fields? Should they just have one field which is a `Transform2D`?

**Comment by evancz** [comment]
Sorry this did not get attention til now! The `Graphics.*` modules now live in `evancz/elm-graphics` so I am trying to get stuff migrated over there. I'm hoping this will make it easier to get help on stuff like this!
