### ISSUE TITLE
Result.mapX should be Result.foldlX ?

### ISSUE THREAD

**Issue by listrophy** [elm-lang/core#675]
It seems to me that `Result.map2`, `Result.map3`, etc should actually be called `Result.foldl2`, `Result.foldl3`, etc.

As I understand it, `map` should be fully parallelizable, applying a func to items in a list without regard to the other items in the list. On the other hand, `foldl` reduces the dimensionality of the input values, often from 2 to 1.

Going further, perhaps there should be a `Result.foldl` with the type signature: `foldl : (a -> value -> value) -> value -> List (Result x a) -> Result x value`

*NB:* Forgive my inexperience in the FP world... this issue is coming from my experience as an OO programmer. For example, I nearly submitted this issue with `reduce` rather than `foldl`. 😀

**Comment by jvoigtlaender** [comment]
If you want to discuss this, please bring it up in a community forum, for example the mailing list. Various options/channels are listed here: http://elm-lang.org/community.

This issue tracker here is not meant for such questions on API design and function names. It is really almost exclusively meant for bug reports.
