### ISSUE TITLE
String.reverse works incorrectly for strings with combining diaeresis

### ISSUE THREAD

**Issue by alech** [elm-lang/core#676]
While looking at the Elixir Getting Started guide, I stumbled upon this interesting blog post called [The string type is broken](https://mortoray.com/2013/11/27/the-string-type-is-broken/). One example is reversing the String "noël", which should result in "lëon". Unfortunately, elm 0.17.1 fails this test, putting the diaresis over the l instead of over the e:
 
> s = "noe\x0308l"
"noël" : String
> String.reverse s
"l̈eon" : String

**Comment by ckoster22** [comment]
This looks to be a duplicate of #625

**Comment by jvoigtlaender** [comment]
Indeed, it does.
