### ISSUE TITLE
Recursive types cause runtime exception while decoding json.

### ISSUE THREAD

**Issue by maxgurewitz** [elm-lang/core#677]
I'm getting a runtime exception while decoding json to a recursively defined type.  My use case is that I'm implementing a web app with nested comments, which I'm defining with recursive types.  Make sure to open your developer console while running the provided example.

- SSCCEE (example of bug):  https://gist.github.com/maxgurewitz/dd5a8b4d1a0e30c42905c728abc22e07
- elm-make 0.17 (Elm Platform 0.17.0)
- OSX: 10.11.4
- chrome: 51.0.2704.103

Please let me know if there's anything else I can do to help debug.

**Comment by jvoigtlaender** [comment]
Closing as duplicate, for example of #664.
