### ISSUE TITLE
Remove Color module

### ISSUE THREAD

**Issue by Skinney** [elm-lang/core#681]
`Color` is the only UI related module in core. All other UI related modules are their own package. I propose to remove `Color` from this project, and instead place it in its own package.

**Comment by evancz** [comment]
Who is it hurting? Seems pretty valuable to have a single color type across the whole language.

**Comment by Skinney** [comment]
Not hurting anyone, it just seems out of place. It's also valuable to have a single HTML/VDOM type across the whole language, yet it is not in core. I don't want to create a big deal out of this, I created the issue because I read through the documentation and thought: "Color? Is that a core thing?" My views can be colored (heh) by the fact that I've yet to find any use for the module.

**Comment by evancz** [comment]
Don't want to track this here. Good conversation for elm-discuss or the Slack channel though. Can revisit later.
