### ISSUE TITLE
Upgrade from elm core 4.0.2 to 4.0.4 breaks Ports

### ISSUE THREAD

**Issue by cscalfani** [elm-lang/core#683]
I now need to import Json.Decode and Json.Encode for my port module. If omitted, the compiler doesn't produce an error. Instead I get the dreaded Runtime Error:

`ReferenceError: _elm_lang$core$Json_Decode$string is not defined`

**Comment by evancz** [comment]
Include an http://sscce.org/

**Comment by cscalfani** [comment]
Okay, so I realized that the problem had to do with how I was building the app. Not sure why an upgrade to 4.0.4 changed the behavior that was working just fine all last week. Don't really care because I've changed my build process.

Sorry for the false alarm.

**Comment by evancz** [comment]
No worries, glad it is working again!

(It may have been about assets getting stuck in `elm-stuff/build-artifacts/` which will get fixed via some elm-make improvements.)
