### ISSUE TITLE
Uncaught TypeError if Json.Decode is not imported (module loading order problem?)

### ISSUE THREAD

**Issue by RobertWalter83** [elm-lang/core#686]
I experience an issue which might be related to [#683](https://github.com/elm-lang/core/issues/683).

I created a [SSCCE ](https://github.com/RobertWalter83/sscce-elm-ports-uncaughtError)to illustrate the problem.

Im working on Windows 10. I use Elm 0.17.1, core 4.0.3.

Description:
I have a port module where I have defined all my app's ports. If this module does not import "Json.Decode", I get an Uncaught TypeError exception:
![ex](https://cloud.githubusercontent.com/assets/5462981/17515855/3227b8b2-5e3b-11e6-926a-14edbe9fe12b.png)

I am aware of [this discussion](https://groups.google.com/forum/#!topic/elm-discuss/Zs5LFb_Ei_4). I do not use elm-webpack-loader.

**Comment by lukewestby** [comment]
It appears that the presence of a port module alone doesn't inform the compiler of the need to import `Json.Decode`. Moving the line `import Ports exposing (..)` below the `Html` imports fixes the issue as the `Html` modules import `Json.Decode` internally. Here's a succinct SSCCE for which you can examine the generated code and note the absence of `Json.Decode`

```elm
port module Main exposing (..)

port example : (String -> msg) -> Sub msg

value =
    1
```

**Comment by evancz** [comment]
@lukewestby, feel free to close issues and open nicer ones if you figure things out like this! I did this with #703.

**Comment by lzrski** [comment]
Also running into this issue with React Native talking to Elm program via ports. The error is

```
Can't find variable _elm_lang$core$Json_Decode$string
```

Adding `import Json.Decode` solves the problem. See [relevant code here](https://github.com/lzrski/elm-react-native-playground/blob/4730bcc975e65f9cf1dea8a23f937dea13c1722a/Main.elm#L4).
