### ISSUE TITLE
Date.month crash with dates in the distant future

### ISSUE THREAD

**Issue by MrMovl** [elm-lang/core#690]
If you manage to get an invalid date like `Date.fromTime 10000000000000000`, everything works until you try something like `notADate |> Date.month |> toString |> Html.text`. Then you get the runtime Error `Uncaught TypeError: Cannot read property 'substring' of undefined` It's the same for Date.dayOfWeek.

This seems unlikely, but you can reach that pretty quick when extrapolating Dates. Not sure if this can be fixed with the Date.month function. Maybe the problem could be solved if Date.fromTime would behave like Date.fromString and yield a _Result_ or a _Maybe_.

Can be reproduced with the following on http://elm-lang.org/examples/hello-html

> import Html 
> import Date
> 
> main =
>   let
>     notAMonth = Date.fromTime 10000000000000000 |> Date.month
>   in
>     notAMonth |> toString |> Html.text

**Comment by kuzux** [comment]
Just managed to reproduce the crash using `Date.fromTime 10000000000000000 |> Date.month` in repl

**Comment by lukewestby** [comment]
Tracking in #816
