### ISSUE TITLE
Relocate or redirect `sleep` function?

### ISSUE THREAD

**Issue by jvoigtlaender** [elm-lang/core#693]
Currently it exists as
```elm
Process.sleep : Time -> Task x ()
```
It's not obvious to find there:
* [A user was looking for this functionality but could not find it.](https://groups.google.com/d/msg/elm-discuss/g1Z21XEDWYs/CFiS_GmABgAJ)
* [The same user would have found it if it had lived in the `Time` or `Task` modules.](https://github.com/elm-lang/core/issues/692#issuecomment-240375350)

Other considerations:
* [In the .NET world, this functionality is known as `Task.Delay`.](https://msdn.microsoft.com/en-us/library/hh139096(v=vs.110).aspx)
* The rest of the `Process` module is about processes created with, or possessing, a `ProcessId`, but `sleep` does not take one of those.
* The documentation of the function says that "progress on the current process" is blocked. It's not very clear what that "current process" is if the user has not `spawn`ed their own process. What would probably be clearer would be to say that the "process the task returned by that function is running in" is blocked. Which amounts to saying that "the task returned by this function" sleeps for a while. No need to bring "process" into the picture. That's an argument for this being a better fit for the `Task` module.
* Nowhere in the current documentation is it said that when a `Task` is performed it becomes a little process. Specifically, neither the [documentation page for `Task`](http://package.elm-lang.org/packages/elm-lang/core/4.0.5/Task), nor the [guide's page on tasks](http://guide.elm-lang.org/error_handling/task.html) linked from there contain the word "process" even once. So how could a user who wants to add a delay in a task chain ever guess that the `Process` module is relevant (i.e., that they may find the sought functionality there)?

My proposal is to move this function to the `Task` module:
```elm
Task.sleep : Time -> Task x ()
```

Secondary proposals could be to not relocate it, but use redirections instead:
* defining `Task.sleep = Process.sleep`
* and/or `Time.sleep = Process.sleep`

But I don't think having the function live in different modules is necessary. Why would a user who knows they are looking for a function of type `Time -> Task x ()` be able to find it in module `Time` and/or in module `Process`, but not in module `Task`? The functionality is clearly "time"- and "task"-related, but not so obviously "process"-related.

**Comment by evancz** [comment]
Added to #322
