### ISSUE TITLE
NonEmptyString type to handle empty string cases in the code

### ISSUE THREAD

**Issue by ondrejsevcik** [elm-lang/core#697]
Hi, sometimes I have to treat an empty string as an invalid state (e.g. in Username) and in those cases, I have to check for all occurrences in my code and make sure that there is proper check for an empty string value.

It would be really great if the compiler could do all the checks for me. I thought about `NonEmptyString` type that would always contain some characters.

```
username : NonEmptyString
username = "Donald Duck" -- valid
username = "" -- compile error
```

then I could define my `username` to `Maybe NonEmptyString` and the compiler will make sure that all the cases are handled in my code.  

```
username : Maybe NonEmptyString
username = Just "Donald Duck"

...

case username of 
    Just username ->
        ...
    Nothing ->
        ...
```

What do you think about it? 
How do you currently solve this issue in your code?

**Comment by evancz** [comment]
I think it makes sense to do more discussion on Elm Slack or elm-discuss before having an issue here about it.

I often use languages with a `NonEmptyList` type and it's never been worth the trouble in my experience. I.e. I've never had a bug related to doing this wrong.

One way to handle your case is to make a special type:

```elm
type UserName = Known String | Unknown

user : String -> Result String UserName
```

And you can have the `user` function check that everything is valid. If the internal details of `User` are hidden, no one on the outside can ever modify the name, so you know that all `User` data is good and only have to check once.
