### ISSUE TITLE
Off by a day

### ISSUE THREAD

**Issue by ChetHarrison** [elm-lang/core#698]
I am not sure if this is timezone related, I am in California, but here is some input/output from my repl. I requested the 13th and got the 12th.

```
> Date.fromString "1969-11-13"
Ok <Wed Nov 12 1969 16:00:00 GMT-0800 (PST)> : Result.Result String Date.Date
```

**Comment by altaic** [comment]
It is timezone related. Notice the part "16:00:00 GMT-0800 (PST)" and add the time and offset for GMT-- you get midnight on the 13th.

**Comment by ChetHarrison** [comment]
k great. Thanks for the clarification!
