### ISSUE TITLE
Should String/Array.slice accept 0 as an end argument

### ISSUE THREAD

**Issue by dannyob** [elm-lang/core#699]
It seems very weird that you can easily slice from the start of a String or Array, but not to its end:
```elm

> String.slice 0 3 "Hello"
"Hel" : String

> String.slice 0 -1 "Hello"
"ell" : String

> String.slice -3 -1 "Hello"
"ll" : String

-- But how do we get "lo"?
> String.slice -2 0 "Hello"
"" : String
```
I think this is a side effect of Elm borrowing from Python -- Python slice indices can be negative, but they can also be None, which indicates either the start or the end of the list, depending on where they are used.

Conceivably we could use 0 as an end argument for this function, just as 0 as a start argument means "before the start." But it's all feeling a bit like null values here...

It feels like @sindikat might have some thoughts on this...

**Comment by andreaazzini** [comment]
The `slice` functions behave exactly like their Javascript counterparts. IMHO, it wouldn't be _right_ to make the Elm `slice` work differently. You can (and probably should) use the `String.right` function in this specific case.

```elm
> String.right 2 "Hello"
"lo" : String
```

However, the `right` function is not available in the `Array` module. Maybe we should discuss how to avoid this specific asymmetry.

**Comment by evancz** [comment]
Added to #322 that tracks all these ideas in one place. That way we can try to make more coherent API choices so things match across all core libraries.
