### ISSUE TITLE
Cannot find variable ..- when creating negative ranges

### ISSUE THREAD

**Issue by hendore** [elm-lang/core#705]
When creating a list with a range of numbers I came across an issue if the "high" number is negative and there isn't a space between range operator and "high" number.

Pasted some example output of the issue.

```
> [0..5]
[0,1,2,3,4,5] : List number
>
> [-5..0]
[-5,-4,-3,-2,-1,0] : List number
>
> [-10..-5]
-- NAMING ERROR ---------------------------------------------- repl-temp-000.elm

Cannot find variable `..-`

3|   [-10..-5]
      ^^^^^^^
Maybe you want one of the following?

    -
    Basics.-


> [-10 .. -5]
[-10,-9,-8,-7,-6,-5] : List number
```

**Comment by lukewestby** [comment]
@hendore can you reopen this on elm-lang/elm-compiler? this would be something to address in the parser

**Comment by hendore** [comment]
@lukewestby Done, thank you very much for the clarification.
