### ISSUE TITLE
Runtime error from `String.indices ""`

### ISSUE THREAD

**Issue by jvoigtlaender** [elm-lang/core#708]
This program:
```elm
import Html
import String

main = Html.text <| toString <| String.indices "" "Goodbye, Cruel World!"
```
leads (on current http://elm-lang.org/try) to an "out of memory" JS error.

**Comment by jvoigtlaender** [comment]
@lorenzo says this is fixed. On http://elm-lang.org/try it still happens.

**Comment by lorenzo** [comment]
Yeah, it was fixed here https://github.com/elm-lang/core/pull/646
