### ISSUE TITLE
Provide a way to update arbitrary properties

### ISSUE THREAD

**Issue by Fresheyeball** [elm-lang/core#714]
Consider a scenario where we wish to update the `scrollTop` property on a Node. At the moment, I have to do this with `port`s and hack around querying because there is no post render hook. Its not ideal given that the data being sent is simple view logic, and views cannot issues `Cmd`. As it stands `Attribute` works well for properties exposed as attributes in the Html api, but it could as well update any arbitrary property.

Proposition for this use-case

```elm
import Html.Attributes as Attr

container at = div [ Attr.class "container", Attr.scrollTop "300px" ] [ text "wowzers" ]
```

Since the raw `attribute` function takes 2 strings, it could be possible to update any arbitrary property via 'stringly typed match'.

**Comment by lukewestby** [comment]
`Html.Attributes.property` will do this if you want

```elm
Html.Attributes.property "scrollTop" (Json.Encode.int 300)
```

You would just need to be careful with things like `scrollTop` on the first render since nothing will be in the DOM and setting `scrollTop` doesn't have any effect until the element is actually inserted.

**Comment by Fresheyeball** [comment]
Damn, how the heck did I miss that.

**Comment by lukewestby** [comment]
I forget about it all the time too, it doesn't come up super often since the built-in attribute stuff covers most use cases 😃

**Comment by evancz** [comment]
Should be done with [this](http://package.elm-lang.org/packages/elm-lang/dom/1.1.0/Dom-Scroll#toY) instead though.

**Comment by Fresheyeball** [comment]
Dom querying really?
