### ISSUE TITLE
String.startsWith returns True for an empty substring

### ISSUE THREAD

**Issue by Shemeikka** [elm-lang/core#717]
Hi,

I noticed that String.startsWith returns True for an empty substring

    > String.startsWith "" "Hello"
    True : Bool

Shouldn't this be False?

Chrome 53
Windows 10
Elm 0.17.1

**Comment by simonewebdesign** [comment]
I think it's correct, ES2015 has the same behavior:

``` javascript
"Hello".startsWith("")
=> true
```

**Comment by Shemeikka** [comment]
Yeah,

So it seems. In fact, this seems to be same in every language. 

I have to say that this is against my logic even after reading the reasons for this behavior.

I think this issue can now be closed..
