### ISSUE TITLE
Compilation should fail when constant is defined as itself

### ISSUE THREAD

**Issue by ondrejsevcik** [elm-lang/core#726]
Hi, take a look at the following code
```
import Html exposing (text)

status =
  status

main =
  text <| toString status
```

is it ok that it's possible to compile a program like this? I had a bug like this in my app and it was a bit hard to find where the error is since the compiler didn't warn me.

**Comment by jvoigtlaender** [comment]
This is tracked in https://github.com/elm-lang/elm-compiler/issues/873.
