### ISSUE TITLE
Dict.insert returns misleading error when 2 arguments instead of 3 are passed

### ISSUE THREAD

**Issue by kkruups** [elm-lang/core#733]
----------------------------------------------
**Issue**
----------------------------------------------

_Dict.insert: comparable -> a -> Dict comparable a -> Dict comparable a_

When sending **Dict.insert** two arguments, a tuple and Dict, instead of three, the error message is misleading.  Note the tuple has the same shape as the entries in the Dict

**With Dict.insert  using 2 arguments** 

*This doesn't work:*  

`Dict.insert ("C", vnfC) vnfDict       (only two args)
`
(where **vnfC = {veg:"Calaloo", fruit:"Cranberry"}** 

and 

**vnfDict** is Dict with two entries:   

Dict.fromList 
`[("A",{ veg = "Artichoke", fruit = "Apple" }),("B",{ veg = "Artichoke", fruit = "Apple" })] : Dict.Dict String Repl.VegnFruit.)`
`

----------------------------------------------
**Expected Behavior**
----------------------------------------------
One of the following 

Either
**1. Indicate missing argument error message** 

or 

**2.Add the entry into Dict if it has same shape as entries of Dict.** 
----------------------------------------------

----------------------------------------------
**Error Message Indicated* ( when executing with Dict.insert with 2 Args):**
----------------------------------------------

`Dict.insert ("C", vnfC) vnfDict
`
**STARTOF ERR MSG  --------------------------**

-- TYPE MISMATCH --------------------------------------------- repl-temp-000.elm

The 1st argument to function `insert` is causing a mismatch.

6|   Dict.insert ("C", vnfC) vnfDict
                ^^^^^^^^^^^
Function `insert` is expecting the 1st argument to be:

   ( String, VegnFruit )

But it is:

   ( String, VegnFruit )

Hint: Only ints, floats, chars, strings, lists, and tuples are comparable.`

**END OF ERR MSG  --------------------------**

----------------------------------------------
**With Dict.insert using 3 arguments:**
----------------------------------------------
*This works:* `

`Dict.insert "C" vnfC vnfDict`  

**Result:**
Dict.fromList  **[("A",{ veg = "Artichoke", fruit = "Apple" }),("B",{ veg = "Artichoke", fruit = "Apple" }),("C",{ veg = "Calaloo", fruit = "Cranberry" })]**
   : Dict.Dict String Repl.VegnFruit    

----------------------------------------------

**Comment by mgold** [comment]
It's fine to pass two arguments to `Dict.insert`; you just get back a function. Here's an SSCCE:

```
import Dict

Dict.insert ("C", Nothing) Dict.empty
```

This produces (0.17, 0.18)
```
-- TYPE MISMATCH ---------------------------------------------

The 1st argument to function `insert` is causing a mismatch.

4|   Dict.insert ("C", Nothing) Dict.empty
                 ^^^^^^^^^^^^^^
Function `insert` is expecting the 1st argument to be:

    ( String, Maybe a )

But it is:

    ( String, Maybe a )

Hint: Only ints, floats, chars, strings, lists, and tuples are comparable.
```

The "expected first argument" is shown to be the same as the "but it is", which is a pretty bad error message. The problem with this code is that `Nothing` is not comparable, and therefore the tuple is not an acceptable key. I'd guess the root cause has something to do with how `comparable` types are handled. The error is reasonable if you try `Dict.insert Nothing Dict.empty`.

The best place for this is likely the [error message catalog](https://github.com/elm-lang/error-message-catalog/issues/new).

**Comment by jvoigtlaender** [comment]
Yes, this belongs on the error message catalog, not here.
