### ISSUE TITLE
0.18: documentation for Basics.never not in line with rest of API

### ISSUE THREAD

**Issue by jvoigtlaender** [elm-lang/core#744]
The documentation currently makes use of this piece of code:
```elm
getTime : Cmd Msg
getTime =
  Task.perform never CurrentTime Time.now
```
But the actual type of `Task.perform` in this version of `core` is:
```
Task.perform : (a -> msg) -> Task Never a -> Cmd msg
```
That does not fit.

Aside: The documentation of the `never` function as originally in `elm-community/basics-extra` is here: http://package.elm-lang.org/packages/elm-community/basics-extra/1.2.0/Basics-Extra#never. But it also cannot be used as is, since it mentions `Task.perform` as well.

**Comment by evancz** [comment]
Fixed in that patch. Thanks for pointing this out!

**Comment by gdennie** [comment]
The Elm Guide refers to the attribute function, `type_`, which no longer exist and is now, `type'`, instead.

Separately, is there a good place to locate quality documentation on the latest version of elm: 0.18.x?
