### ISSUE TITLE
0.18: Have `Tuple` as part of default imports?

### ISSUE THREAD

**Issue by jvoigtlaender** [elm-lang/core#745]
Like `List`, `Maybe` etc. It seems odd and inconsistent with those cases that one explicitly has to write `import Tuple` to be able to use `Tuple.first` (whereas e.g. `List.reverse` can be used without writing `import List`).

**Comment by jtojnar** [comment]
That should probably go to [elm-compiler](https://github.com/elm-lang/elm-compiler/blob/4f5db922692099010a1cc5c987ce3cc536cf0140/src/Elm/Compiler/Imports.hs#L14).

**Comment by jvoigtlaender** [comment]
Not really. Look at the README of this repository here. That's where the decisions about what are default imports are recorded. And also this here is the repository where the decision was made to move certain functions from the `Basics` module to the `Tuple` module.

To not derail the discussion here, I'll remove both your comment above and this my response to it.

**Comment by evancz** [comment]
Yeah, I was thinking about that. I'd prefer to have this discussion on elm-dev and get feedback deeper than +1 from folks. Perhaps there are no downsides, but I'd like to see folks try to think of them at least!
