### ISSUE TITLE
support parallelism with multi-threaded model

### ISSUE THREAD

**Issue by abnud1** [elm-lang/core#751]
Right now core have Tasks and Processes which support concurrency (interleaving) but not parallelism.  

Given that JS developers have web workers, I think elm should have an API for multithreading.  

I know that web workers only got supported recently and shared web workers are still not supported in IE/Edge and Safari but this shouldn't stop Elm from adding parallelism.  

If not via multithreading then some other model for parallelism ?

**Comment by jvoigtlaender** [comment]
Questions/discussion like this are not the purpose if this issue tracker. Please ask on the mailing list instead. 

http://elm-lang.org/community
