### ISSUE TITLE
Broken link on Signal docs

### ISSUE THREAD

**Issue by yigitozkavci** [elm-lang/core#753]
In the [Signal docs](http://package.elm-lang.org/packages/elm-lang/core/2.1.0/Signal) there is the warning stating:
```
Warning! The latest version of this package is 5.0.0
```
And when we click [this url](http://package.elm-lang.org/packages/elm-lang/core/latest/Signal), we have this error in link:
```
problem with parameter 'version': Must have format MAJOR.MINOR.PATCH (e.g. 1.0.2)
```
Since we don't have Signals anymore, I think that warning shouldn't appear on top of the page.

**Comment by yigitozkavci** [comment]
Problem also exists on [Html.App docs](http://package.elm-lang.org/packages/elm-lang/html/1.0.0/Html-App)

**Comment by jvoigtlaender** [comment]
This is a problem with the package site, not the library here. 

Can you please reopen at the package site's repository?

**Comment by evancz** [comment]
It is also already reported there https://github.com/elm-lang/package.elm-lang.org/issues/195

**Comment by yigitozkavci** [comment]
Oh my bad, then I'll leave a comment on that issue, thanks :)
