### ISSUE TITLE
suspicious code in Array

### ISSUE THREAD

**Issue by wishfoundry** [elm-lang/core#754]
I noticed this line
```javascript
var slot = new createNode(a.height - 1, 0);
```
in:
https://github.com/elm-lang/core/blob/master/src/Native/Array.js#L730

createNode() is the factory here, it should not be new'ed up itself

I'm entirely sure where this will manifest though. If the being appended are balanced it probably can't reach this code.

**Comment by wishfoundry** [comment]
actually this looks like the source of the problem in #474

**Comment by turboMaCk** [comment]
+1

**Comment by mgold** [comment]
Great detective work, but it won't be needed: there's a [fully-Elm version of Array](https://groups.google.com/forum/#!topic/elm-discuss/aAMVveQAG8c) in the final stages of testing.

**Comment by evancz** [comment]
I'm interested in this fix in the meantime. That new stuff needs a performance review, and if this is an easy fix, it won't hurt!

So can someone do a PR with the change and a test that demonstrates what it fixes?

**Comment by lukewestby** [comment]
@wishfoundry how did you demonstrate that this is the cause of the issue in #474? i'm setting a breakpoint at that line while running the examples from that issue and the line in question isn't being reached.

while the use of `new` is semantically incorrect here, it doesn't change the behavior of pure functions like `createNode`.

<img width="305" alt="screen shot 2016-11-29 at 6 51 24 pm" src="https://cloud.githubusercontent.com/assets/1508245/20735319/edbc2e7e-b664-11e6-9fab-6a7e43e2400a.png">

**Comment by wishfoundry** [comment]
@lukewestby newing up a function can prevent it from returning a value:

<img width="256" alt="screen shot 2016-11-29 at 9 26 31 pm" src="https://cloud.githubusercontent.com/assets/818080/20740912/afd6088e-b67b-11e6-92fe-2ea8d6f74ad1.png">

I discovered the bug while attempting to port the rrb code to plain js, during a battery of performance comps against other immutable libs.
The rrb version would fail on any tests with lengths > 32, < 1024. I removed the "new", and they ran again. but I'm still a little unclear the exact reason. but if there is still a future in the current Array code, I'll update here as soon as I get a few moment to rerun them

**Comment by wishfoundry** [comment]
Finally got it. the issue has to do with the final balancing act done in:

https://github.com/elm-lang/core/blob/master/src/Native/Array.js#L644

assumes that both are never leaves, which isn't always true due to RRBs unbalanced nature. We just need to add a ```node.height != 0``` check in here. (PR to follow)

**Comment by wishfoundry** [comment]
after looking further through this code, I've come to realize it too many issues to quickly repair.

I'm going to see if I can help out with the new HAMT version instead of working on this.
