### ISSUE TITLE
"Just" doesn't make sense to me as the counterpart to Nothing. Rename to Just to Something?

### ISSUE THREAD

**Issue by willnwhite** [elm-lang/core#756]
I remember thinking "Just" was weird. It hinted to me that it was doing something other than just being the counterpart to Nothing. It still sounds weird to me when I hear it being explained to others. "Something" (as in the phrase "something or nothing") makes more sense to me as a counterpart to Nothing. Could we rename Maybe.Just to Maybe.Something?

**Comment by jvoigtlaender** [comment]
Please place such discussions on the mailing list instead.

**Comment by willnwhite** [comment]
Sorry, forgot. Will do. Is there reasoning behind this I can read?

**Comment by jvoigtlaender** [comment]
Reasoning behind what?

**Comment by willnwhite** [comment]
Sorry, reasoning behind have to discuss on Google Groups rather than here.

**Comment by jvoigtlaender** [comment]
There are three links in process-bot's message above that point to documents detailing Evan's preferred work mode. They don't contain much reasoning, I think. But there's this talk of his on collaboration: https://www.youtube.com/watch?v=DSjbTC-hvqQ&list=PLglJM3BYAMPH2zuz1nbKHQyeawE4SN0Cd&index=1

Beyond that, you would probably have to ask on the mailing list. :smile:
