### ISSUE TITLE
0.18 should keep Task.fromResult

### ISSUE THREAD

**Issue by benpence** [elm-lang/core#760]
I think this is a pretty useful function that @evancz got rid of in 9a1dec5cdd742842feaff427b4e4e3ab05dfb7e6 for 0.18. It's not particularly hard for me to implement, which is why I advocate for keeping it, since I expect most developers will write their own and now we've added a _pinch_ more maintenance/bug surface for everyone.

Is there any discussion on similar topics? I'm generally pro- functions & "point free notation" over pattern matching in cases like this, but can be persuaded.

**Comment by jvoigtlaender** [comment]
This is a discussion to be had on the mailing list.
