### ISSUE TITLE
Cryptic Error message: elm-make: Map.!: given key is not an element in the map

### ISSUE THREAD

**Issue by dimus** [elm-lang/core#761]
Elm 0.18, OS Ubuntu 16.04, using docker ([Dockerfile](https://github.com/GlobalNamesArchitecture/gn_crossmap_web/blob/689b00671f305ae5f42f1aa3c46d3f22188485f7/Dockerfile), [docker-compose.yml](https://github.com/GlobalNamesArchitecture/gn_crossmap_web/blob/689b00671f305ae5f42f1aa3c46d3f22188485f7/docker-compose.yml))
A cryptic error message `elm-make: Map.!: given key is not an element in the map` started to appear during compilation. Incidentally, it started to happen after I installed `elm-lang/http` package. Deleting `elm-stuff` and recompiling fixed the problem.

Sadly I do not know how to reproduce this bug, but it looks like it happened to [others](https://groups.google.com/forum/#!topic/elm-discuss/cN0GFZpw_b0) as well.

**Comment by hojberg** [comment]
I've heard this was if there were 0.17 things sitting around in elm-stuff for some reason. Deleting elm-stuff worked for me too.

**Comment by jvoigtlaender** [comment]
Even if there is more to this than an 0.17-to-0.18-upgrade issue, it seems to belong in the https://github.com/elm-lang/elm-compiler repo, not here.  

Thus, I'm closing the issue here.
