### ISSUE TITLE
Include full message in rhs of debug pane

### ISSUE THREAD

**Issue by simonh1000** [elm-lang/core#763]
My messages are rather nested and thus cannot be read in the space available. It would be great if, after clicking on a message in the left hand side, that the full message was placed above the model on the right hand side where there is more room to read it all
 
![screen shot 2016-11-29 at 18 00 39](https://cloud.githubusercontent.com/assets/5256724/20719930/c38be31c-b65d-11e6-9e04-98441a78997f.png)

**Comment by rtfeldman** [comment]
@simonh1000 The debugger is actually housed in https://github.com/elm-lang/virtual-dom/issues - would you mind closing this and re-posting there?
