### ISSUE TITLE
Curious why foldl in haskell has a different type than elm.

### ISSUE THREAD

**Issue by MrRacoon** [elm-lang/core#764]
In **[elm](http://package.elm-lang.org/packages/elm-lang/core/latest/List#foldl)** (5.0.0):
```
foldl : (a -> b -> b) -> b -> List a -> b
foldr : (a -> b -> b) -> b -> List a -> b
```

In **[haskell](http://hackage.haskell.org/package/base-4.9.0.0/docs/Data-Foldable.html#v:foldl)**:
```
foldl :: Foldable t => (b -> a -> b) -> b -> t a -> b
foldr :: Foldable t => (a -> b -> b) -> b -> t a -> b
```

notice the arguments of the function given to foldl seem to be backwards. Is that intended?

**Comment by MrRacoon** [comment]
oh interesting, just saw this: https://github.com/elm-lang/elm-compiler/issues/346

**Comment by evancz** [comment]
Yep, that's the reasoning! This way you can write functions such that "The data structure is always last" and it works nice with folds. The direction of your fold shouldn't require a refactor IMO.

**Comment by MrRacoon** [comment]
Does this image still apply to elm?
![](http://image.slidesharecdn.com/fp-by-examples-130723041014-phpapp01/95/functional-programming-by-examples-using-haskell-28-638.jpg?cb=1374552694)

**Comment by evancz** [comment]
I think it'd be better to talk about this more on the Slack or on elm-discuss.

**Comment by MrRacoon** [comment]
Aye!
