### ISSUE TITLE
Array.map2

### ISSUE THREAD

**Issue by miniBill** [elm-lang/core#767]
Can we get an `Array.map2` function?
The signature would be `(a -> b -> c) -> Array a -> Array b -> Array c`

**Comment by rtfeldman** [comment]
@miniBill This exists in http://package.elm-lang.org/packages/elm-community/array-extra/1.0.2/Array-Extra#map2 - so you can use it right now!

Whether it should be in `core` is a separate question, but there's a general notion of "go through community `-extra` packages and see if it makes sense to bring things into `core`" from time to time, so I don't think we need a separate issue to track this particular one as a special case. 🙂
