### ISSUE TITLE
[Proposition] Add unfolds for types.

### ISSUE THREAD

**Issue by Heimdell** [elm-lang/core#773]
I tried to code some isometric landscape generator (using svg) lately, and I got a task to solve: generate list of points `(Int, Int)`.

The `core.List` module only contained `List.range : Int -> Int -> List Int` method. And no `unfoldr` or alike.
So I had to break my stream of thinking of things I want to do and implemented it myself.

My proposition: add `unfold{r,l,}` for any module describing "sequental container" types like `List`, `Maybe`, etc.

For instance, `List.unfoldr : (seed -> Maybe (a, seed)) -> seed -> List a`.

**Comment by jvoigtlaender** [comment]
Please make such suggestions on the mailing list, not here. Also see what the links from process-bot have to say on this.
