### ISSUE TITLE
Array issue

### ISSUE THREAD

**Issue by wearsunscreen** [elm-lang/core#775]
**I found this Array issue. It should be linked with #649.** 

The first and third elements should be identical, but `g` changes when `concatGrid g` is evaluated.

 ```elm 
 results =
            [ getRow 0 (setColorInGrid ( 0, 0 ) 99 (Debug.log "before" g))
                == [ 99, 4, 2, 4 ]
            , concatGrid g == concatenated
            , getRow 0 (setColorInGrid ( 0, 0 ) 99 (Debug.log "after" g))
                == [ 99, 4, 2, 4 ]
            ]
```

Full code is attached. Happens on v 0.18, Firefox and Chrome. 
[GridA.elm.txt](https://github.com/elm-lang/core/files/631529/GridA.elm.txt)

**Comment by jvoigtlaender** [comment]
Isn't it already covered by https://github.com/elm-lang/core/issues/649?
