### ISSUE TITLE
Can't set gitlab repository in elm-package.json

### ISSUE THREAD

**Issue by diugalde** [elm-lang/core#777]
My elm-package.json looks like:

```
{
    ....
    "repository": "https://gitlab.com/org/name.git",
    ....
}
```
I get the following message:

```
Error: The description in elm-package.json is not valid.

Error in $: Problem with the "repository" field.

The given domain does not start with <https://github.com/>
```

I think is wrong to restrict the repositories to GitHub.

**Comment by jvoigtlaender** [comment]
This has been discussed often. And/but this here is the wrong repository for that discussion.

**Comment by jvoigtlaender** [comment]
For reference: https://github.com/elm-lang/elm-package/issues/189.
