### ISSUE TITLE
tuple limit: tuple exceeding 9 members results in elm-make error

### ISSUE THREAD

**Issue by kkruups** [elm-lang/core#781]
## Tuples exceeding 9 members result in following errors being indicated:

    elm-make: Could not find `_Tuple10` when solving type constraints.
    elm-make: thread blocked indefinitely in an MVar operation

## Code to reproduce this issue:
```
import Html exposing (text)

myTup = (1,2,3,4,5,6,7,8,9,10)

main =
  text <| toString myTup

```

It appears like tuples are special, and constrain the number of members. 
They do not allow same number of members as Lists, since I can create a list with the same 
number of members without issue.  

`myList = [1,2,3,4,5,6,7,8,9,10]`

**Why the constraint?**

Is this WAD?

## Additional Info:
I wanted to do the following with tuples, which works with lists but not tuples:

```
import Html exposing (text)

-- timesIt = \y -> [let baizo x =  x * y  in ( baizo 1 , baizo 2 , baizo 3, baizo 4, baizo 5, baizo 6, baizo 7, baizo 8, baizo 9, baizo 10 )]

timesIt = \y -> [let baizo x =  x * y  in [baizo 1 , baizo 2 , baizo 3, baizo 4, baizo 5, baizo 6, baizo 7, baizo 8, baizo 9, baizo 10 ]]

myList = [1,2,3,4,5,6,7,8,9,10]

main =
  text <| toString <| timesIt 3

```

 What OS and browser are you using? What versions?
```
Chrome Version 54.0.2840.99 m
Win 7 SP1

```
 What version of Elm are you using?

```
Elm Online Editor (elmO) (v.0.18 online)
Elm-Repl: v.0.17
```

**Comment by rtfeldman** [comment]
Thanks for reporting this @kkruups!

This repo is for Elm's `core` package, whereas what you've discovered is a compiler bug.

Would you mind re-opening this issue on https://github.com/elm-lang/elm-compiler/issues ?

**Comment by kkruups** [comment]
@rtfeldman done! :)
