### ISSUE TITLE
tuple limit:  tuples larger than 9 elements are not allowed

### ISSUE THREAD

**Issue by kkruups** [elm-lang/core#792]
## Issue:
Tuple Data type does not allow tuples larger than 9 members to be created.  The following error is indicated.  

Expected Behavior: tuples would not have limit and would not be constrained just as Lists are not constrained.

## Error Indicated:
```
elm-make: Could not find `_Tuple10` when solving type constraints.
elm-make: thread blocked indefinitely in an MVar operation
```

How to recreate:

1.In elm-repl or ElmO (Elm Online Editor) create the following tuple and run:
` (1 , 2 ,3,  4, 5, 6, 7, 8, 9, 10)`

## Additional Info:
I wanted to create a list comprehension which included a **tuple** (breaks at 10 member):

This fails with indicated error:
`tupleIt = \y -> [let baizo x =  x * y  in (baizo 1 , baizo 2 , baizo 3, baizo 4, baizo 5, baizo 6, baizo 7, baizo 8, baizo 9, baizo 10, baizo 11, baizo 12) ]`

However with a list is works successfully:

`listIt = \y -> [let baizo x =  x * y  in [baizo 1 , baizo 2 , baizo 3, baizo 4, baizo 5, baizo 6, baizo 7, baizo 8, baizo 9, baizo 10, baizo 11, baizo 12 ]]`

## Environment:

win7 sp1
elm-repl (0.17)
elmO  (latest version 0.18 release)  (should really add version info to elmO)

**Comment by jvoigtlaender** [comment]
This is not a bug, and not an issue of `core`. It's a feature limitation of the compiler. According to the guidelines of this repository (and what `process-bot` says), this does not belong here as an open GitHub issue,
