### ISSUE TITLE
Ref to Html.App still in docs

### ISSUE THREAD

**Issue by wintvelt** [elm-lang/core#793]
In the package docs, for the Platform package, in the paragraph on the Program type,
Here: http://package.elm-lang.org/packages/elm-lang/core/5.0.0/Platform#Program

The 2nd paragraph still mentions Html.App. 

"You can create headless programs with the program and programWithFlags functions. Similar functions exist in Html.App that let you specify a view."

Should be Html since 0.18, right?

**Comment by evancz** [comment]
Okay, this got fixed by https://github.com/elm-lang/core/commit/915fb98c87a60d8b3bea175bac5101a4adb1a767, but there has not been a new release of core yet. So it'll be fixed with the next release!
