### ISSUE TITLE
SVG should be in the Documentation links underneath HTML...

### ISSUE THREAD

**Issue by GordonBGood** [elm-lang/core#795]
SVG is commonly used to augment basic HTML view layouts and features prominently in many examples such as "clock" from which we learn about subscriptions and the basic Elm architecture;   however, it can only be found by opening up github to the overall elm-lang view and find its repository.

It (and perhaps other commonly used projects) should be included in the documentation summary page at:  http://elm-lang.org/docs.

**Comment by jvoigtlaender** [comment]
Please make this suggestion in the repository for the package site, not here (which is for the standard library).
