### ISSUE TITLE
The view is only updated as per the latest Model when the runtime is passed Cmd.none...

### ISSUE THREAD

**Issue by GordonBGood** [elm-lang/core#796]
Sometimes one might want intermediate updates, as as the following sequence of tasks:

1. Respond to a Start Button click by setting state of a running boolean (not doing anyting - exiting sequence - if running is already True).
1. Take the current time.
1. Run something
1. Take the stop time.
1. Display the results.

Currently, the results and the elapsed time are only displayed at the end (when Cmd.none is sent to the runtime) even though the model is updated at every step, which should cause changes to the view model.

It would be nice if the view model could be updated at intermediate steps, so that one could do such things as disable the Start Button, update status ("Running" instead of "Waiting for Click"), clearing text fields, etc.

This might be easily accomplished by adding a Cmd.update that could be batched with other commands on any given intermediate step of the sequence where the view update should be triggered (or doing special processing for Cmd.none when it is one of the  batched Cmd's to treat it like a request for view update - doesn't currently work; it currently only seems to update the view when there is nothing else to do).

**Comment by jvoigtlaender** [comment]
This is something for discussion on the mailing list, instead of the GitHub issue tracker here. (To understand why, have a look at what process-bot points to above.)

Hence, I'm closing this here.
