### ISSUE TITLE
Array.Append mutates first argument when result is small

### ISSUE THREAD

**Issue by zynque** [elm-lang/core#802]
Array.Append should not alter the two arrays passed to this function, however, when the resulting array is 32 elements or less, the array value passed as the first argument gets mutated.

Elm.Core version: 5.0.0
Browser/OS: Chrome/Windows

Example of this behavior:

    a1 = Array.repeat 20 1 
    a2 = Array.repeat 12 2
    a3 = Array.append a1 a2

    -- a1: Array.fromList [1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,2,2,2,2,2,2,2,2,2,2,2,2]
    -- a2: Array.fromList [2,2,2,2,2,2,2,2,2,2,2,2]
    -- a3: Array.fromList [1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,2,2,2,2,2,2,2,2,2,2,2,2]

    a4 = Array.repeat 20 1
    a5 = Array.repeat 13 2
    a6 = Array.append a4 a5

    -- a4: Array.fromList [1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1]
    -- a5: Array.fromList [2,2,2,2,2,2,2,2,2,2,2,2,2]
    -- a6: Array.fromList [1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,2,2,2,2,2,2,2,2,2,2,2,2,2]

**Comment by jvoigtlaender** [comment]
Duplicate, covered in https://github.com/elm-lang/core/issues/649, isn't it?

**Comment by zynque** [comment]
Apologies for the oversight. Thanks for closing!
