### ISSUE TITLE
Date.fromString failed when tried to convert string that was obtained using toString on Date. 

### ISSUE THREAD

**Issue by Wildsoft** [elm-lang/core#807]
Error: Unable to parse '<Sat Jan 14 2017 17:06:24 GMT-0500 (Eastern Standard Time)>' as a date. Dates must be in the ISO 8601 format.

The same code worked well on Chrome but failed on Firefox (50.1.0 on Windows 8)

**Comment by Wildsoft** [comment]
IE 11 had the same issue

**Comment by Wildsoft** [comment]
Here is a snippet of code that reproduce the issue:
addHistoryEntry : DestParty -> Date -> UserData -> UserData
addHistoryEntry destParty callDate userData =
  let
    dateStr = (toString callDate)
    dateForVal = Date.fromString dateStr
    dateStr2 = case dateForVal of
      Ok _ -> dateStr
      Err err -> "Got:"++ err
............................................................................................

**Comment by jvoigtlaender** [comment]
Can you try to properly format your example code in the last comment using a Markdown code block?

**Comment by Wildsoft** [comment]
Sure, I have recreate the issue with very small program.  Here it is:

import Html exposing (text)
import Date exposing (..)
import Time exposing (..)



main =
  text (case 
          (
           Date.fromTime 1484459877252 |>
           toString |>
           Date.fromString
          ) of 
  Ok date -> toString date
  Err err -> err)

**Comment by jvoigtlaender** [comment]
Look at how your comment (also the new one) looks on GitHub. No formatting, unreadable.

**Comment by Wildsoft** [comment]
Can you please look at attached file?

**Comment by jvoigtlaender** [comment]
Please open a new issue, with all relevant information in the first comment, in readable form. Our current conversation here will just make it more complicated to see what the problem is and to act on it.

**Comment by Wildsoft** [comment]
Done

**Comment by jvoigtlaender** [comment]
@Wildsoft, please do take a look at https://github.com/elm-lang/core/issues/810#issue-200876297. I edited your comment there to put the code right there into it as a Markdown block (instead of a link only). *This* is how you should present examples like this in an issue if you want to make it easy for the maintainer to work with your issue (which you *should* want).

**Comment by Wildsoft** [comment]
@jvoigtlaender , sure, thanks for your help and patience
