### ISSUE TITLE
Sub.filter function

### ISSUE THREAD

**Issue by aravantv** [elm-lang/core#808]
Hi,

I would really like to see a Sub.filter function:

`Sub.filter : (a -> Bool) -> Sub a -> Sub a`

such that `Sub.filter p s` is a subscription which only sends updates if the value carried by the original subscription `s` passes the predicate `p`.

I would like to make a "sub-extras" package as indicated in the guidelines but the only solution I see requires changing the Native.Platform package and, as far as I understood, I should not be dealing with this in a separate library... right?

**Comment by jvoigtlaender** [comment]
There has been extensive discussion of exactly this request on the mailing list in the past (driven by me). Please find that thread there. The role of the issue tracker here is not for feature requests. If you want a new feature added, you will have to make a convincing argument in the discussion forum first. For this specific request, I and others have tried but been turned down.

**Comment by jvoigtlaender** [comment]
What you should probably read:
* https://groups.google.com/d/msg/elm-discuss/u-6aCwaJezo/fu-HMPy6CQAJ

And maybe also:
* https://groups.google.com/d/msg/elm-discuss/Ud7WzAhRsqE/O9-T9UZOCAAJ

**Comment by aravantv** [comment]
Thanks! The conversation there reflects precisely my train of thoughts.

Sorry for using the issue tracker for feature request, there are so many options out there to communicate (Slack, Mailing list, Github, usw.) that I was not so sure what's the best way to do it. Now I know.
