### ISSUE TITLE
Hot-swapper does not check types of new states vs. old states

### ISSUE THREAD

**Issue by jvoigtlaender** [elm-lang/core#81]
On http://elm-lang.org/blog/Interactive-Programming.elm, it is said: "The hot-swapper can also check to see if the types of the old state matches the types of the new state, ruling out a whole class of hot-swapping-induced runtime errors."

However, that checking is not currently done by the hot-swapper.

**Comment by jvoigtlaender** [comment]
Maybe it makes sense to add this to https://github.com/elm-lang/elm-reactor/milestones/Swapping?

**Comment by evancz** [comment]
Yeah, can we move this issue over to that repo?

**Comment by jvoigtlaender** [comment]
Sure, will do.

**Comment by jvoigtlaender** [comment]
Reopening this issue here, since it was closed over at https://github.com/elm-lang/elm-reactor/issues/107, because the reactor does not at the moment actually do any hot-swapping (it just swaps and replays).

On the other hand, http://elm-lang.org/try *does* use hot-swapping, and is affected by the difference of actual implementation from what the "Interactive Programming" post says.

The current code showing that only the structure, not the types, are compared on hot-swap is here: https://github.com/elm-lang/core/blob/2.1.0/src/Native/Runtime.js#L449-L460.
