### ISSUE TITLE
Support for unicode "variables"?

### ISSUE THREAD

**Issue by manonthemat** [elm-lang/core#815]
In certain situations, I've found for me, that choosing a constant/variable name using characters like the kanji "角" instead of the english word "angle" is useful.

I've found that I can not do this using elm 0.18.0.

Is this something that could be of use to the elm community? As I've just started exploring elm, I'm wondering what my next steps would be to be able to actively contribute to this improvement.

**Comment by mgold** [comment]
Greek letters such as theta, pi, and [tau](tauday.com) would also be useful.

**Comment by lukewestby** [comment]
@manonthemat this is something that should be discussed on the mailing list. github issues are meant for things like reporting bugs. please refer to the [contribution checklist](https://github.com/process-bot/contribution-checklist/blob/master/issues.md)

thanks!
