### ISSUE TITLE
KeyCode called "unicode" in Char documentation

### ISSUE THREAD

**Issue by kasbah** [elm-lang/core#82]
Or am I missing something? 

https://github.com/elm-lang/core/blob/master/src/Char.elm#L85

**Comment by kasbah** [comment]
Sorry, I investigated myself and it _is_ the same thing as it uses [fromCharCode](http://www.w3schools.com/jsref/jsref_fromcharcode.asp) under the hood. Feel free to close unless you feel the documentation could use improvement.

**Comment by kasbah** [comment]
I am even more confused now as `toCode 'g'` returns 71 which is the same as `toCode 'G'` (uppercase) even though it seems to be using `str.charCodeAt(0); ` under the hood.  I don't see where it is being converted to uppercase and I don't think the docs are really clear that this is what should be happening.

**Comment by kasbah** [comment]
Ah, I just found #50 through `git blame`.

**Comment by evancz** [comment]
Seems like the docs could be changed. Can you do a PR?
