### ISSUE TITLE
Minor change from 5.0.0 to 5.1.1 causes compilation errors if aliasing List.Extra as List

### ISSUE THREAD

**Issue by joeandaverde** [elm-lang/core#821]
`import List.Extra as List`

My `elm-package.json` has these dependencies:

```
"elm-community/list-extra": "4.0.0 <= v < 5.0.0",
"elm-lang/core": "5.0.0 <= v < 6.0.0",
```

Error is:

```
-- NAMING ERROR - ././src/REDACTED_FILE_NAME_HERE.elm

This usage of variable `List.singleton` is ambiguous.

REDACTED LINE OF CODE 

Maybe you want one of the following?

    List.Extra.singleton
    List.singleton
```

This failed because we imported a module aliased with the same name as a core module. I imagine others will break for a similar reason. This type of import seems to be used commonly in many examples.

I think the problem is that list-extra and core didn't both get a major version upgrade. 

List-Extra did a major version change whereas core did a minor version change. This discrepancy caused elm-package to download one update and not the other.

**Comment by joeandaverde** [comment]
In order for us to proceed with a build I believe the best course of action would be to specify exact versions.

**Comment by stephenreddek** [comment]
@joeandaverde https://github.com/elm-lang/elm-package/issues/259 seems to make this fix impossible. Requires a code change to recover.

**Comment by mgold** [comment]
Upgrading to list-extra 6.0.0 should resolve this issue.

**Comment by joeandaverde** [comment]
Wouldn't that mean all of my dependencies that depend on List.Extra would have to upgrade to the latest version also?

**Comment by mgold** [comment]
...yes. Crud.

**Comment by lukewestby** [comment]
@joeandaverde @mgold is this resolved?
