### ISSUE TITLE
Trivial port send example: Uncaught TypeError: Cannot read property 'tag' of undefined

### ISSUE THREAD

**Issue by maca** [elm-lang/core#822]
I am getting this runtime error for the most trivial port send example:

JS:
```
elmApp.ports.incoming.send("hello")
// #=> Uncaught TypeError: Cannot read property 'tag' of undefined
```

Elm:
```
port module Ports exposing (..)

port incoming : (String -> msg)  -> Sub msg
```

Using: elm 0.18
Browser/OS: Chromium 55/Linux

Gist coming...

**Comment by maca** [comment]
It works fine when I define my main module as a port module and define the ports there, instead of doing it in another file/module.

Feel free to disregard

**Comment by aaronjameslang** [comment]
This still occurs, specifically if the project's port module has a name beginning with a letter before J, and does not have a declared dependency on `Json.Decode` then the elm compiler will emit the port module code before `Json.Decode` which causes all decoders to be `Undefined`. See https://groups.google.com/forum/#!topic/elm-discuss/Zs5LFb_Ei_4

**Comment by FranzSkuffka** [comment]
For me this also occurs.

**Comment by evancz** [comment]
Please make an http://sscce.org/ and open a new issue.
