### ISSUE TITLE
Type mismatch for tuple union types passed to tuple functions

### ISSUE THREAD

**Issue by zeddidragon** [elm-lang/core#827]
**Steps to reproduce:**
```elm
type Foo
  = Bar (String, Int)
  | Baz (Int, Int)

bar : Foo
bar = Bar ("Bar", 1)

derp : (a, Int) -> Int
derp (a, b) = b

herp = derp bar

```

**Actual result:**
```
-- TYPE MISMATCH ------------------------------------------------- UnionType.elm

The argument to function `derp` is causing a mismatch.

11|        derp bar
                ^^^
Function `derp` is expecting the argument to be:

    ( a, Int )

But it is:

    Foo
```

**Expected result:**
Program compiles, herp is 1

Since any instance of Foo is guaranteed to be a tuple where the second element is an Int, it should be reasonable to expect a function that only cares about the second element of the tuple to accept instances of Foo.

**Version**
Elm version 0.18.0 for OSX

**Comment by mgold** [comment]
This behaves as designed and is unlikely to be changed. I can go into more depth if you ask on the [mailing list](https://groups.google.com/forum/#!forum/elm-discuss).

**Comment by jvoigtlaender** [comment]
Max is right. I'm closing this issue.
