### ISSUE TITLE
Elm kernel for jupyter

### ISSUE THREAD

**Issue by RyanCCollins** [elm-lang/core#828]
I'd love to be able to write elm in Jupyter notebooks and thought I'd make a feature request to see if that's possible.  You can see the list of kernels available [here](https://github.com/jupyter/jupyter/wiki/Jupyter-kernels).  Thank you!

**Comment by lukewestby** [comment]
@RyanCCollins please bring this discussion up on the [community](http://elm-lang.org/community) discussion spaces. Github issues are for tracking bugs. Thanks!

**Comment by RyanCCollins** [comment]
@lukewestby Sure thing!  Appreciate the pointer to the community.  Apologies for cluttering the issue tracker on here.  Take it easy!
