### ISSUE TITLE
Better documentation for Date.fromString

### ISSUE THREAD

**Issue by jinjor** [elm-lang/core#833]
The document for [Date.fromString](http://package.elm-lang.org/packages/elm-lang/core/latest/Date#fromString) is just saying

```
Attempt to read a date from a string.
```

, but does not describe what kind of string is valid.
Giving some examples or saying it is just the same as `new Date()` may be more helpful.

**Comment by evancz** [comment]
It makes sense to either go with ISO 8601 and rename this to `fromIso8601` or to do something more serious to solve this in a better way.
