### ISSUE TITLE
Confusing Char.KeyCode

### ISSUE THREAD

**Issue by jinjor** [elm-lang/core#837]
I believe ASCII (char code) and key code are different things. It took me a while to find I can use `fromCode` to convert `120` to `'x'` (`120` is `F9` in key code). Could the documentation cover more general usages (e.g. reading binaries)? Also, it lacks information for error cases.

Maybe there are other solutions:
* Just call it "Int"
* Move these features to elm-lang/keyboard

**Comment by evancz** [comment]
https://github.com/elm-lang/core/commit/3a6dc880a475aa153d4ac47156dca5f9a9e892c7 also improves the docs a bunch so a lot of functions are clearer.
