### ISSUE TITLE
Improve Regex equality

### ISSUE THREAD

**Issue by pauldijou** [elm-lang/core#839]
Right now, any Elm regex is considered equal to any other regex even if their definitions are totally different. [Check demo](https://ellie-app.com/mcxKPrvCqM/0).

Maybe improve `Native.Utils.eq` to perform a special check when testing regexps. Found this code browsing SO:

```javascript
function regexSame(r1, r2) {
    if (r1 instanceof RegExp && r2 instanceof RegExp) {
        var props = ["global", "multiline", "ignoreCase", "source"];
        for (var i = 0; i < props.length; i++) {
            var prop = props[i];
            if (r1[prop] !== r2[prop]) {
                return false;
            }
        }
        return true;
    }
    return false;
}
```

**Comment by lukewestby** [comment]
@pauldijou can you share some reasons why you would want to check the equality of two regex values?

**Comment by pauldijou** [comment]
I was messing around implementing a `Map` (like a `Dict` but with any type of key) and using `Regex` as keys broke it since all regexs were considered equals.

**Comment by evancz** [comment]
`Regex` is similar to functions when it comes to equality. We will eventually be able to disallow using `(==)` on them statically, but it's not possible for now. So this will be "improved" by turning it into a compilation error once the compiler work happens.

**Comment by jvoigtlaender** [comment]
Maybe a note about Regex at http://package.elm-lang.org/packages/elm-lang/core/latest/Basics#== would be in place.
