### ISSUE TITLE
List literal with many items leads to "Maximum call stack size exceeded"

### ISSUE THREAD

**Issue by witoldsz** [elm-lang/core#840]
I just discovered that list literals with many items produce a code which crashes at run-time.
Look at this example: https://runelm.io/c/yca
It defines a list with 1000 items and the program will crash before it executes. Sometimes 400 items will be enough to crash the browser, sometimes 600 won't crash.

I have found this when I was trying to work with `elm-community/elm-time` library. The bug was filled:
https://github.com/elm-community/elm-time/issues/13
Example: https://ellie-app.com/qwD8mkg9TTa1/1

Later, I have found another, unrelated issue with that lib:
https://github.com/elm-community/elm-time/issues/21
and when I was trying to fix that, I have discovered I cannot even build that project, because it was crashing with `Maximum call stack size exceeded` during `elm-test`.

There is no hard limit: that very lib defines dict with all possible time zones which is c.a. 600 elements. It sometimes crashes, sometimes it does not, depends on browser and number of opened tabs.

**Comment by witoldsz** [comment]
Workaround: split your big list and use `List.concat`, example:

```elm
before =
    [1,2,3, …, n]

after =
    List.concat [ [1,2,3, …], [ 31, 32, 33, …], …] ]
```

**Comment by jvoigtlaender** [comment]
Thisis a duplicate of a known issue: https://github.com/elm-lang/elm-compiler/issues/1521

Please close.

**Comment by witoldsz** [comment]
That's strange, I was looking for an open issue with "maximum" and did not find it.

**Comment by jvoigtlaender** [comment]
Looked in the wrong repository?

**Comment by witoldsz** [comment]
You are right! I was looking in elm-core.
