### ISSUE TITLE
Idea - func factory

### ISSUE THREAD

**Issue by philn5d** [elm-lang/core#841]
I'm new to elm-lang, seems great so far. I have an idea...

I was looking at svg src and it seems like there's a lot of unnecessarily repeated code as in https://github.com/elm-lang/svg/blob/master/src/Svg.elm perhaps which is more general to other packages as well. If there were a way to define the functions (since they all share the same type) using a function, all of that could go away and you'd don it like this -
```
map-type : Type -> f-> List( String ) -> g
map-type  t f names=
    names ... however you do a lambda ... name => make-func name t (f name)

make-func : Type -> f -> name -> g
make-func t name f =
    name : t
    name (get-args t) =
        f
```        
Not really sure how it would work, but the idea is there.   

Use like this:

```
map-svg-types =
    map-types (List( Attributes msg ) -> List ( Svg msg ) -> Svg msg) node

map-svg-types 
    [ "square"
    , "circle"
    .
    .
    ]
```
Well, I'm not sure about the syntax, but it would eliminate all the repeat function definitions. The map-types or maybe it should be make-funcs should create funcs of the type given across the list of function names.

**Comment by evancz** [comment]
You are describing a macro system. The issue tracker is for bugs, not for open-ended design questions. More info in https://github.com/process-bot/contribution-checklist/blob/master/issues.md
