### ISSUE TITLE
Array initialization Bug or Expected?

### ISSUE THREAD

**Issue by DavidWhit** [elm-lang/core#845]
Windows 7
Elm REPL 0.18

```
someArray = Array.empty
Array.push someNewVal someArray -- REPL shows pushed
Array.push someNewVal someArray -- same
Array.length someArray  = 0 

```
hmm ok; but then

```
someArray = Array.push someNewVal  Array.empty
Array.push someNewVal someArray -- shows pushed
Array.length somArray = 1 not 2?
```
For the above 

![image](https://cloud.githubusercontent.com/assets/3008424/24014575/8296493e-0a53-11e7-8225-b7b649372a67.png)

Thanks, Dave

**Comment by jvoigtlaender** [comment]
Expected. Elm is a functional language. Values (like someArray) are immutable.

**Comment by DavidWhit** [comment]
That's fine just thought in an Array or List those were handled by the module itself to return a new copy for the immutable part otherwise I would never be able to modify an array or list once initialized. So the assumption was i was getting a new copy and garbage collection ran.

The answer I was looking for is that is the fundamental difference between array and lists as lists can be manipulated 

```
tasks = [task1, task2] 
List.append [task3], tasks
works as thought
```
I just really wanted to avoid having to use fromList every time but  it's not that big of a deal and I'm better now asking and thinking through it. 
for basic things like 
get 2 (fromList tasks)

**Comment by jvoigtlaender** [comment]
Lists are not any more or less manipulae than arrays in Elm.  In your example, the length of tasks is still 2 after the append call.

**Comment by DavidWhit** [comment]
Yeah, your are right this REPL keeps making me do a double take cause it looks like it's ok...
Then I quickly glanced at the web before I left work "A library for manipulating lists of values. Every value in a list must have the same type."
 Immutable is immutable Elixir will ( i question now) pattern match and if you set it = again it will replace with the copy but at this point trying to pick up both is causing some confusion.
Anyway thanks

**Comment by jvoigtlaender** [comment]
Don't you want to close the issue now?
