### ISSUE TITLE
Make Date comparable?

### ISSUE THREAD

**Issue by maxf** [elm-lang/core#851]
It would be nice to be able to compare dates, eg.
```
Date.fromTime 100000000) < (Date.fromTime 2000000000000)
```
But currently Date isn't a comparable type, making it a bit complicated to do things like having dates as Dict keys or sorting Dates.

**Comment by jvoigtlaender** [comment]
This is a duplicate of https://github.com/elm-lang/elm-compiler/issues/1482. @evancz

**Comment by lukewestby** [comment]
I added to #816 as well. Since we're tracking there as well as in a compiler issue let's close this.
