### ISSUE TITLE
I would like take up the task of improving documentation

### ISSUE THREAD

**Issue by anilreddykatta** [elm-lang/core#854]
Currently, most of the documentation is textual for some core modules without sample code and it's output. Do you guys think it's a good idea to have documentation with some sample code for core package? If yes, I can raise series of pull request to improve on those lines?

Also, thinking of providing a `repl` so a user can play in place without any installations?

**Comment by lukewestby** [comment]
Hey @anilreddykatta,

GitHub issues here are for reporting bugs. Ideas for how to improve something broader like documentation are best discussed on the [elm-dev mailing list](https://groups.google.com/forum/#!forum/elm-dev) or the #elm-dev channel in [slack](elmlang.herokuapp.com)
