### ISSUE TITLE
Date.fromString is NOT a pure function, result depends on local env

### ISSUE THREAD

**Issue by witoldsz** [elm-lang/core#855]
The result below depends on your local time zone.
```elm
"2017-07-25T20:31:23.647Z"
    |> Date.fromString
    |> Result.map (Date.hour >> toString >> (++) "The hour is: ")
    |> Result.withDefault ""
```
What I see is: 
```
The hour is: 22
```
Run this: https://runelm.io/c/2su

Functions in Elm are supposed to be pure, this one is not, because it calls `new Date(…)` which produces a date with a time zone of the local environment (system).

P.S.
Just to be clear: this is not about the ambiguous input. The `Z` stands for UTC (ISO8601).

**Comment by witoldsz** [comment]
I can see the #816 does not address this particular issue.

**Comment by lukewestby** [comment]
Added to #816, thank you!
