### ISSUE TITLE
disable "[elm-hot] ports.<port>.subscribe called." message logging.

### ISSUE THREAD

**Issue by nineonine** [elm-lang/core#858]
Is there a way to disable that log message? maybe there is a compilation flag or something? I am trying to debug Js/Elm interaction and I am heavily relying on good ol' consol.log . This message clutters up the console and it becomes tricky/annoying to debug.

**Comment by zwilias** [comment]
Hi,

This is an `elm-hot-loader` thing: https://github.com/fluxxu/elm-hot-loader/blob/85946eb359285b722fb5ead0173ed2fda0a93804/hmr.js#L257

You might want to log an issue on that project instead :)

**Comment by nineonine** [comment]
fluxxu/elm-hot-loader#31
