### ISSUE TITLE
Link to linear and radial gradients examples in documentation ends up on a 404

### ISSUE THREAD

**Issue by Psycojoker** [elm-lang/core#859]
Hello, 

[Here](http://package.elm-lang.org/packages/elm-lang/core/5.1.1/Color#linear) and [here](http://package.elm-lang.org/packages/elm-lang/core/5.1.1/Color#radial),  the links under "see this example" ends up on a 404. They seems to have been removed from the examples directory since it's still present http://elm-lang.org/examples/

Those links are defined here https://github.com/elm-lang/core/blob/70c7d1290cf4fcbbfee8aedefe2f48f250ac04b4/src/Color.elm#L246 and here https://github.com/elm-lang/core/blob/70c7d1290cf4fcbbfee8aedefe2f48f250ac04b4/src/Color.elm#L257

Kind regards,

**Comment by evancz** [comment]
For now I'm thinking of just removing the `Color` library, so the link is "fixed" in a sense.

Thanks for the report!
