### ISSUE TITLE
A type alias allows the same key to be defined multiple times

### ISSUE THREAD

**Issue by alessiosantangelo** [elm-lang/core#867]
Hi, we experienced an issue using Elm in production which breaks IE 11.
It seems that Elm allows the same key to be defined multiple times inside the same "piece" of model.
E.g.
```
type alias Save =
    { code : Id
    , totalPrice : Amount
    , hasDiscount : Bool
    , hasFranchigia : Bool
    , hasFranchigiaSoisy : Bool
    , canBeBooked : Bool
    , coverages : List Coverage
    , contractor : Contractor
    , conventionDiscount : Maybe ConventionDiscount
    , hasEarlyDiscount : Bool
    , hasPressureDiscount : Bool
    , hasFranchigia : Bool
    , colorCase : ColorCase
    }
```
The ```
hasFranchigia```
 is used two times inside the same type. 
The compilers does not throw any error or warning, but the Javascript Strict Mode doesn't allow multiple instances of the same key in the same object.

Probably this is not a problem of Elm itself, but I would share it with you. 
Thanks,
Alessio

**Comment by lukewestby** [comment]
Hey @alessiosantangelo,

> Probably this is not a problem of Elm itself, but I would share it with you.

this looks like something that we would want to address. Since this issue has to do with the compiler would you mind closing it here and reopening on https://github.com/elm-lang/elm-compiler?

Thanks!
