### ISSUE TITLE
No warning given when a port module has no ports

### ISSUE THREAD

**Issue by kevgathuku** [elm-lang/core#869]
When a module is declared as a `port module` and it has no ports, I expected a warning to be raised, but no indication of this is given from Elm.
Given that Elm recommends that very few modules should have ports in them, this case should give some feedback to the user.

Elm version: `0.18.0`

**Comment by evancz** [comment]
I think https://github.com/elm-lang/elm-compiler/issues/1386 should be the canonical issue for this.

Thank you for the report! It is helpful to see independent sources come to the same conclusion!
