### ISSUE TITLE
Cmd.batch reverses list

### ISSUE THREAD

**Issue by pdavidow** [elm-lang/core#877]
See JS console output for: https://github.com/pdavidow/CmdBatch
(Tones are actually played in correct order anyway.)

elm-version: 0.18
My platform: Windows10 64bit, Chrome browser

**Comment by evancz** [comment]
Ordering is not guaranteed to be anything. It could do a random shuffle on the commands.

**Comment by pdavidow** [comment]
Kindly document as such.

**Comment by evancz** [comment]
Info about this is already added in the dev branch.

https://github.com/elm-lang/core/blob/dev/src/Platform/Cmd.elm#L58-L68

Working on releasing that.
