### ISSUE TITLE
Faster dict implementation by improving code generation

### ISSUE THREAD

**Issue by Skinney** [elm-lang/core#879]
So I ran a simple benchmark, and got some interesting results. Here is the benchmark:

```
        describe "Dict"
            [ Benchmark.compare "Dict Get"
                (benchmark2 "First" Dict.get 1 dict)
                (benchmark2 "Last" Dict.get (n - 1) dict)
            ]
```

And here are the results:

![bench_orig](https://user-images.githubusercontent.com/854889/27509081-aee650e8-58f4-11e7-9aae-c4f84aa4228b.png)

Retrieving the last/highest/greatest element in a dictionary is slower than retrieving the first/lowest/least. This seemed odd, so I did some investigating. I'm not going to list up everything I tried, but those that made a difference.

Every change I did was made to the compiled javascript of `Dict.get`. It originally looks like this:

```
var _elm_lang$core$Dict$get = F2(
	function (targetKey, dict) {
		get:
		while (true) {
			var _p15 = dict;
			if (_p15.ctor === 'RBEmpty_elm_builtin') {
				return _elm_lang$core$Maybe$Nothing;
			} else {
				var _p16 = A2(_elm_lang$core$Basics$compare, targetKey, _p15._1);
				switch (_p16.ctor) {
					case 'LT':
						var _v20 = targetKey,
							_v21 = _p15._3;
						targetKey = _v20;
						dict = _v21;
						continue get;
					case 'EQ':
						return _elm_lang$core$Maybe$Just(_p15._2);
					default:
						var _v22 = targetKey,
							_v23 = _p15._4;
						targetKey = _v22;
						dict = _v23;
						continue get;
				}
			}
		}
	});
```

If one removes the `continue get;` statements of that code, as well as the get label above the while-statement, this is the result:

![bench_no_label](https://user-images.githubusercontent.com/854889/27509124-191c50ec-58f6-11e7-81c5-b35caba2bb9c.png)

That's a hefty performance improvement for the "first/lowest/least" case. To improve performance for "last/greatest/highest", one needs to change the order of the switch statements, so that the function now looks like this:

```
var _elm_lang$core$Dict$get = F2(
	function (targetKey, dict) {
		while (true) {
			var _p15 = dict;
			if (_p15.ctor === 'RBEmpty_elm_builtin') {
				return _elm_lang$core$Maybe$Nothing;
			} else {
				var _p16 = A2(_elm_lang$core$Basics$compare, targetKey, _p15._1);
				switch (_p16.ctor) {
					case 'LT':
						var _v20 = targetKey,
							_v21 = _p15._3;
						targetKey = _v20;
						dict = _v21;
					case 'GT':
						var _v22 = targetKey,
							_v23 = _p15._4;
						targetKey = _v22;
						dict = _v23;
					default:
						return _elm_lang$core$Maybe$Just(_p15._2);
				}
			}
		}
	});
```

Then you get the following performance:

![bench_final](https://user-images.githubusercontent.com/854889/27509134-757a3a0c-58f6-11e7-8323-59fbacf96a30.png)

I also tried removing the label and `continue`-statements from other recursive functions like `List.foldl` and (my implementation of) `Array.get`, but saw no performance difference.

A couple of takeways:

1. Removing labels and continue statements were they are not needed can significantly improve performance for complex recursive functions (were the compiler would generate more than two continue statements). Based on what I've read, JIT compilers have trouble optimizing such loops. Removing a conditional `break`-statement from the `initializeFromList` function in the new Array implementation confirms this, as performance increased 2-3 times. In other cases, it would simply reduce code size.
2. Switch ordering really matters, which surprised me. In the case of `Dict.get` it matters a lot as the  `EQ` case is only triggered once, if at all, while `LT` and `GT` cases are triggered "all the time".
3. Loops not optimized properly, for instance because of complex loop-logic, can hinder other optimizations. Changing the switch ordering so `GT` comes right after `LT`, without removing labels and `continue`-statements, have no effect. Only when removing the label and `continue` statements is performance similar.

I don't know how difficult this is to implement, but it seems worthwhile :)

Also, it would be nice if someone could confirm my results. Here is a repo which makes it easy to get started: https://github.com/Skinney/elm-dict-exploration

**Comment by eeue56** [comment]
> Switch ordering really matters, which surprised me. In the case of Dict.get it matters a lot as the EQ case is only triggered once, if at all, while LT and GT cases are triggered "all the time".
Loops not optimized properly, for instance because of complex loop-logic, can hinder other optimizations. Changing the switch ordering so GT comes right after LT, without removing labels and continue-statements, have no effect. Only when removing the label and continue statements is performance similar.

This is easy to do, right now - right now, the _last_ case in a case..of is always used as `default`. Simply changing the ordering in the Elm file will make that work: https://github.com/elm-lang/core/blob/master/src/Dict.elm#L107

**Comment by Skinney** [comment]
I know. But as mentioned, it has no effect with removing the label and `continue`-statements first. I think it might be because it prevents optimizing the switch statement or something :/

**Comment by eeue56** [comment]
We discussed on Slack and weren't able to find/think of a place where `continue...label` would be required, based on the current compiler. Even edgecases like a TCO function being defined inside the body of another TCO function do not need the `continue`. V8 [seems](https://github.com/v8/v8/blob/24bf7ef59025b2bdabc8136a4e8aaa21ff61a8ea/src/ast/ast.h#L788) to do no form of optimisation for jumps like this, as far as I can tell from the code. [This](https://github.com/petkaantonov/bluebird/wiki/Optimization-killers#6-infinite-loops-with-deep-logic-exit-conditions-or-unclear-exit-conditions) might be relevant too.

**Comment by Skinney** [comment]
I just realized that I posted this in the wrong repo, this was supposed to go to the elm-lang/compiler repo :(

I'll try to move it.
