### ISSUE TITLE
Time.every improvement

### ISSUE THREAD

**Issue by kuznero** [elm-lang/core#884]
Does it make sense to improve current `every : Time -> (Time -> msg) -> Sub msg` to `every : Time -> (Time -> Maybe msg) -> Sub msg`, such that event is fired not precisely every `N` something, but also does that based on some predicate that will be possible to implement in `Time -> Maybe msg` lambda?

**Comment by evancz** [comment]
It may make sense, but any design like this would need to be motivated by practical examples. If you have some of those, that can make a stronger suggestion. I'd recommend trying to refine the idea on Elm slack or the elm-discuss mailing list and opening a new issue if you feel you have compelling evidence.

**Comment by jvoigtlaender** [comment]
@kuznero, there are related questions for other "subscription generating functions". So it *might* be useful for you to have a look at:
*  https://github.com/elm-lang/keyboard/issues/7

 as well as at two existing mailing list threads (referenced over there):
* https://groups.google.com/forum/#!msg/elm-discuss/u-6aCwaJezo/fu-HMPy6CQAJ and
* https://groups.google.com/forum/#!topic/elm-discuss/Ud7WzAhRsqE

**Comment by kuznero** [comment]
@jvoigtlaender thanks for the links
