### ISSUE TITLE
Text overflow in docs

### ISSUE THREAD

**Issue by fjanon** [elm-lang/core#885]
A long description like

http://package.elm-lang.org/packages/elm-lang/core/5.1.1/Platform#program

overflows in the TOC on the right side, apparently because of the CSS

```
.docs-annotation {
    white-space: pre;
```
If we remove "white-space: pre;" the text stays in its container.

Should the  ".docs-annotation white-space: pre;" be removed?

**Comment by jvoigtlaender** [comment]
This should be an issue in the repo https://github.com/elm-lang/package.elm-lang.org, not of the `core` library.

**Comment by evancz** [comment]
Thanks for the report!

It looks like we have https://github.com/elm-lang/package.elm-lang.org/issues/201 as well, so let's go with that one.
