### ISSUE TITLE
Json.Decode.list is not consistent

### ISSUE THREAD

**Issue by ghivert** [elm-lang/core#889]
Hi!

Encountered a bug today with decoders. Here's the case:

```elm
decodeUserPhotos : Decoder (List UserPhoto)
decodeUserPhotos =
  Decode.list decodeUserPhoto

decodeUserPhoto : Decoder UserPhoto
decodeUserPhoto =
  Decode.succeed UserPhoto
    |: (Decode.field "id" Decode.int)
    |: (Decode.field "cloudinary_id" Decode.string)
```

Used with a list like this:

```json
[
  {"id":3,"user_id":1,"cloudinary_id":"xxxxxx"},
  {"id":2,"user_id":1,"cloudinary_id":"yyyyyy"},
  {"id":1,"user_id":1,"cloudinary_id":"zzzzzz"}
]
```

On Chrome Mac, I got:
```elm
[ UserPhoto 1 "zzzzzz"
, UserPhoto 2 "yyyyyy"
, UserPhoto 3 "xxxxxx"
]
```

But on Chrome Windows, I got:
```elm
[ UserPhoto 3 "xxxxxx"
, UserPhoto 2 "yyyyyy"
, UserPhoto 1 "zzzzzz"
]
```

I just got the correct behavior by adding a `Json.Decode.map (List.sortBy .id)` after `decodeUserPhotos`. I think the output list should be consistent, whatever browser you're using.
I imagine it is browser specific?

**Comment by evancz** [comment]
Edit your post to have an http://sscce.org/

**Comment by evancz** [comment]
Actually, just make a new issue with the SSCCE. I think that'll work better.
