### ISSUE TITLE
Allow single quotes for strings since double quotes are hard to type on some keyboard layouts

### ISSUE THREAD

**Issue by ellogwen** [elm-lang/core#891]
I got used to writing single quotes for representing a string since double quotes are hard to type on my keyboard layout (at least for me and my body metrics). Now, while trying out elm, I noticed quickly that I am forced to use double quotes for strings instead of both (as in JavaScript). Now I am in constant "pain" bending my wrists and fingers for typing the double quote while trying out elm.

If I will stick with elm, I definitly will rebind my keys or something :)

**Comment by evancz** [comment]
In Elm, the literal `"hello"` is a `String` and the literal `'c'` is a `Char`. So we are actually distinguishing between different types of data.

If my memory is correct, this behavior is the same in C, C++, Java, C#, F#, OCaml, SML, Haskell, etc. So there is lots of precedent for this distinction in typed languages. I don't have any plans to change this behavior, so I don't think we should track it in a github issue.
