### ISSUE TITLE
Array has unwanted side effects - duplicates elements

### ISSUE THREAD

**Issue by okkero** [elm-lang/core#893]
## Description
When using `Array` under certain circumstances, elements in the array are duplicated when they shouldn't be. This makes some array operations impure. I can only guess that this is due to a bug in the code that handles persistent data structures in the runtime (does `Array` map more or less directly to JavaScript's array under the hood?).

## Example that exhibits the problem
Check out this example: https://ellie-app.com/3W8CQfWkjfSa1/4 (I tried making it as short as possible and still keeping the bug)

This is a small portion of an app that I'm working on. It's a relatively unstyled version of a dialog box for configuring a graph, wherein you can select which parameters are shown on which axis.

### Steps to reproduce

1. Compile the example and click the `Setup` button
2. Select the `abc` parameter in the first list, by clicking on it
3. Move it to the second list by clicking the button labeled `v`
4. Click cancel. According to the Elm code the state of the setup dialog should now be reset and `abc` should be back in the first list.
5. Click `Setup` again. Observe how `abc` has been moved back to the first list, but that it has also been duplicated and still exists in the second list.
6. Weirder still, if you open `Debug` and click the `ClickMoveTo` message, `abc` will be duplicated again. Keep clicking this message and `abc` will keep duplicating. This is not expected nor correct behaviour.

## Additional information
I have tested the same code with the difference that the `Array`s have been replaced with `List`s. Now the app works as expected.

I have only tested this on Windows 10, on Google Chrome Version 60.0.3112.90, but I am willing to bet that it happens on all browsers and OSes.

**Comment by sigurdsa** [comment]
Able to reproduce on Firefox 54.0.1 also

**Comment by Skinney** [comment]
This is fixed in the upcoming Elm 0.19.

If you need a working version *NOW*, then you can use the package `Skinney/elm-array-exploration`.
