### ISSUE TITLE
Color is not comparable, can't make a Set of them

### ISSUE THREAD

**Issue by Keyamoon** [elm-lang/core#894]
Since `Color` is not `comparable`, I couldn't make a `Set` of them. I ended up writing a pair of functions to convert `Color` to and from tuples.

Why did I want to make a `Set` of `Color`s in the first place? Because `Set` helps me avoid duplicates, and I'm using it to extract and keep all the colors found in user input.

I just opened this issue to point out a use case regarding https://github.com/elm-lang/elm-compiler/issues/1008.

**Comment by evancz** [comment]
This seems like a request to make `Color` into a `comparable` type.

I think doing one-off changes like this feels like progress, but it does not address the root issue, and in one or five or ten years, it will be quite a bad path. So I am not planning to change this in isolation.
