### ISSUE TITLE
Color.toHsl (Color.rgb 255 255 255) returns to NaN

### ISSUE THREAD

**Issue by simonh1000** [elm-lang/core#895]
In elm-repl
```
> import Color
> Color.toHsl (Color.rgb 255 255 255)
{ hue = NaN, saturation = NaN, lightness = 1, alpha = 1 }
    : { alpha : Float, hue : Float, lightness : Float, saturation : Float
      }
```
Likewise `Color.toHsl Color.white` fails

**Comment by zwilias** [comment]
Related PR's and discussion: #695 and #587 and an important [commit](https://github.com/elm-lang/core/commit/aaaaa929963b5a6a695eec28b52008de00a5c189)

Depending on use-case, you may be able to work around the issue with `if isNaN v then 0 else v` to post-process `.hue` and `.saturation`.
