### ISSUE TITLE
TypeError: array is undefined slicing an array at the end in current elm

### ISSUE THREAD

**Issue by prozacchiwawa** [elm-lang/core#900]
Although the previous issues with arrays have been closed, I see this error using recent elm (confirmed on ellie-app and elm-lang.org/try) when slicing zero elements from the end of an array.

https://ellie-app.com/45rwKnNgpwVa1/0

full example:

    module Main exposing (..)

    import Html exposing (Html, text)
    import Array

    main : Html a
    main =
        let end = 200 in
        let x = Array.initialize end identity in
        text (toString (Array.slice end end x))

Throws:

TypeError: array is undefined

Stack Trace:

length http://elm-lang.org/compile:956:1
sliceLeft http://elm-lang.org/compile:634:10
slice http://elm-lang.org/compile:555:9
A3 http://elm-lang.org/compile:99:7
_user$project$Temp1503266268830868$main< http://elm-lang.org/compile:7800:5
<anonymous> http://elm-lang.org/compile:7795:2
<anonymous>

Expected:

Array.fromList []

**Comment by Skinney** [comment]
It's been fixed in the next version of Elm. In the meantime, you can use `Skinney/elm-array-exploration`, which is the new array implementation available as a third-party library.
