### ISSUE TITLE
Complier fails to recognize imported module.

### ISSUE THREAD

**Issue by z5h** [elm-lang/core#906]
X.elm
```
module X exposing (X)

type X
    = X Int
```

Y.elm
```
module Y exposing (..)

import X


type Thing
    = A X.X


thingToString : Thing -> String
thingToString thing =
    case thing of
        A (X.X int) ->
            "A X int"
```

Error is on 2nd use of `X.X` in Y.elm:
> Cannot find pattern `X.X`.
> No module called `X` has been imported.

**Comment by evancz** [comment]
When you say `exposing (X)` you are only exposing the type, not the constructors. You must say `exposing (X(..))` to reveal the constructors as well. This allows you to _hide_ details if you want, and it is very important to creating strong abstractions.

So there is no bug here exactly, but that is certainly a weird error message. This is a good candidate for https://github.com/elm-lang/error-message-catalog/issues Can you put it there?

**Comment by martian57** [comment]
I am new to elm. Exposing the constructors work, but a slight modification to the code cause the compiler to fail:


X.elm:
```
module X exposing (XType(..))

type XType
    = X1 Int
```

Y.elm:
```
module Y exposing (..)

import X


type Thing
    = A X.XType


thingToString : Thing -> String
thingToString thing =
    case thing of
        A (X.XType int) ->
            "A X int"
```

results in

```
Cannot find pattern `X.XType`.

13|         A (X.XType int) ->
               ^^^^^^^^^^^
`X` does not expose `XType`. 
```

**Comment by jvoigtlaender** [comment]
Try replacing `A (X.XType int)` by `A (X.X1 int)`.

**Comment by jvoigtlaender** [comment]
Try replacing `A (X.XType int)` by `A (X.X1 int)`.
