### ISSUE TITLE
1 % 0 is an intentional runtime exception

### ISSUE THREAD

**Issue by rtfeldman** [elm-lang/core#909]
This was a [design decision from 2013 based on how Haskell did it](https://github.com/elm-lang/elm-compiler/issues/262#issuecomment-24883407), which predated Elm's No Runtime Exceptions design guideline.

Creating an issue for this just to track it in https://github.com/elm-lang/core/issues/377

[According to IEEE](https://en.wikipedia.org/wiki/IEEE_754-1985#NaN):

> Some operations of floating-point arithmetic are invalid, such as taking the square root of a negative number. The act of reaching an invalid result is called a floating-point _exception_. An exceptional result is represented by a special code called a NaN, for "Not a Number". 

Since `NaN` is already an Elm value due to IEEE's influence on hardware design, it seems in line with how Elm's design goals have evolved to remove the following conditional `throw` in favor of letting JavaScript's `%` return `NaN` in the case of division by zero, which is the normal behavior of JS `%`.

https://github.com/elm-lang/core/blob/80bbcc901b748f2af250b92a6a3aa5b43a73edcf/src/Elm/Kernel/Basics.js#L23-L25

A counter-argument to this is that in a world where Elm compiled to Assembly, although it could trap [`SIGFPE`](https://en.wikipedia.org/wiki/Signal_(IPC)#SIGFPE) from the processor ([supported on Windows](https://msdn.microsoft.com/en-us/library/xdkz3x12.aspx) as well as on POSIX) for integer division by zero, [floating-point division by zero](https://en.wikipedia.org/wiki/Division_by_zero#In_computer_arithmetic) is considered well-defined by IEEE to be `Infinity`. So there would have to be some runtime overhead to check for `Infinity`, and any runtime overhead on arithmetic operations has the potential to be multiplied by a massive quantity of operations.

Interestingly, in Rust, both `x % 0` and `x / 0` crash the program, indicating that generating an extra automatic comparison with 0 (in order to crash if detected) was considered a worthwhile cost to pay, even for a language with a primary design goal of "have no runtime overhead."

**Comment by jvoigtlaender** [comment]
Maybe worth referencing the "integer division by zero" item from https://github.com/elm-lang/core/issues/721 here. (https://github.com/elm-lang/core/issues/590)

**Comment by gogocurtis** [comment]
I've noticed it is possible to crash the browser with code that is not called but does a divide by zero.


```
-- this will divide by zero when it is defined
unsafeFun =
    let
        start = 0
        end   = 3
        len   = List.length []
        indexes  = List.range start end |> List.map (\idx -> idx % len)
    in
        indexes
```

**Comment by brian-carroll** [comment]
@gogocurtis that is actually not a function definition, it's a constant value definition.

If you're used to languages that have functions with no arguments, Elm doesn't have that. All functions have arguments. Anything that doesn't have arguments is a constant, whose value will be evaluated on startup.

If you want to define a value but delay evaluation until you need it, the usual way is to use the empty tuple () as the argument type of a function, and just ignore it in the function body. (Usually naming it "_")

**Comment by evancz** [comment]
@rtfeldman, can you add to #377 and close this one?

**Comment by evancz** [comment]
Tracked in #377.
