### ISSUE TITLE
Mouse.position's initial value is (0, 0)

### ISSUE THREAD

**Issue by thSoft** [elm-lang/core#91]
The initial value of Mouse.position is (0, 0) regardless of the actual position of the mouse until it is moved. Example to reproduce: http://share-elm.com/sprout/54b129a6e4b05f9c59b24f3a
Elm version: 0.14.1

**Comment by jvoigtlaender** [comment]
That comes from this line: https://github.com/elm-lang/core/blob/master/src/Native/Mouse.js#L14

You would have to replace the `Utils.Tuple2(0,0)` in there by the current mouse position at program start. However, when that line of code is run, the "page" with respect to which you want the mouse position most likely doesn't even exist yet.

**Comment by jvoigtlaender** [comment]
In other words, this issues is unlikely to get fixed unless the runtime (in particular the way the signal graph is built and initialized, and when the actual "graphics display" is created) were restructured somewhat considerably.

**Comment by evancz** [comment]
I don't think it is possible to ask any browser for the mouse position, so my understanding is that this is not possible. If you can find a way to synchronously detect the mouse position in JS, we can do this. If you cannot, we should close this issue.

**Comment by thSoft** [comment]
Aha, [I see](http://stackoverflow.com/a/2601273/90874). That's a pity...

**Comment by jvoigtlaender** [comment]
Oh, so it's even worse, there is nothing to replace the `Utils.Tuple2(0,0)` in the first place. Learned something.

**Comment by evancz** [comment]
Yeah, I was surprised when I learned this as well. I'd like to do it nicer, but given that it has been impossible for 20+ years, I don't have tons of hope :P
