### ISSUE TITLE
runtime exception in Regex.regex

### ISSUE THREAD

**Issue by dave-doty** [elm-lang/core#912]
The function `regex : String -> Regex` creates a Elm `Regex` from a `String`. If given an invalidly formatted regex string, for example, `"0)"`, it throws a runtime exception.

Perhaps this is expected behavior, since `regex` returns a `Regex` instead of a `Result _ Regex`? So perhaps this is a feature request to alter the return type to return `Err _` if the input has bad syntax, or at least give some way to test whether a `String` is a valid Javascript regular expression before calling the `regex` function.

**Comment by dave-doty** [comment]
Sorry, I just noticed that this will be fixed in Elm 0.19:

https://github.com/elm-lang/core/issues/722

**Comment by evancz** [comment]
Yep, looking forward to that :)
