### ISSUE TITLE
Random.int low byte always zero for large ranges in Core 5.1.1

### ISSUE THREAD

**Issue by electronjoe** [elm-lang/core#917]
I came across this when verifying the randomness of my Elm application. I was using Random.Generate - but this caused me to explore in the REPL - and demonstrated unexpected behavior.

Note in the random output examples below
1870605312 = 0x6F7F2C00
-40506368 = 0xFD95EC00

In experimentation - all outputs appear to be 24 bits of randomness with a low byte of zero? Unless I'm somehow abusing things.

> Random.step (Random.int Random.minInt Random.maxInt) (Random.initialSeed 352342343451)
(1870605312,Seed { state = State 271757466 483020887, next = <function>, split = <function>, range = <function> })
    : ( Int, Random.Seed )
> Random.step (Random.int 0 Random.maxInt) (Random.initialSeed 352342343451)
(1870605312,Seed { state = State 271757466 483020887, next = <function>, split = <function>, range = <function> })
    : ( Int, Random.Seed )
> Random.step (Random.int Random.minInt Random.maxInt) (Random.initialSeed 352342342)
(-40506368,Seed { state = State 1784235513 1655838864, next = <function>, split = <function>, range = <function> })
    : ( Int, Random.Seed )

**Comment by electronjoe** [comment]
Additional information:
Browser: Chrome 61.0.3163.100 (Official Build) (64-bit)
OS: OSX Sierra 10.12.6

**Comment by electronjoe** [comment]
Wanted to follow up for people who might come across this.  I understand that mgold/elm-random-pcg is going to become mainline soon? I migrated to mgold/elm-random-pcg, it was completely API compatible with Core.Random - and resolved my issue.

**Comment by evancz** [comment]
Yes, that library will be in core in the next release of Elm. Using Max's library is a nice thing to do in the meantime.
