### ISSUE TITLE
Integer division doesn't work with left operands larger than LONG_MAX

### ISSUE THREAD

**Issue by Mischa-Alff** [elm-lang/core#92]
The issue at [elm-compiler#878](https://github.com/elm-lang/elm-compiler/issues/878) mentions it, but it's in the wrong repo, so I'm recreating it here.

LHS arguments greater than `LONG_MAX`(`4294967295`) return a negative number when using integer division (`//`).

```elm
main = asText (4294967295 // 2)
-- shows 2147483647
```

```elm
main = asText (4294967296 // 2)
-- shows -2147483648
```

This is because elm-core's `src/Native/Basics.js` `div` function is `a/b|0`, thus using JavaScript's OR operator, which most converts the LHS to a 32-bit integer  and returns a 32-bit integer.

EDIT: I read the JS spec, it's not a bug with JS, just another one of its problems.

**Comment by int-index** [comment]
I have encountered this bug and my workaround was to define my own integer division:
```elm
(//) : Int -> Int -> Int
a // b = floor (Basics.toFloat a / Basics.toFloat b)
```

Is there a better implementation?

**Comment by evancz** [comment]
Consolidated all the math related stuff into the #721 meta issue. Follow along there!

**Comment by drathier** [comment]
Late to the party, but @int-index your int division rounds negative numbers wrongly.

**Comment by fdenzer** [comment]
init : Model
init =
  10000000000000009
prints out in a View as
10000000000000008

Or a better example:
10000000000000001 to 10000000000000000 made sense for me, as all numbers after the mantissa are simply rounded truly
