### ISSUE TITLE
Time helper functions inSeconds, inMinutes etc. error

### ISSUE THREAD

**Issue by Saulzar** [elm-lang/core#922]
Time is an alias for Float which specifies time as a unit of milliseconds as far as I can tell. However, the helper functions inSeconds
```
inSeconds : Time -> Float
inSeconds t =  t / second
```

For example` isSeconds 2 = 0.002`  !! Where 2 seconds should be 2000 milliseconds

Instead of divding by `second` it should be multiplied.
```
inSeconds : Time -> Float
inSeconds t =  t * second
```

**Comment by zwilias** [comment]
The intended usage, which isn't terribly well documented, is that you can do something like this:

```elm
twoMinutes : Time
twoMinutes = 2 * Time.minute

inSeconds twoMinutes --> 120
``` 

The multiplication you propose as implementation for the `inSeconds` function is pretty much what you would use _right now_ to convert a `Float` into `Time`.

Perhaps a second set of functions can be added like `fromSeconds` which turns a number of seconds into an equivalent `Time` representation, though.

**Comment by Skinney** [comment]
I think a lot of this confusion can be cleared up by specifying that `Time` represents milliseconds, and filling out examples for all the functions in the namespace.

**Comment by Skinney** [comment]
But the entire `Time` api is about to change in 0.19 anyway, right?

**Comment by mkwiatkowski** [comment]
The API will change, but the documentation problem may remain. Current code on the `dev` branch is a bit confusing as the new `Posix` type seems to hold seconds (https://github.com/elm-lang/core/blob/dev/src/Time.elm#L62), but other functions treat it as milliseconds (https://github.com/elm-lang/core/blob/dev/src/Time.elm#L82).

**Comment by evancz** [comment]
There is a PR about adding docs for these functions (#920) so I'll let that be the canonical one.

The documentation is gonna get updated for the new API. It's not the same, so the docs cannot stay the same.
