### ISSUE TITLE
Is Elm dead?

### ISSUE THREAD

**Issue by Spenhouet** [elm-lang/core#927]
In November 2016 I tried out Elm the first time with the platform version 0.18 back then.
Since then I was watching the Elm project because I thought it looks really promising.
Looking at the project more than 1 year later it seems there was little to no change.
The last commit on the core is 5 months old.
The platform didn't even increased in a single minor version. After a whole year.
The last real core release was in the beginning of 2017.
Elm was removed from the TIOBE index in November (added back in December). Only assessed by the Technology Radar but never followed up.
I can't find any road map, any active development plans, non. Very little active contributors.

Is Elm dead? Is anyone even bothering anymore?

**Comment by mkwiatkowski** [comment]
Elm is alive and well. Most of the development happens on [the dev branch](https://github.com/elm-lang/core/tree/dev) and you'll see some recent activity there. Check out Slack and Reddit, that should convince you that the user base is growing: http://elm-lang.org/community If you are unsatisfied with the pace of development watching this talk should help you understand the process: https://www.youtube.com/watch?v=DSjbTC-hvqQ

**Comment by Spenhouet** [comment]
@mkwiatkowski Good to here that there is active development on Elm. I would wish this would be more transparent and things as changes, progress, road map, future plans, new version releases, ... would all be reflected on [elm-lang.org](http://elm-lang.org/). Looking at the website and the language for an outsider like me it looks like the language had no development at all since 1 year. If this isn't reflecting the actual state of the project than I think this isn't good for the language in terms of attracting new developers and companies to try and switch to Elm. I would be good to see an overview of current released versions of all parts of Elm, see the milestones and due dates for up coming releases, see the current features that are in progress and features that are planned. Additionally a long time vision / road map that get updated regularly would further increase the transparency of the progress and change on the Elm project. All this should be prominently presented on the main web page.
I'm not sure if all active Elm developers / contributors are so deep into the project that they don't see that for outsiders it looks like Elm is dead or if everything related to Elm updates is communicated on other (not obvious or visible) channels.

**Comment by zwilias** [comment]
The issue tracker is for bugs. Please feel free to get in touch with [the community](http://elm-lang.org/community) for further discussion. Thanks for your concern 🙂
