### ISSUE TITLE
Improving Json.Decode.index error messages

### ISSUE THREAD

**Issue by cjduncana** [elm-lang/core#928]
If the user of `Json.Decode.index` provides a negative integer, the following error message is decoded: `Err "Expecting an Int at _[-1] but instead got: undefined"` ([Example](https://ellie-app.com/6YxVrcZMha1/0)). Though technically correct we have an opportunity to improve the error message since we know why that position is `undefined`: a negative number was provided.

My suggestion is to check before [this](https://github.com/elm-lang/core/blob/5.1.1/src/Native/Json.js#L366) and [this](https://github.com/elm-lang/core/blob/dev/src/Elm/Kernel/Json.js#L231) if the integer provided is less than zero. If so, then provide a helpful error message like in the case when the integer exceeds the array's length: `Err "Expecting a longer array. Need index 5 but there are only 3 entries but instead got: [1,2,3]"` ([Example](https://ellie-app.com/6YxVrcZMha1/1)).

Sample code:
```javascript
if (index < 0)
{
     return _Json_expecting('a non-negative index. Index ' + index + ' was provided instead.', value);
}
```

**Comment by evancz** [comment]
The next release should make it easier to create custom error messages. Having lots of special cases by default will increase code size in ways that is not right for everyone, so I would not want to commit everyone to this approach.
