### ISSUE TITLE
Graphics.Input.hoverable causes runtime error

### ISSUE THREAD

**Issue by mgold** [elm-lang/core#93]
Minimum example:

````elm
import Graphics.Element as E
import Graphics.Input as Input
import Signal as S

chan = S.channel False

main = E.spacer 100 200 |> Input.hoverable (S.send chan)
````

Produces:
````
Cannot read property 'make' of undefined

Open the developer console for more details.
````

It seems to error on `var Text = Elm.Native.Text.make(localRuntime);` because `Elm.Native.Text` is undefined. Seems like a dependency ordering issue.

**Comment by mgold** [comment]
Related to elm-lang/elm-compiler#864. Solved by adding `import Text` to the top of the elm source.

**Comment by evancz** [comment]
Could you make a PR?

**Comment by mgold** [comment]
*headslap* I was adding it to the client code but yes adding it to the library fixes it as well.
