### ISSUE TITLE
Rename { List, Dict, Set }.length to count

### ISSUE THREAD

**Issue by Skinney** [elm-lang/core#938]
`List.length` gives sounds like a getter, giving the impression that it is a constant time operation, when it's actual linear time. Renaming that function to `count` gives a better impression of what the function actually does.

The same applies to `Dict` and `Set`. `Array.length`, on the other hand, is a getter and constant time operation and should keep its name.

**Comment by evancz** [comment]
I don't know. It seems like a fine idea, but I'm not convinced it is better than just adding `O(n)` to the docs on things.
