### ISSUE TITLE
Date.parse doesn't work in certain browsers

### ISSUE THREAD

**Issue by loovjo** [elm-lang/core#939]
`Date.parse` does not work for certain dates in Firefox, but does in Opera and Chrome. For example, the following code produces a parse error in Firefox, but works in Chrome:

    import Html exposing (text)
    import Date

    main = text <| toString <| Date.fromString "2018-02-24UTC"

**Comment by perty** [comment]
I tried the code in the online Elm editor and as said in OP, it is different results in FF and Chrome:
FF: Err "Unable to parse '2018-02-24UTC' as a date. Dates must be in the ISO 8601 format."
Chrome: Ok <Sat Feb 24 2018 01:00:00 GMT+0100 (CET)>

According to the [standard](https://en.wikipedia.org/wiki/ISO_8601), FF is correct, the date in the example is not a correct date.

**Comment by evancz** [comment]
It is getting removed from core in the next release. It will be replaced by parsers written in Elm for various formats such that we have guaranteed reliability.
