### ISSUE TITLE
Will the next release of core be version 2.0.0?

### ISSUE THREAD

**Issue by deadfoxygrandpa** [elm-lang/core#94]
All the Travis tests are failing right now because Elm-Test relies on the List function `maximum : List comparable -> comparable` function, which has now changed to `maximum : List comparable -> Maybe comparable`. 

It's pretty easy to fix this with a new version of Elm-Test, but I want to set the correct version bounds, so when all this new core stuff is released it won't mess people up if they're still using core-1.x.x

**Comment by evancz** [comment]
It is really up to `elm-package diff` what the next version will be. It says it is a major change, so it should be 2.0.0 :)
