### ISSUE TITLE
Alpine Linux execution error with every elm executable

### ISSUE THREAD

**Issue by cprieto** [elm-lang/core#941]
Installed in Alpine Linux 3.7, installation of elm 0.18.0 went without issues as a normal user:

`npm install --prefix /opt/elm elm -g`

Package install without problems or warnings.

PATH:

`PATH='/opt/elm/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'

And which reports elm in the correct place:

`/opt/elm/bin/elm`

Executing any of the elm applications fails with the following message:

```
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: spawn /opt/elm/lib/node_modules/elm/Elm-Platform/0.18.0/.cabal-sandbox/bin/elm ENOENT
    at _errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:686:11)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
```

Tried changing the path directly to the .cabal-sandbox/bin and the same error happens. I followed the same instructions and tried as in the issue #787 and error continues.

**Comment by evancz** [comment]
I recommend asking around on https://discourse.elm-lang.org/ or http://elmlang.herokuapp.com/ for help with this. It definitely is not caused by the core libraries though, and I bet someone in the community can help more effectively than I can.
