### ISSUE TITLE
Need a way to define and enumerate union types.

### ISSUE THREAD

**Issue by congwenma** [elm-lang/core#943]
I find myself defining `union types`, and when trying to use them I have to explicitly use their names instead of just enumerate through them,

It seems that by having `union type` automatically classifying types(which is wonderful), we lost a use case of dynamically expand its content into possible test cases. Would it be too unstable to have this bit of dynamic-ality in elm? 

In any case, I'm wondering how the following test case is possible in elm.

```javascript
const alphabet = "abcdefghijklmnopqrstuvwxyz".split('') 
// Here's what I'd imagine would be UnionType in elm ->
//     type Alphabet = A | B | C | D | E.....
const germanAlphabet = "abcdefghijklmnopqrstuvwxyzäöüß".split('')

const expand = n => [...Array(n)]

const testSetup = (unionType) => {
  const randomTestString = expand(1000) 
    .reduce((accu) => {
       const alphabetIndex = Math.floor(Math.random() * unionType.length);
       return accu + unionType[alphabetIndex]; 
       // ^^ Can you do something like this in Elm?
    }, "");
  return randomTestString
}

const randomText = testSetup(alphabet)
const randomGermanText = testSetup(germanAlphabet)
```

And lets pretend that in this fictional universe, people are very proud of a letter they are assigned to, so much so that they would gladly label themselves in this fashion of elm:

```elm
type alias Person = { 
  name: String,
  letter: AlphaBet
}
```

**Comment by evancz** [comment]
This seems like a language feature request, but I do not get it at all. We do not have any short-term plans to make changes to `type` declarations though, so I will close.
