### ISSUE TITLE
`foldl` and `foldr` different from Haskell's?

### ISSUE THREAD

**Issue by Spaxe** [elm-lang/core#956]
I'm curious why Elm's implementation of `foldl` and `foldr` has identical signatures, where as Haskell's doesn't. 

For example:

Elm: `foldl : (a -> b -> b) -> b -> List a -> b`

Haskell: `foldl :: (b -> a -> b) -> b -> [a] -> b`

Source code: https://github.com/elm-lang/core/blob/master/src/List.elm#L148-L184

**Comment by evancz** [comment]
Elm does it like Standard ML, and I always thought that was nicer. So the real question is why did Haskell do something different than Standard ML? ;)

The short version is that (1) I find it so much easier to remember just one thing, (2) we say "the data structure is always the last argument" is a good guide to writing functions and that means our type fits better with other functions in the language, and (3) I think the "oh, but it's like math" argument ignores practical considerations.

I recommend asking questions like this on the Elm slack in the future though! They can give just as nice answers, but it is a nicer allocation of labor!
