### ISSUE TITLE
Documentation for JSON.Decode.Value is misleading

### ISSUE THREAD

**Issue by arowM** [elm-lang/core#957]
In `master` branch, documentation about `JSON.Decode.Value` is as follows.

> A JSON value.

But I guess it is misleading because `Value` is now not only for JSON objects.
(Though it is defined in **`JSON`**`.Decode` module...)
For example, it is also used for `Html.Events.on` to handle [`Event` object](https://developer.mozilla.org/ja/docs/Web/API/Event), which is not exactly the JSON object.
In another instace, we use `Value` as an input/output type of ports to handle some JS objects that Elm cannot handle such as `File` object.
(In fact, I have not realized that `Value` can be used to pass `File` object to ports at first.)

P.S.
I'm not sure that this is the right place to report about `JSON.Decode` module because it seems to be moving to [independent package](https://github.com/elm-lang/json), so if this is not the right place, I'll apologize.

**Comment by toraritte** [comment]
`Value` is originally defined in `Json.Encode` and [it is only aliased in `Json.Decode`](https://github.com/elm-lang/json/blob/master/src/Json/Decode.elm#L405). On the other hand, `Json.Encode.Value`'s documentation is more general by saying that it "_[represents a JavaScript value](http://package.elm-lang.org/packages/elm-lang/core/latest/Json-Encode#Value)_".

**Comment by arowM** [comment]
Thanks. So, how about using the same documentation as `Json.Encode.Value` to avoid confusion.

**Comment by evancz** [comment]
Making the PR about it the canonical one for this
